--# -path=.:../romance:../common:../abstract:../../prelude

concrete LexiconPor of Lexicon = CatPor ** open
  (M=MorphoPor), ParadigmsPor, BeschPor, Prelude in {

flags
  optimize=values ;

lin
   easy_A2V = mkA2V (regA "fácil") dative genitive ;
   married_A2 = mkA2 (regA "casado") dative ;
   probable_AS = mkAS (regA "provável") ;
   fun_AV = mkAV (regA "divertido") genitive ;
   -- A
   bad_A       = prefA (mkADeg (regA "mau") (regA "pior")) ;
   beautiful_A = prefA (regADeg "belo") ;    -- bela
   big_A       = prefA (regADeg "grande") ;
   black_A     = regADeg "preto" ;	-- preta
   blue_A      = regADeg "azul" ;
   broad_A     = regADeg "largo" ;
   brown_A     = regADeg "marrom" ; --- *
   clean_A     = regADeg "limpo" ;
   clever_A    = regADeg "inteligente" ;
   cold_A      = regADeg "frio" ;		-- fria
   correct_A   = regA "correcto" ;
   dirty_A     = regADeg "sujo" ;
   dry_A       = regA "seco" ;
   dull_A      = regA "desafilado" ;
   empty_A     = regADeg "vazio" ;
   full_A      = regA "lleno" ;
   good_A      = prefA (mkADeg (regA "bom") (regA "melhor")) ; ---- adv?
   green_A     = regADeg "verde" ;
   heavy_A     = regA "pesado" ;
   hot_A       = regADeg "quente" ;
   important_A = regADeg "importante" ;
   long_A      = regADeg "longo" ;
   narrow_A    = regADeg "estreito" ;
   near_A      = regA "cercano" ;
   new_A       = prefA (regADeg "novo") ;
   old_A       =  prefA (regADeg "velho") ;
   red_A       = regADeg "vermelho" ;
   rotten_A    = regA "podrido" ;
   round_A     = regA "redondo" ;
   sharp_A     = regA "filoso" ; -- afilado, puntiagudo
   short_A     = regADeg "curto" ; --- breve, pequeno, baixo
   small_A     = prefA (regADeg "pequeno") ;
   smooth_A    = regA "liso" ;     -- suave
   straight_A  = regA "directo" ;
   stupid_A    = regADeg "estúpido" ;
   thick_A     = regADeg "grosso" ;
   thin_A      = regADeg "fino" ;			-- delgado
   ugly_A      = regADeg "feio" ;
   warm_A      = regADeg "quente" ;
   wet_A       = regA "mojado" ;
   white_A     = compADeg (regA "blanco") ;
   wide_A      = regA "ancho" ;      -- extenso
   yellow_A    = regADeg "amarillo" ;
   young_A     = prefA (mkA "joven" "joven" "jóvenes" "jóvenes" "jovenamente") ;
   already_Adv = mkAdv "ya" ;
   far_Adv = mkAdv "lejos" ; ----?
   now_Adv = mkAdv "ahora" ;
   today_Adv = mkAdv "hoje" ;
   brother_N2 = deN2 (mkN "irmão") ;
   father_N2 = deN2 (mkN "pai") ;
   mother_N2 = deN2 (mkN "mãe" feminine) ;
   distance_N3 = mkN3 (mkN "distância") genitive dative ;
   -- N
   airplane_N   = mkN "avião" masculine ; -- is masculine
   animal_N     = mkN "animal" ; -- masc (sometimes fem when adj)
   apartment_N  = mkN "apartamento" ;
   apple_N      = mkN "maçã" "maçãs" ;
   art_N        = mkN "arte" feminine ;
   ashes_N      = mkN "cinza" ;
   baby_N       = mkN "bebê" ;		-- can be used for both fem. & masc.
   back_N       = mkN "costas" "costas" feminine ;
   bank_N       = mkN "banco" ;
   bark_N       = mkN "casca" ;
   beer_N       = mkN "cerveja" ;
   belly_N      = mkN "barriga" ;
   bike_N       = mkN "bicicleta" ;
   bird_N       = mkN "pássaro" ;
   blood_N      = mkN "sangue" nonExist ;
   boat_N       = mkN "bote" ;
   bone_N       = mkN "osso" ;
   book_N       = mkN "livro" ;
   boot_N       = mkN "bota" ;
   boss_N       = mkN "chefe"; -- Fem can be both "chefa" or "chefe" ;
   boy_N        = mkN "menino" ;
   bread_N      = mkN "pão" "pães" masculine ;
   breast_N     = mkN "seio" ;             -- pecho
   butter_N     = mkN "manteiga" ;
   camera_N     = mkN "câmera" ; -- ["máquina fotográfica"]
   cap_N        = mkN "gorro" ;
   car_N        = mkN "carro" ;
   carpet_N     = mkN "tapete" ;
   cat_N        = mkN "gato" ;		-- gata
   ceiling_N    = mkN "teto" ;
   chair_N      = mkN "cadeira" ;
   cheese_N     = mkN "queijo" ;
   child_N      = mkN "criança" ;
   church_N     = mkN "igreja" ;
   city_N       = mkN "cidade" feminine ;
   cloud_N      = mkN "nuvem" feminine ;
   coat_N       = mkN "abrigo" ;
   computer_N   = mkN "computador" ;
   country_N    = mkN "país" ;		-- masc
   cousin_N     = mkN "primo" ;
   cow_N        = mkN "vaca" ;
   day_N        = mkN "dia" masculine ;
   doctor_N     = mkN "médico" ;		-- médica
   dog_N        = mkN "cachorro" ;		-- cadela
   door_N       = mkN "porta" ;
   dust_N       = mkN "poeira" nonExist ;
   ear_N        = mkN "orelha" ;
   earth_N      = mkN "terra" ;
   egg_N        = mkN "ovo" ;
   enemy_N      = mkN "inimigo" ;		-- inimiga
   eye_N        = mkN "olho" ;
   factory_N    = mkN "fábrica" ;
   fat_N        = mkN "gordura" ;
   feather_N    = mkN "pena" ;
   fingernail_N = mkN "unha" ;
   fire_N       = mkN "fogo" ;
   fish_N       = mkN "peixe" ;
   floor_N      = mkN "chão" nonExist ; -- piso
   flower_N     = mkN "flor" feminine ;
   fog_N        = mkN "névoa" ;
   foot_N       = mkN "pé" ;
   forest_N     = mkN "floresta" ;
   fridge_N     = mkN "geladeira" ;
   friend_N     = mkN "amigo" ;		-- amiga
   fruit_N      = mkN "fruta" ;
   garden_N     = mkN "jardim" ;
   girl_N       = mkN "menina" ;
   glove_N      = mkN "luva" ;
   gold_N       = mkN "ouro" nonExist ;
   grammar_N    = mkN "gramática" ;
   grass_N      = mkN "grama" nonExist ;
   guts_N       = mkN "tripa" ;
   hair_N       = mkN "cabelo" nonExist ;
   hand_N       = mkN "mão" "mãos" feminine ;
   harbour_N    = mkN "porto" ;
   hat_N        = mkN "chapéu" ;
   head_N       = mkN "cabeça" ;
   heart_N      = mkN "coração" masculine ;
   hill_N       = mkN "morro" ; -- colina
   horn_N       = mkN "chifre" ;
   horse_N      = mkN "cavalo" ;
   house_N      = mkN "casa" ;
   husband_N    = mkN "marido" ;  -- esposo
   ice_N        = mkN "gelo" ;
   industry_N   = mkN "indústria" ;
   iron_N       = mkN "ferro" ;
   king_N       = mkN "rei" ;
   knee_N       = mkN "joelho" ;
   lake_N       = mkN "lago" ;
   lamp_N       = mkN "lâmpada" ;
   language_N   = mkN "linguagem" ;
   leaf_N       = mkN "folha" ;
   leather_N    = mkN "couro" nonExist ;
   leg_N        = mkN "perna" ;
   liver_N      = mkN "fígado" ;
   louse_N      = mkN "piolho" ;
   love_N       = mkN "amor" ;
   man_N        = mkN "homem" ;		-- masc
   meat_N       = mkN "carne" feminine ;
   milk_N       = mkN "leite" ;
   moon_N       = mkN "lua" ;
   mountain_N   = mkN "montanha" ;
   mouth_N      = mkN "boca" ;
   music_N      = mkN "música" ;
   name_N       = mkN "nome" ;
   neck_N       = mkN "pescoço" ;
   newspaper_N  = mkN "jornal" ;
   night_N      = mkN "noite" feminine ;
   nose_N       = mkN "nariz" ;
   number_N     = mkN "número" ;
   oil_N        = mkN "óleo" ;
   paper_N      = mkN "papel" ;
   peace_N      = mkN "paz" feminine ;
   pen_N        = mkN "caneta" ;
   person_N     = mkN "pessoa" ;
   planet_N     = mkN "planeta" masculine ;
   plastic_N    = mkN "plástico" ;
   policeman_N  = mkN "policial" ;
   priest_N     = mkN "padre" ;		-- masc
   queen_N      = mkN "rainha" ;
   question_N   = mkN "pergunta" ;
   radio_N      = mkN "rádio" ;
   rain_N       = mkN "chuva" ;
   reason_N     = mkN "razão" ;
   religion_N   = mkN "religião" ;
   restaurant_N = mkN "restaurante" ;
   river_N      = mkN "rio" ;
   road_N       = mkN "estrada" ;
   rock_N       = mkN "rocha" ;
   roof_N       = mkN "telhado" ;
   root_N       = mkN "raiz" feminine ;
   rope_N       = mkN "corda" ;
   rubber_N     = mkN "borracha" ;
   rule_N       = mkN "regra" ;
   salt_N       = mkN "sal" ;
   sand_N       = mkN "areia" nonExist ;
   school_N     = mkN "escola" ;
   science_N    = mkN "ciência" ;
   sea_N        = mkN "mar" ;
   seed_N       = mkN "semente" ;
   sheep_N      = mkN "ovelha" ;
   ship_N       = mkN "navio" ;
   shirt_N      = mkN "camisa" ;
   shoe_N       = mkN "sapato" ;
   shop_N       = mkN "loja" ;
   silver_N     = mkN "prata" nonExist ;
   sister_N     = mkN "irmã" ;
   skin_N       = mkN "pele" feminine ;
   sky_N        = mkN "céu" ;
   smoke_N      = mkN "fumaça" nonExist ;
   snake_N      = mkN "cobra" ;
   snow_N       = mkN "neve" nonExist feminine ;
   sock_N       = mkN "meia" ;
   song_N       = mkN "canção" "canções" feminine ;
   star_N       = mkN "estrela" ;
   steel_N      = mkN "aço" nonExist ;
   stick_N      = mkN "bastão" "bastões" ;
   stone_N      = mkN "pedra" ;
   stove_N      = mkN "forno" ;
   student_N    = mkN "estudante" ;	-- used both for fem & masc
   sun_N        = mkN "sol" ;
   table_N      = mkN "mesa" ;
   tail_N       = mkN "rabo" ;
   teacher_N    = mkN "professor" ;
   television_N = mkN "televisão" ;
   tongue_N     = mkN "língua" ;
   tooth_N      = mkN "dente" ;
   train_N      = mkN "trem" ;
   tree_N       = mkN "árvore" feminine ;
   university_N = mkN "universidade" ;
   village_N    = mkN "vila" ;
   war_N        = mkN "guerra" ;
   water_N      = mkN "água" ;
   wife_N       = mkN "esposa" ;
   wind_N       = mkN "vento" ;
   window_N     = mkN "janela" ;
   wine_N       = mkN "vinho" ;
   wing_N       = mkN "asa" ;
   woman_N      = mkN "mulher" feminine ;
   wood_N       = mkN "madeira" ;
   worm_N       = mkN "verme" ;             -- lombriga (Fem)
   year_N       = mkN "ano" ;
   left_Ord = M.mkOrd (regA "esquerda") ;
   right_Ord = M.mkOrd (regA "direita") ;
   john_PN = mkPN "João" masculine ;
   paris_PN = mkPN "Paris" feminine ;
   rain_V0 = mkV0 (verboV (llover_89 "chover")) ;
   paint_V2A = mkV2A (regV "pintar") accusative (mkPrep "em") ;
   ask_V2Q = mkV2Q (regV "perguntar") dative ;
   answer_V2S = mkV2S (regV "responder") dative ;
   beg_V2V = mkV2V (mkV "rogar" "rogo") accusative dative ;   -- pedir
   -- V2
   bite_V2       = dirV2 (verboV (morder_50b "morder")) ;
   break_V2      = dirV2 (special_ppV (regV "romper") "rompido") ;
   buy_V2        = dirV2 (regV "comprar") ;
   close_V2      = dirV2 (mkV "fechar" "fechado") ;
   count_V2      = dirV2 (verboV (contar_38b "contar")) ;
   cut_V2        = dirV2 (regV "cortar") ;
   do_V2         =  dirV2 (verboV (hacer_44 "fazer")) ;
   drink_V2      = dirV2 (regV "beber") ;
   eat_V2        = dirV2 (regV "comer") ;
   fear_V2       = dirV2 (regV "temer") ;
   fight_V2      = dirV2 (regV "lutar") ;
   find_V2       = dirV2 (verboV (encontrar_38 "encontrar")) ;
   forget_V2     = dirV2 (regV "esquecer") ;
   hate_V2       = dirV2 (mkV "odiar" "ódio") ;
   hear_V2       = dirV2 (mkV (oir_51 "ouvir")) ;
   hit_V2        = dirV2 (regV "bater") ;
   hold_V2       = dirV2 (verboV (tener_4 "ter")) ;
   hunt_V2       = dirV2 (regV "caçar") ;
   kill_V2       = dirV2 (regV "matar") ;
   know_V2       = mkV2 (verboV (conocer_25 "conhecer")) ;
   learn_V2      = dirV2 (regV "aprender") ;
   leave_V2      = dirV2 (regV "partir") ;	-- irse, dejar
   like_V2       = dirV2 (regV "gostar") ;
   listen_V2     = dirV2 (regV "escutar") ;
   lose_V2       = dirV2 (verboV (defender_29 "perder")) ;
   love_V2       = dirV2 (regV "amar") ;
   open_V2       = dirV2 (special_ppV (regV "abrir") "aberto") ;
   play_V2       = dirV2 (verboV (jugar_47 "jogar")) ;
   pull_V2       = dirV2 (regV "tirar") ;
   push_V2       = dirV2 (regV "empurrar") ;
   put_V2        = dirV2 (verboV (poner_60 "por")) ;
   read_V2       = dirV2 (verboV (creer_26 "ler")) ;
   rub_V2        = dirV2 (regV "resfregar") ;
   scratch_V2    = dirV2 (regV "rascar") ;
   see_V2        = dirV2 (verboV (ver_83 "ver")) ;
   seek_V2       = dirV2 (regV "buscar") ;
   speak_V2      = dirV2 (regV "falar") ;
   split_V2      = dirV2 (regV "separar") ; -- dividir,) ;
   squeeze_V2    = dirV2 (regV "exprimir") ;
   stab_V2       = dirV2 (regV "apuñalar") ;
   suck_V2       = dirV2 (regV "chupar") ;
   switch8off_V2 = dirV2 (regV "apagar") ;
   switch8on_V2  = dirV2 (regV "ligar") ; -- acender
   teach_V2      = dirV2 (regV "enseñar") ;
   throw_V2      = dirV2 (regV "tirar") ;
   tie_V2        = dirV2 (regV "atar") ;
   understand_V2 = dirV2 (mkV "entender" "entiendo") ;
   wait_V2       = mkV2 (regV "esperar") dative ;
   wash_V2       = dirV2 (regV "lavar") ;
   watch_V2      = dirV2 (regV "mirar") ;		-- ver
   win_V2        = dirV2 (regV "ganar") ;
   wipe_V2       = dirV2 (regV "secar") ;
   write_V2      = dirV2 (special_ppV (regV "escribir") "escrito") ;
   add_V3 = dirV3 (regV "sumar") dative ;
   give_V3 = dirdirV3 (verboV (dar_27 "dar")) ;
   sell_V3 = dirV3 (regV "vender") dative ;
   send_V3 = dirV3 (regV "mandar") dative ; -- enviar
   talk_V3 = mkV3 (regV "hablar") dative genitive ;
   become_VA = reflV (mkV "converter" "convertido") ;  --- convertirse en, volverse, ponerse
   know_VQ = mkVQ (verboV (saber_71 "saber")) ;
   wonder_VQ = mkVQ (reflV (regV "preguntar")) ;
   fear_VS = mkVS (regV "temer") ;
   hope_VS = mkVS (regV "esperar") ;
   know_VS = mkVS (verboV (saber_71 "saber")) ;
   say_VS = mkVS (verboV (decir_28 "dizer")) ;
   -- V
   blow_V    = regV "soplar" ;
   breathe_V = (regV "respirar") ;
   burn_V    = regV "quemar" ;
   come_V    = verboV (venir_82 "vir") ;
   die_V     = verboV (morir_35b "morrer") ;
   dig_V     = regV "escarbar" ;
   fall_V    = verboV (caer_20 "caer") ;
   float_V   = regV "flotar" ;
   flow_V    = verboV (influir_45 "fluir") ;             -- circular
   fly_V     = regV "volar" ;
   freeze_V  = regV "congelar" ;
   go_V      = (verboV (ir_46 "ir")) ;
   jump_V    = regV "saltar" ;
   laugh_V   = regV "reir" ; ----V reír_67
   lie_V     = reflV (regV "acostar") ; --  "acostarse"
   live_V    = verboV (vivir_7 "viver") ;
   play_V    = regV "jugar" ;
   run_V     = regV "correr" ;
   sew_V     = regV "coser" ;
   sing_V    = regV "cantar" ;
   sit_V     = reflV (mkV "sentar" "siento") ;
   sleep_V   = verboV (dormir_35 "dormir") ;
   smell_V   = verboV (oler_52 "oler") ;
   spit_V    = regV "escupir" ;
   stand_V   = verboV (estar_2 "estar") ; ---- "estar de pie" ;
   stop_V    = regV "parar" ;
   swell_V   = regV "tragar" ;
   swim_V    = regV "nadar" ;
   think_V   = regV "pensar" ;
   travel_V  = regV "viajar" ;
   turn_V    = regV "doblar" ;
   vomit_V   = regV "vomitar" ;
   walk_V    = mkV "caminhar" ;

} ;
