--# -path=.:../romance:../common:../abstract:../../prelude

concrete LexiconPor of Lexicon = CatPor ** open
  (M=MorphoPor), ParadigmsPor, BeschPor, (B=IrregBeschPor), Prelude in {

flags
  optimize=values ;
  coding=utf8 ;

lin
   easy_A2V = mkA2V (mkA "fácil") dative genitive ;
   married_A2 = mkA2 (mkA "casado") dative ;
   probable_AS = mkAS (mkA "provável") ;
   fun_AV = mkAV (mkA "divertido") genitive ;
   -- A
   bad_A       = prefA (mkA (mkA "mau") (mkA "pior")) ;
   beautiful_A = prefA (mkA "belo") ;    -- bela
   big_A       = prefA (mkA "grande") ;
   black_A     = mkA "preto" ;	-- preta
   blue_A      = mkA "azul" ;
   broad_A     = mkA "largo" ;
   brown_A     = mkA "marrom" ; --- *
   clean_A     = mkA "limpo" ;
   clever_A    = mkA "inteligente" ;
   cold_A      = mkA "frio" ;		-- fria
   correct_A   = mkA "correto" | mkA "correcto" ;
   dirty_A     = mkA "sujo" ;
   dry_A       = mkA "seco" ;
   dull_A      = mkA "desafilado" ;
   empty_A     = mkA "vazio" ;
   full_A      = mkA "cheio" ;
   good_A      = prefA (mkA (mkA "bom") (mkA "melhor")) ; ---- adv?
   green_A     = mkA "verde" ;
   heavy_A     = mkA "pesado" ;
   hot_A       = mkA "quente" ;
   important_A = mkA "importante" ;
   long_A      = mkA "longo" ;
   narrow_A    = mkA "estreito" ;
   near_A      = mkA "perto" ;
   new_A       = prefA (mkA "novo") ;
   old_A       =  prefA (mkA "velho") ;
   ready_A     = mkA "pronto" ;
   red_A       = mkA "vermelho" ;
   rotten_A    = mkA "podre" ;
   round_A     = mkA "redondo" ;
   sharp_A     = mkA "afiado" ; -- pontiagudo
   short_A     = mkA "curto" ; --- breve, pequeno, baixo
   small_A     = prefA (mkA "pequeno") ;
   smooth_A    = mkA "liso" ;     -- suave
   straight_A  = mkA "direto" | mkA "directo" ; -- reto
   stupid_A    = mkA "estúpido" ;
   thick_A     = mkA "grosso" ;
   thin_A      = mkA "fino" ; -- delgado, magro
   ugly_A      = mkA "feio" ;
   uncertain_A = mkA "incerto" ;
   warm_A      = mkA "quente" ;
   wet_A       = mkA "molhado" ;
   white_A     = compADeg (mkA "branco") ;
   wide_A      = mkA "largo" ; -- extenso
   yellow_A    = mkA "amarelo" ;
   young_A     = prefA (mkA "jovem" "jovem" "jovens" "jovens" "juvenilmente") ;
   already_Adv = mkAdv "já" ;
   far_Adv = mkAdv "longe" ; ----?
   now_Adv = mkAdv "agora" ;
   today_Adv = mkAdv "hoje" ;
   brother_N2 = deN2 (mkN "irmão") ;
   father_N2 = deN2 (mkN "pai") ;
   mother_N2 = deN2 (mkN "mãe" feminine) ;
   distance_N3 = mkN3 (mkN "distância") genitive dative ;
   -- N
   airplane_N   = mkN "avião" masculine ; -- is masculine
   animal_N     = mkN "animal" ; -- masc (sometimes fem when adj)
   apartment_N  = mkN "apartamento" ;
   apple_N      = mkN "maçã" "maçãs" ;
   art_N        = mkN "arte" feminine ;
   ashes_N      = mkN "cinza" ;
   baby_N       = mkN "bebê" ;		-- can be used for both fem. & masc.
   back_N       = mkN "costas" "costas" feminine ;
   bank_N       = mkN "banco" ;
   bark_N       = mkN "casca" ;
   beer_N       = mkN "cerveja" ;
   belly_N      = mkN "barriga" ;
   bike_N       = mkN "bicicleta" ;
   bird_N       = mkN "pássaro" ;
   blood_N      = mkN "sangue" nonExist ;
   boat_N       = mkN "bote" ;
   bone_N       = mkN "osso" ;
   book_N       = mkN "livro" ;
   boot_N       = mkN "bota" ;
   boss_N       = mkN "chefe"; -- Fem can be both "chefa" or "chefe" ;
   boy_N        = mkN "menino" ;
   bread_N      = mkN "pão" "pães" masculine ;
   breast_N     = mkN "seio" ;             -- pecho
   butter_N     = mkN "manteiga" ;
   camera_N     = mkN "câmera" ; -- ["máquina fotográfica"]
   cap_N        = mkN "gorro" ;
   car_N        = mkN "carro" ;
   carpet_N     = mkN "tapete" ;
   cat_N        = mkN "gato" ;		-- gata
   ceiling_N    = mkN "teto" ;
   chair_N      = mkN "cadeira" ;
   cheese_N     = mkN "queijo" ;
   child_N      = mkN "criança" ;
   church_N     = mkN "igreja" ;
   city_N       = mkN "cidade" feminine ;
   cloud_N      = mkN "nuvem" feminine ;
   coat_N       = mkN "abrigo" ;
   computer_N   = mkN "computador" ;
   country_N    = mkN "país" ;		-- masc
   cousin_N     = mkN "primo" ;
   cow_N        = mkN "vaca" ;
   day_N        = mkN "dia" masculine ;
   doctor_N     = mkN "médico" ;		-- médica
   dog_N        = mkN "cachorro" ;		-- cadela
   door_N       = mkN "porta" ;
   dust_N       = mkN "poeira" nonExist ;
   ear_N        = mkN "orelha" ;
   earth_N      = mkN "terra" ;
   egg_N        = mkN "ovo" ;
   enemy_N      = mkN "inimigo" ;		-- inimiga
   eye_N        = mkN "olho" ;
   factory_N    = mkN "fábrica" ;
   fat_N        = mkN "gordura" ;
   feather_N    = mkN "pena" ;
   fingernail_N = mkN "unha" ;
   fire_N       = mkN "fogo" ;
   fish_N       = mkN "peixe" ;
   floor_N      = mkN "chão" nonExist ; -- piso
   flower_N     = mkN "flor" feminine ;
   fog_N        = mkN "névoa" ;
   foot_N       = mkN "pé" ;
   forest_N     = mkN "floresta" ;
   fridge_N     = mkN "geladeira" ;
   friend_N     = mkN "amigo" ;		-- amiga
   fruit_N      = mkN "fruta" ;
   garden_N     = mkN "jardim" ;
   girl_N       = mkN "menina" ;
   glove_N      = mkN "luva" ;
   gold_N       = mkN "ouro" nonExist ;
   grammar_N    = mkN "gramática" ;
   grass_N      = mkN "grama" nonExist ;
   guts_N       = mkN "tripa" ;
   hair_N       = mkN "cabelo" nonExist ;
   hand_N       = mkN "mão" "mãos" feminine ;
   harbour_N    = mkN "porto" ;
   hat_N        = mkN "chapéu" ;
   head_N       = mkN "cabeça" ;
   heart_N      = mkN "coração" masculine ;
   hill_N       = mkN "morro" ; -- colina
   horn_N       = mkN "chifre" ;
   horse_N      = mkN "cavalo" ;
   house_N      = mkN "casa" ;
   husband_N    = mkN "marido" ;  -- esposo
   ice_N        = mkN "gelo" ;
   industry_N   = mkN "indústria" ;
   iron_N       = mkN "ferro" ;
   king_N       = mkN "rei" ;
   knee_N       = mkN "joelho" ;
   lake_N       = mkN "lago" ;
   lamp_N       = mkN "lâmpada" ;
   language_N   = mkN "linguagem" ;
   leaf_N       = mkN "folha" ;
   leather_N    = mkN "couro" nonExist ;
   leg_N        = mkN "perna" ;
   liver_N      = mkN "fígado" ;
   louse_N      = mkN "piolho" ;
   love_N       = mkN "amor" ;
   man_N        = mkN "homem" ;		-- masc
   meat_N       = mkN "carne" feminine ;
   milk_N       = mkN "leite" ;
   moon_N       = mkN "lua" ;
   mountain_N   = mkN "montanha" ;
   mouth_N      = mkN "boca" ;
   music_N      = mkN "música" ;
   name_N       = mkN "nome" ;
   neck_N       = mkN "pescoço" ;
   newspaper_N  = mkN "jornal" ;
   night_N      = mkN "noite" feminine ;
   nose_N       = mkN "nariz" ;
   number_N     = mkN "número" ;
   oil_N        = mkN "óleo" ;
   paper_N      = mkN "papel" ;
   peace_N      = mkN "paz" feminine ;
   pen_N        = mkN "caneta" ;
   person_N     = mkN "pessoa" ;
   planet_N     = mkN "planeta" masculine ;
   plastic_N    = mkN "plástico" ;
   policeman_N  = mkN "policial" ;
   priest_N     = mkN "padre" ;		-- masc
   queen_N      = mkN "rainha" ;
   question_N   = mkN "pergunta" ;
   radio_N      = mkN "rádio" ;
   rain_N       = mkN "chuva" ;
   reason_N     = mkN "razão" ;
   religion_N   = mkN "religião" ;
   restaurant_N = mkN "restaurante" ;
   river_N      = mkN "rio" ;
   road_N       = mkN "estrada" ;
   rock_N       = mkN "rocha" ;
   roof_N       = mkN "telhado" ;
   root_N       = mkN "raiz" feminine ;
   rope_N       = mkN "corda" ;
   rubber_N     = mkN "borracha" ;
   rule_N       = mkN "regra" ;
   salt_N       = mkN "sal" ;
   sand_N       = mkN "areia" nonExist ;
   school_N     = mkN "escola" ;
   science_N    = mkN "ciência" ;
   sea_N        = mkN "mar" ;
   seed_N       = mkN "semente" ;
   sheep_N      = mkN "ovelha" ;
   ship_N       = mkN "navio" ;
   shirt_N      = mkN "camisa" ;
   shoe_N       = mkN "sapato" ;
   shop_N       = mkN "loja" ;
   silver_N     = mkN "prata" nonExist ;
   sister_N     = mkN "irmã" ;
   skin_N       = mkN "pele" feminine ;
   sky_N        = mkN "céu" ;
   smoke_N      = mkN "fumaça" nonExist ;
   snake_N      = mkN "cobra" ;
   snow_N       = mkN "neve" nonExist feminine ;
   sock_N       = mkN "meia" ;
   song_N       = mkN "canção" "canções" feminine ;
   star_N       = mkN "estrela" ;
   steel_N      = mkN "aço" nonExist ;
   stick_N      = mkN "bastão" "bastões" ;
   stone_N      = mkN "pedra" ;
   stove_N      = mkN "forno" ;
   student_N    = mkN "estudante" ;	-- used both for fem & masc
   sun_N        = mkN "sol" ;
   table_N      = mkN "mesa" ;
   tail_N       = mkN "rabo" ;
   teacher_N    = mkN "professor" ;
   television_N = mkN "televisão" ;
   tongue_N     = mkN "língua" ;
   tooth_N      = mkN "dente" ;
   train_N      = mkN "trem" ;
   tree_N       = mkN "árvore" feminine ;
   university_N = mkN "universidade" ;
   village_N    = mkN "vila" ;
   war_N        = mkN "guerra" ;
   water_N      = mkN "água" ;
   wife_N       = mkN "esposa" ;
   wind_N       = mkN "vento" ;
   window_N     = mkN "janela" ;
   wine_N       = mkN "vinho" ;
   wing_N       = mkN "asa" ;
   woman_N      = mkN "mulher" feminine ;
   wood_N       = mkN "madeira" ;
   worm_N       = mkN "verme" ;             -- lombriga (Fem)
   year_N       = mkN "ano" ;
   left_Ord = M.mkOrd (regA "esquerda") ;
   right_Ord = M.mkOrd (regA "direita") ;
   john_PN = mkPN "João" masculine ;
   paris_PN = mkPN "Paris" feminine ;
   -- V
   rain_V0 = mkV0 B.chover_V ;
   paint_V2A = mkV2A B.pintar_V accusative (mkPrep "em") ;
   ask_V2Q = mkV2Q B.perguntar_V dative ;
   answer_V2S = mkV2S B.responder_V dative ;
   beg_V2V = mkV2V B.rogar_V accusative dative ;   -- pedir
   bite_V2       = dirV2 B.morder_V ;
   break_V2      = dirV2 B.quebrar_V ;
   buy_V2        = dirV2 B.comprar_V ;
   close_V2      = dirV2 B.fechar_V ;
   count_V2      = dirV2 B.contar_V ;
   cut_V2        = dirV2 B.cortar_V ;
   do_V2         =  dirV2 B.fazer_V ;
   drink_V2      = dirV2 B.beber_V ;
   eat_V2        = dirV2 B.comer_V ;
   fear_V2       = dirV2 B.temer_V ;
   fight_V2      = dirV2 B.lutar_V ;
   find_V2       = dirV2 B.encontrar_V ;
   forget_V2     = dirV2 B.esquecer_V ;
   hate_V2       = dirV2 B.odiar_V ;
   hear_V2       = dirV2 B.ouvir_V ;
   hit_V2        = dirV2 B.bater_V ;
   hold_V2       = dirV2 B.ter_V ;
   hunt_V2       = dirV2 B.caçar_V ;
   kill_V2       = dirV2 B.matar_V ;
   know_V2       = mkV2 B.conhecer_V ;
   learn_V2      = dirV2 B.aprender_V ;
   leave_V2      = dirV2 B.partir_V ;
   like_V2       = mkV2 B.gostar_V genitive ;
   listen_V2     = dirV2 B.escutar_V ;
   lose_V2       = dirV2 B.perder_V ;
   love_V2       = dirV2 B.amar_V ;
   open_V2       = dirV2 (special_ppV (mkV "abrir") "aberto") ;
   play_V2       = dirV2 B.jogar_V ;
   pull_V2       = dirV2 B.tirar_V ;
   push_V2       = dirV2 B.empurrar_V ;
   put_V2        = dirV2 B.pôr_V ;
   read_V2       = dirV2 B.ler_V ;
   rub_V2        = dirV2 B.esfregar_V ;
   scratch_V2    = dirV2 B.coçar_V ;
   see_V2        = dirV2 B.ver_V ;
   seek_V2       = dirV2 B.buscar_V ;
   speak_V2      = dirV2 B.falar_V ;
   split_V2      = dirV2 B.separar_V ; -- dividir,) ;
   squeeze_V2    = dirV2 B.apertar_V ;
   stab_V2       = dirV2 B.esfaquear_V ;
   suck_V2       = dirV2 B.chupar_V ;
   switch8off_V2 = dirV2 B.apagar_V ;
   switch8on_V2  = dirV2 B.ligar_V ; -- acender
   teach_V2      = dirV2 B.ensinar_V ;
   throw_V2      = dirV2 B.jogar_V ;
   tie_V2        = dirV2 B.atar_V ;
   understand_V2 = dirV2 B.entender_V ;
   wait_V2       = mkV2 B.esperar_V dative ;
   wash_V2       = dirV2 B.lavar_V ;
   watch_V2      = dirV2 B.ver_V ;		-- ver
   win_V2        = dirV2 B.ganhar_V ;
   wipe_V2       = dirV2 B.remover_V ;
   write_V2      = dirV2 (special_ppV (mkV "escrever") "escrito") ;
   add_V3 = dirV3 B.somar_V dative ;
   give_V3 = dirdirV3 B.dar_V ;
   sell_V3 = dirV3 B.vender_V dative ;
   send_V3 = dirV3 B.enviar_V dative ; -- mandar
   talk_V3 = mkV3 B.falar_V dative genitive ;
   become_VA = reflV B.virar_V ;  --- convertirse en, volverse, ponerse
   know_VQ = mkVQ B.saber_V ;
   wonder_VQ = mkVQ (reflV B.perguntar_V) ;
   fear_VS = mkVS B.temer_V ;
   hope_VS = mkVS B.esperar_V ;
   know_VS = mkVS B.saber_V ;
   say_VS = mkVS B.dizer_V ;
   -- V
   blow_V    = B.assoprar_V ;
   breathe_V = B.respirar_V ;
   burn_V    = B.queimar_V ;
   come_V    = B.vir_V ;
   die_V     = B.morrer_V ;
   dig_V     = B.escavar_V ;
   fall_V    = B.cair_V ;
   float_V   = B.flutuar_V ;
   flow_V    = B.fluir_V ; -- circular
   fly_V     = B.voar_V ;
   freeze_V  = B.congelar_V ;
   go_V      = B.ir_V ;
   jump_V    = B.saltar_V ;
   laugh_V   = B.rir_V ;
   lie_V     = reflV B.mentir_V ;
   live_V    = B.viver_V ;
   play_V    = B.jogar_V ;
   run_V     = B.correr_V ;
   sew_V     = B.costurar_V ;
   sing_V    = B.cantar_V ;
   sit_V     = reflV B.sentar_V ;
   sleep_V   = B.dormir_V ;
   smell_V   = B.cheirar_V ;
   spit_V    = B.cuspir_V ;
   stand_V   = B.estar_V ; ---- "estar de pé" ;
   stop_V    = B.parar_V ;
   swell_V   = B.tragar_V ;
   swim_V    = B.nadar_V ;
   think_V   = B.pensar_V ;
   travel_V  = B.viajar_V ;
   turn_V    = B.virar_V ;
   vomit_V   = B.vomitar_V ;
   walk_V    = B.caminhar_V ;
   -- interj
   alas_Interj = ss "infelizmente" ;
} ;
