concrete Assign_19 of DictEngAbs = CatChi ** open ParadigmsChi in {flags coding=utf8 ; lin
register_V = mkV "注册"; -- 8
present_N = mkN "目前" []; -- 8
oversubscribe_V2 = mkV2 "超额认购";-- 8
mature_A = mkA "成熟"; -- 8
keyboard_N = mkN "键盘"; -- 8
hurry_N = mkN "匆忙"; -- 8
foe_N = mkN "敌人"; -- 8
enthusiastic_A = mkA "热心"; -- 8
digital_A = mkA "数字"; -- 8
converter_N = mkN "变流器";-- 8
christian_A = mkA "基督教";-- 8
bleed_V = mkV "流血"; -- 8
adapt_V = mkV "适应"; -- 8
vegetable_N = mkN "蔬菜"; -- 7
tractor_N = mkN "拖拉机";-- 7
supervision_N = mkN "监督"; -- 7
skid_V = mkV "刹车"; -- 7
seldom_Adv = mkAdv "很少"; -- 7
reimbursement_N = mkN "报销"; -- 7
problematic_A = mkA "有问题"; -- 7
periodic_A = mkA "定期"; -- 7
notwithstanding_Prep = mkPrep "虽然"; -- 7
mine_A = mkA "矿";-- 7
jamaican_A = mkA "牙买加";-- 7
hectic_A = mkA "兴奋"; -- 7
foil_V2 = mkV2 "挫败"; -- 7
emergence_N = mkN "出现"; -- 7
dire_A = mkA "可怕"; -- 7
constructive_A = mkA "建设性";-- 7
calm_V2 = mkV2 "冷静"; -- 7
bloody_A = mkA "血腥"; -- 7
aggregate_N = mkN "合计"; -- 7
whiskey_N = mkN "威士忌酒"; -- 6
unacceptable_A = mkA "不可接受";-- 6
tabloid_N = mkN "小报"; -- 6
sterling_A = mkA "英镑"; -- 6
shut_V2 = mkV2 "关闭"; -- 6
russia_PN = mkPN "俄国"; -- 6
reschedule_V2 = mkV2 "重新安排";-- 6
race_V = mkV "竞赛"; -- 6
picket_N = mkN "纠察"; -- 6
order_V = mkV "命令"; -- 6
nag_V = mkV "唠叨"; -- 6
mania_N = mkN "躁狂症";-- 6
land_V2 = mkV2 "登陆"; -- 6
inclination_N = mkN "倾角"; -- 6
hint_V = mkV "暗示"; -- 6
frame_V2 = mkV2 "框架"; -- 6
eyebrow_N = mkN "眉" ; -- 6
early_on_Adv = mkAdv "在早期" ; -- 6
dentist_N = mkN "牙科医生";-- 6
constrain_V2 = mkV2 "压抑"; -- 6
civic_A = mkA "公民"; -- 6
brunt_N = mkN "首当其冲";-- 6
attributable_A = mkA "归属"; -- 6
afterwards_Adv = mkAdv "事后"; -- 6
wander_V = mkV "漫步"; -- 5
unexplained_A = mkA "原因不明";-- 5
timid_A = mkA "胆小"; -- 5
superintendent_N = mkN "主管"; -- 5
sport_V2 = mkV2 "运动"; -- 5
shortcoming_N = mkN "缺点"; -- 5
sacrifice_N = mkN "牺牲"; -- 5
resiliency_N = mkN "弹性"; -- 5
reassign_V2 = mkV2 "重新分配";-- 5
prostitution_N = mkN "卖淫"; -- 5
please_V = mkV "请" ;-- 5
past_Adv = mkAdv "过去"; -- 5
orchard_N = mkN "果园"; -- 5
much_AdA = mkAdA "多" ; -- 5
mathematics_N = mkN "数学"; -- 5
lie_N = mkN "说谎"; -- 5
isolation_N = mkN "隔离"; -- 5
immense_A = mkA "巨大"; -- 5
happening_N = mkN "事件"; -- 5
frivolous_A = mkA "轻浮"; -- 5
fame_N = mkN "名誉"; -- 5
eloquent_A = mkA "雄辩"; -- 5
distance_V2 = mkV2 "疏远"; -- 5
delete_V2 = mkV2 "删除"; -- 5
cosmetic_A = mkA "美容";-- 5
complication_N = mkN "并发症";-- 5
characteristic_A = mkA "特性"; -- 5
burgeon_V = mkV "发芽"; -- 5
blunt_A = mkA "钝"; -- 5
asian_A = mkA "亚洲人";-- 5
admittedly_Adv = mkAdv "固然"; -- 5
wig_N = mkN "假发"; -- 4
urge_VS = mkVS "敦促"; -- 4
unconventional_A = mkA "非传统";-- 4
tolerate_V2 = mkV2 "容忍"; -- 4
swear_V2 = mkV2 "发誓"; -- 4
st_petersburg_PN = mkPN "圣彼得堡" ; -- 4
smoke_V2 = mkV2 "吸烟"; -- 4
shiver_N = mkN "发抖"; -- 4
ruler_N = mkN "统治者";-- 4
restart_V2 = mkV2 "重新开始";-- 4
recount_V2 = mkV2 "述说"; -- 4
pyramid_N = mkN "金字塔";-- 4
presume_V2 = mkV2 "假定"; -- 4
playground_N = mkN "操场"; -- 4
peg_V = mkV "限制"; -- 4
overhead_A = mkA "在头上"; -- 4
objectivity_N = mkN "客观性";-- 4
mud_N = mkN "泥" ; -- 4
mettle_N = mkN "气概"; -- 4
man_V2 = mkV2 "男人"; -- 4
lengthen_V = mkV "延长"; -- 4
irregularity_N = mkN "不规则";-- 4
instant_N = mkN "瞬间"; -- 4
impact_V2 = mkV2 "碰撞"; -- 4
hepatitis_N = mkN "肝炎"; -- 4
grateful_A = mkA "感谢"; -- 4
funnel_V2 = mkV2 "成漏斗形"; -- 4
floppy_A = mkA "松软"; -- 4
facsimile_N = mkN "传真"; -- 4
enroll_V = mkV "注册"; -- 4
distinguish_V = mkV "区分"; -- 4
dictation_N = mkN "听写"; -- 4
defect_V = mkV "叛变"; -- 4
crush_V = mkV "粉碎"; -- 4
contraceptive_A = mkA "避孕";-- 4
complicity_N = mkN "同谋"; -- 4
choose_VS = mkVS "选择"; -- 4
capitalistic_A = mkA "资本主义";-- 4
boon_N = mkN "福利"; -- 4
awkward_A = mkA "尴尬"; -- 4
alert_A = mkA "警惕"; -- 4
wrest_V2 = mkV2 "夺取"; -- 3
warrior_N = mkN "战士"; -- 3
venezuelan_A = mkA "委内瑞拉";-- 3
unheard_A = mkA "闻所未闻";-- 3
turboprop_N = mkN "涡轮螺旋桨飞机";-- 3
tournament_N = mkN "比赛"; -- 3
thoroughbred_N = mkN "纯种"; -- 3
sway_V2 = mkV2 "摇摆"; -- 3
strenuous_A = mkA "费劲";-- 3
stare_V = mkV "盯"; -- 3
spin_N = mkN "纺";  -- 3
sniff_V = mkV "吸气"; -- 3
simplicity_N = mkN "简单"; -- 3
shadow_V2 = mkV2 "遮蔽"; -- 3
screech_V = mkV "尖叫"; -- 3
russian_N = mkN "俄";  -- 3
restart_V = mkV "重新开始"; -- 3
rehearing_N = mkN "重审"; -- 3
readiness_N = mkN "准备就绪";-- 3
puny_A = mkA "弱小"; -- 3
press_V2V = mkV2V "压迫"; -- 3
polite_A = mkA "有礼貌";-- 3
pinch_V2 = mkV2 "掐掉"; -- 3
patch_V2 = mkV2 "修补"; -- 3
ornamental_A = mkA "装饰"; -- 3
observe_V = mkV "观察" ; -- 3
myth_N = mkN "神话"; -- 3
mirror_N = mkN "镜子"; -- 3
marke_VS = mkVS "做标记"; -- 3
literacy_N = mkN "读写能力";-- 3
legalization_N = mkN "合法化";-- 3
irrational_A = mkA "不合理";-- 3
ingenious_A = mkA "巧妙"; -- 3
impeccable_A = mkA "无可挑剔";-- 3
hook_V2 = mkV2 "钩住" ; -- 3
gray_V = mkV "变灰白"; -- 3
generalize_V = mkV "概括"; -- 3
forfeit_V2 = mkV2 "丧失"; -- 3
flair_N = mkN "风骚"; -- 3
fatten_V = mkV "养肥"; -- 3
european_N = mkN "欧洲" [] ;-- 3
effect_V2 = mkV2 "产生"; -- 3
dowdy_A = mkA "寒酸";-- 3
disc_N = mkN "圆盘"; -- 3
derive_V = mkV "派生"; -- 3
cynicism_N = mkN "玩世不恭";-- 3
correspondence_N = mkN "对应"; -- 3
condemnation_N = mkN "非难"; -- 3
clump_N = mkN "丛"; -- 3
chase_N = mkN "追" [] ; -- 3
cab_N = mkN "出租汽车" "辆" ;-- 3
breezy_A = mkA "活泼";-- 3
bleach_N = mkN "漂白"; -- 3
beast_N = mkN "兽";-- 3
attrition_N = mkN "摩擦"; -- 3
appalling_A = mkA "骇人听闻";-- 3
air_conditioned_A = mkA "有空调"; -- 3
accolade_N = mkN "荣誉"; -- 3
wrapper_N = mkN "包装纸" [] ;-- 2
whirlwind_N = mkN "旋风"; -- 2
waterfront_N = mkN "海滨"; -- 2
virtuoso_N = mkN "演奏家";-- 2
vector_N = mkN "向量"; -- 2
unwritten_A = mkA "不成文";-- 2
unravel_V = mkV "解散"; -- 2
unfettered_A = mkA "不受约束";-- 2
unchanging_A = mkA "不变"; -- 2
triple_V2 = mkV2 "增至三倍"; -- 2
torpedo_V2 = mkV2 "用鱼雷攻击"; -- 2
thoroughfare_N = mkN "通道"; -- 2
tell_V2V = mkV2V "告诉"; -- 2
symposium_N = mkN "座谈会";-- 2
superior_N = mkN "优越"; -- 2
stylish_A = mkA "时尚"; -- 2
stereotype_N = mkN "铅板"; -- 2
squander_V2 = mkV2 "挥霍"; -- 2
speed_up_V2 = mkV2 "加速"; -- 2
solidarity_N = mkN "团结"; -- 2
smack_Adv = mkAdv "猛然"; -- 2
sinister_A = mkA "险恶"; -- 2
shooting_N = mkN "拍摄"; -- 2
self_sufficient_A = mkA "自给自足"; -- 2
scour_V2 = mkV2 "冲刷"; -- 2
sanitize_V2 = mkV2 "消毒"; -- 2
rub_V = mkV "擦";-- 2
rim_N = mkN "边"; -- 2
resuscitate_V2 = mkV2 "复苏"; -- 2
repackage_V2 = mkV2 "改头换面";-- 2
redeemable_A = mkA "可赎回"; -- 2
razor_N = mkN "剃刀"; -- 2
quick_Adv = mkAdv "快"; -- 2
prudential_A = mkA "谨慎";-- 2
profess_V2 = mkV2 "宣称"; -- 2
pre_register_V2 = mkV2 "预注册" ; -- 2
politick_V = mkV "谈论政治"; -- 2
pineapple_N = mkN "菠萝"; -- 2
perfect_V2 = mkV2 "使完美"; -- 2
passing_N = mkN "通过"; -- 2
oxide_N = mkN "氧化"; -- 2
outfit_V2 = mkV2 "配备"; -- 2
offer_V3 = mkV3 "提供"; -- 2
notoriety_N = mkN "臭名"; -- 2
necklace_N = mkN "项链"; -- 2
monstrous_A = mkA "巨大"; -- 2
miscalculate_V = mkV "算错"; -- 2
median_N = mkN "中位数";-- 2
malignancy_N = mkN "恶性肿瘤";-- 2
look_VV = mkVV "看"; -- 2
liberate_V2 = mkV2 "解放"; -- 2
laughter_N = mkN "笑声"; -- 2
kettle_N = mkN "水壶"; -- 2
jaguar_N = mkN "美洲虎";-- 2
intersection_N = mkN "路口"; -- 2
innocence_N = mkN "无辜"; -- 2
inconvenience_N = mkN "不方便";-- 2
imperialist_N = mkN "帝国主义者";-- 2
hurry_V2 = mkV2 "赶快"; -- 2
hiding_N = mkN "藏"; -- 2
hasten_V2 = mkV2 "赶快"; -- 2
grumble_V = mkV "抱怨" ; -- 2
going_N = mkN "去" ; -- 2
gamut_N = mkN "域"; -- 2
fraught_A = mkA "忧虑";-- 2
flunk_V2 = mkV2 "失败"; -- 2
firework_N = mkN "焰火"; -- 2
fed_N = mkN "喂"; -- 2
eye_catching_A = mkA "有吸引力"; -- 2
exchangeable_A = mkA "可兑换";-- 2
epidemic_N = mkN "疫情"; -- 2
embolden_V2 = mkV2 "壮胆"; -- 2
earnest_A = mkA "认真"; -- 2
downfall_N = mkN "倒台"; -- 2
dissipate_V = mkV "消散"; -- 2
disdain_V2 = mkV2 "蔑视"; -- 2
detriment_N = mkN "损害"; -- 2
density_N = mkN "密度"; -- 2
decoration_N = mkN "装饰"; -- 2
dangle_V = mkV "吊着"; -- 2
crevasse_N = mkN "裂缝"; -- 2
cornea_N = mkN "角膜"; -- 2
confide_VS = mkVS "信任"; -- 2
compassion_N = mkN "同情"; -- 2
coercion_N = mkN "强迫"; -- 2
clean_N = mkN "清洁"; -- 2
cherry_N = mkN "樱桃"; -- 2
ceaseless_A = mkA "不断"; -- 2
caricature_N = mkN "漫画"; -- 2
buffer_V2 = mkV2 "缓冲"; -- 2
bottomless_A = mkA "深不可测"; -- 2
blast_V2 = mkV2 "爆破"; -- 2
bend_V2 = mkV2 "弯曲"; -- 2
bandage_N = mkN "绷带"; -- 2
avuncular_A = mkA "慈祥"; -- 2
astute_A = mkA "精明"; -- 2
arcane_A = mkA "神秘";-- 2
anchor_V2 = mkV2 "抛锚" ; -- 2
alcoholic_N = mkN "酒精"; -- 2
acquisitive_A = mkA "贪得"; -- 2
zoology_N = mkN "动物学";-- 1
yearly_Adv = mkAdv "每年"; -- 1
wonderment_N = mkN "惊异"; -- 1
whittle_V2 = mkV2 "削减" ; -- 1
well_meaning_A = mkA "善意" ; -- 1
wart_N = mkN "疣"; -- 1
voyage_N = mkN "航程"; -- 1
villain_N = mkN "恶棍"; -- 1
vegetarian_N = mkN "素" ; -- 1
usurpation_N = mkN "篡夺"; -- 1
unthinkable_A = mkA "不可想象";-- 1
unpopularity_N = mkN "不受欢迎";-- 1
uninitiated_A = mkA "没经验";-- 1
unfashionable_A = mkA "过时";-- 1
underpay_V2 = mkV2 "克扣工资"; -- 1
unceremonious_A = mkA "粗鲁";-- 1
ultraviolet_A = mkA "紫外线";-- 1
turkey_N = mkN "火鸡"; -- 1
troublemaker_N = mkN "麻烦制造者"; -- 1
traumatic_A = mkA "创伤"; -- 1
touring_N = mkN "巡演"; -- 1
tomato_N = mkN "西红柿";-- 1
ticklish_A = mkA "不安定";-- 1
thermometer_N = mkN "温度计";-- 1
terrain_N = mkN "地形"; -- 1
telecast_N = mkN "转播"; -- 1
tangle_N = mkN "纠缠"; -- 1
--* syndicate_V2 = mkV2 "聚合"; -- 1 --- also in DictEngChi
swear_VV = mkVV "发誓"; -- 1
supervise_V = mkV "监督"; -- 1
subsume_V2 = mkV2 "归入"; -- 1
stuffy_A = mkA "闷热";  -- 1
strainer_N = mkN "过滤器";-- 1
stocking_N = mkN "放养"; -- 1
stew_N = mkN "炖";  -- 1
stanch_V2 = mkV2 "止血";-- 1
squalor_N = mkN "肮脏"; -- 1
splinter_V2 = mkV2 "分碎"; -- 1
specificity_N = mkN "特异性";-- 1
sorrow_N = mkN "悲哀"; -- 1
sob_V = mkV "哭泣"; -- 1
snarl_N = mkN "搞乱"; -- 1
slovenian_A = mkA "斯洛文尼亚"; -- 1
slave_N = mkN "奴隶"; -- 1
singing_N = mkN "歌唱"; -- 1
sibling_N = mkN "兄弟"; -- 1
shore_up_V2 = mkV2 "支撑"; -- 1
shear_V2 = mkV2 "剪断"; -- 1
serpent_N = mkN "蛇"; -- 1
self_destruct_V = mkV "自毁"; -- 1
seaport_N = mkN "海港"; -- 1
scornful_A = mkA "蔑视";-- 1
scamper_V = mkV "疾走"; -- 1
san_marinese_N = mkN "圣马力诺人"; -- 1
safe_N = mkN "安全"; -- 1
rubbish_N = mkN "垃圾"; -- 1
romance_V2 = mkV2 "虚构"; -- 1
riff_N = mkN "即兴"; -- 1
retrench_V = mkV "删减"; -- 1
restless_A = mkA "不安"; -- 1
reproduce_V = mkV "复制"; -- 1
rendezvous_N = mkN "会合"; -- 1
reinterpretation_N = mkN "重新诠释";-- 1
reflective_A = mkA "反射"; -- 1
record_breaking_A = mkA "破记录"; -- 1
reappoint_V2 = mkV2 "续聘"; -- 1
ravage_V = mkV "蹂躏"; -- 1
ramp_V2 = mkV2 "蔓延"; -- 1
quotient_N = mkN "商";  -- 1
qualm_N = mkN "疑虑"; -- 1
pulverize_V2 = mkV2 "粉碎"; -- 1
protestant_A = mkA "抗议"; -- 1
progress_V2 = mkV2 "进步"; -- 1
pretension_N = mkN "预紧"; -- 1
precocious_A = mkA "早熟"; -- 1
pouch_N = mkN "袋"; -- 1
pop_V2 = mkV2 "弹出"; -- 1
plume_N = mkN "羽"; -- 1
plan_V2V = mkV2V "计划"; -- 1
pillowcase_N = mkN "枕套"; -- 1
petition_V = mkV "请愿"; -- 1
perfume_V2 = mkV2 "散发香气"; -- 1
peek_N = mkN "窥视"; -- 1
patrol_V = mkV "巡逻"; -- 1
parliamentarian_N = mkN "国会议员"; -- 1
panic_V2 = mkV2 "恐慌"; -- 1
paddle_N = mkN "桨"; -- 1
overplant_V2 = mkV2 "过度灌溉"; -- 1
outleap_V2 = mkV2 "向前跳";--  1
opulence_N = mkN "富裕"; -- 1
officious_A = mkA "非官方";-- 1
oblige_V2V = mkV2V "迫使"; -- 1
noteworthy_A = mkA "显著"; -- 1
nightly_Adv = mkAdv "每夜"; -- 1
naysay_V2 = mkV2 "否认";-- 1
musicianship_N = mkN "音乐修养";-- 1
motorcade_N = mkN "车队"; -- 1
mold_V = mkV "塑造" ; -- 1
mistake_V2 = mkV2 "弄错"; -- 1
mill_V = mkV "碾磨"; -- 1
metabolize_V2 = mkV2 "代谢"; -- 1
melodious_A = mkA "悠扬"; -- 1
mass_produce_V2 = mkV2 "批量生产"; -- 1
maniac_N = mkN "疯子"; -- 1
maharajah_N = mkN "大君"; -- 1
lumber_V = mkV "伐木"; -- 1
longevity_N = mkN "长寿"; -- 1
lit_V2 = mkV2 "点燃"; -- 1
licence_N = mkN "许可证";-- 1
leapfrog_V2 = mkV2 "蛙跳"; -- 1
lascivious_A = mkA "淫荡"; -- 1
kowtow_V = mkV "磕头"; -- 1
kindle_V2 = mkV2 "点燃"; -- 1
junction_N = mkN "连接点";-- 1
jet_off_V = mkV "前往"; -- 1
irrepressible_A = mkA "挡不住";-- 1
intoxication_N = mkN "醉"; -- 1
intellect_N = mkN "智力"; -- 1
innumerable_A = mkA "无数"; -- 1
infest_V2 = mkV2 "侵扰"; -- 1
indulge_V2 = mkV2 "放纵"; -- 1
incompetency_N = mkN "不称职";-- 1
impugn_V2 = mkV2 "抨击"; -- 1
impairment_N = mkN "减值"; -- 1
ignominious_A = mkA "可耻"; -- 1
hush_hush_A = mkA "机密" ; -- 1
howl_N = mkN "嗥叫"; -- 1
honduran_N = mkN "洪都拉斯";-- 1
hinterland_N = mkN "腹地"; -- 1
hereafter_Adv = mkAdv "此后"; -- 1
headrest_N = mkN "头枕"; -- 1
hardbound_A = mkA "精装"; -- 1
halo_N = mkN "晕"; -- 1
gullible_A = mkA "轻信"; -- 1
grievous_A = mkA "惨重"; -- 1
gouty_A = mkA "痛风"; -- 1
glitter_N = mkN "闪光"; -- 1
gibberish_N = mkN "胡言乱语";-- 1
geneticist_N = mkN "遗传学家";-- 1
futility_N = mkN "无用"; -- 1
froth_N = mkN "泡沫"; -- 1
freakish_A = mkA "滑稽可笑"; -- 1
forward_V2 = mkV2 "促进"; -- 1
foot_V = mkV "步行"; -- 1
flout_V2 = mkV2 "藐视"; -- 1
flattery_N = mkN "奉承"; -- 1
finder_N = mkN "发现者";-- 1
fertilization_N = mkN "施肥"; -- 1
fascist_N = mkN "法西斯";-- 1
facade_N = mkN "正面"; -- 1
explosive_N = mkN "爆炸物";-- 1
exemplary_A = mkA "典范"; -- 1
estrange_V2 = mkV2 "疏远"; -- 1
epidemiologist_N = mkN "流行病学";-- 1
engagement_N = mkN "订婚"; -- 1
embattled_A = mkA "心烦意乱";-- 1
eeriness_N = mkN "怪诞"; -- 1
dutch_N = mkN "荷兰人";-- 1
drift_apart_V = mkV "疏远"; -- 1
double_breasted_A = mkA "双排"; -- 1
ditto_N = mkN "同上"; -- 1
dispatch_N = mkN "派遣"; -- 1
discontinuance_N = mkN "废止"; -- 1
diphtheria_N = mkN "白喉"; -- 1
devious_A = mkA "歪" ; -- 1
derby_N = mkN "德比"; -- 1
demagogue_N = mkN "煽动者";-- 1
defensiveness_N = mkN "防卫"; -- 1
deadlock_N = mkN "僵局"; -- 1
dab_V2 = mkV2 "轻拍"; -- 1
cube_N = mkN "立方体";-- 1
cringe_V = mkV "奉承";-- 1
crass_A = mkA "愚钝";-- 1
coupling_N = mkN "耦合"; -- 1
cornucopia_N = mkN "聚宝盆";-- 1
contraption_N = mkN "玩意儿";-- 1
connote_V2 = mkV2 "意味着";-- 1
compute_V2 = mkV2 "计算"; -- 1
comical_A = mkA "滑稽"; -- 1
cohesion_N = mkN "凝聚"; -- 1
clutch_V2 = mkV2 "抓住";-- 1
classless_A = mkA "无阶级"; -- 1
cinematic_A = mkA "影片"; -- 1
chime_V = mkV "鸣响"; -- 1
charisma_N = mkN "人格魅力";-- 1
catholic_N = mkN "天主教徒";-- 1
carillon_N = mkN "钟琴"; -- 1
cane_N = mkN "甘蔗"; -- 1
bygone_A = mkA "过去";-- 1
burble_VS = mkVS "窃笑"; -- 1
brunch_N = mkN "早午餐";-- 1
bride_N = mkN "新娘"; -- 1
bound_N = mkN "边界" ; -- 1
boil_N = mkN "煮"; -- 1
bleed_VS = mkVS "流血"; -- 1
bin_N = mkN "箱子"; -- 1
better_N = mkN "长辈"; -- 1
beet_N = mkN "甜菜"; -- 1
bassoon_N = mkN "巴松管";-- 1
bang_V = mkV "重击" ; -- 1
babel_N = mkN "巴贝尔";-- 1
attest_V = mkV "证明"; -- 1
ass_N = mkN "屁股"; -- 1
armpit_N = mkN "腋窝"; -- 1
appendage_N = mkN "附加物";-- 1
anoint_V2 = mkV2 "涂油于";-- 1
amp_N = mkN "放大器";-- 1
almanac_N = mkN "历书"; -- 1
aftershock_N = mkN "余震"; -- 1
adjoin_V = mkV "毗临" ; -- 1
account_V2 = mkV2 "报账"; -- 1
abandonment_N = mkN "放弃"; -- 1
}
