--# -path=.:prelude

concrete LexiconHin of Lexicon = CatHin ** 
--open ResHin, Prelude in {
  open ParadigmsHin, Prelude in {

  flags 
    optimize=values ;
    coding = utf8;

lin
  airplane_N = mkCmpdNoun "hava:I:" (mkN "jaha:z") ;
  answer_V2S = mkV2  (compoundV "java:b" (mkV "de:na:")) ;
  apartment_N = mkN "kamra:" ;
  apple_N = mkN "se:b" ;
--  art_N = mkN "" ;
  ask_V2Q = mkV2 (mkV "pu:c'na:") ;
  baby_N = mkN "bacX,c'a:" ;
  bad_A = mkA "bura:" ;
  bank_N = mkN "be+m.k" ;
  beautiful_A = mkA "xu:bsu:rat" ;
  become_VA = mkV "banna:";
  beer_N = mkN "biyar" ;
  beg_V2V =  mkV2V (compoundV "b'i:k'" (mkV "ma:m.gna:")) "se:" "k'" False;
  big_A = mkA "baRa:" ;
  bike_N = mkN "sa:ykal" feminine ;
  bird_N = mkN "ciRiya:" ;
  black_A =  mkA "ka:la:" ;
  blue_A = mkA "ni:la:" ;
  boat_N = mkN "na:v" ;
  book_N = mkN "kita:b" feminine ;
  boot_N = mkN "ju:ta:" ;
  boss_N = mkN "ma:lik" ;
  boy_N = mkN "laRka:" ;
  bread_N = mkN "ro:Ti:" ;
  break_V2 = mkV2 (mkV "to:Rna:") ;
  broad_A = mkA "co+Ra:" ;
  brother_N2 = mkN2 (mkN "b'a:I:") (mkPrep "ka" "ki:") "ke:" ; --not correct
  brown_A = mkA "b'u:ra:" ;
  butter_N = mkN "makX,k'an" ;
  buy_V2 = mkV2 (mkV "xari:dna:") "ko:"; -- add ko: here for es ko khredna, but this will create sentences like kitab ko kharedna
  camera_N = mkN "ke+mara:" ;
  cap_N = mkN "To:pi:" ;
  car_N = mkN "ka:r" ;
  carpet_N = mkN "qa:li:n" ;
  cat_N = mkN "billi:" feminine;
  ceiling_N = mkN "c'at" feminine ;
  chair_N = mkN "kurX,si:" ;
  cheese_N = mkN "pani:r" feminine ;
  child_N = mkN "bacX,ca:"  ;
  church_N = mkN "girija:" ;
  city_N = mkN "s*ahar" ;
  clean_A = mkA "sa:f" ;
  clever_A = mkA "ca:la:k" ;  
  close_V2 =  mkV2 (compoundV "band" do_V2); 
  coat_N = mkN "ko:T" ;
  cold_A = mkA "sarX,d" ;
  come_V = mkV "A:na:" ;
  computer_N = mkN "kam.pyu:Tar" ;
  country_N = mkN "de:s*" ;
  cousin_N = mkCmpdNoun "cca" (mkN "zad") ; -- a compund noun made of two nouns
  cow_N = mkN "ga:y" feminine ;
  die_V = mkV "marna:" ;
  dirty_A = mkA "gam.da:" ;
  distance_N3 = mkN3 (mkN "fa:sla:") (mkPrep "ka:" "ki:") "ke:" "se:"  ;
  doctor_N = mkN "Da:kTar" ;
  dog_N = mkN "kutX,ta:" ;
  door_N = mkN "darva:za:" ;
  drink_V2 = mkV2 (mkV "pi:na:");
  easy_A2V = mkA "A:sa:n" "" ; -- chek for A or a
  eat_V2 = mkV2 (mkV "k'a:na:") "" ;
  empty_A = mkA "xa:li:" ;
  enemy_N = mkN "dus*X,man" ;
  factory_N = mkN "ka:rxa:na:" ;
  father_N2 = mkN2 (mkN "ba:p") (mkPrep "ka" "ki:") "ke:"  ;
  fear_N = mkN "Dar";
  fear_VS = mkV "Darna:";
  find_V2 = mkV2 (mkV "pa:na:") ;
  fish_N = mkN "mac'li:" ;
  floor_N = mkN "fars*" ;
  forget_V2 = mkV2 (mkV "b'u:lna:")  ;
  fridge_N = mkN "frij" ;
  friend_N = mkN "do:sX,t" masculine ;
  fruit_N = mkN "p'al" ;
--  fun_AV = mkAV (regA "fun") ;
  garden_N = mkN "ba:g." ; -- chek for g.
  girl_N = mkN "laRki:" ;
  glove_N = mkN "dasta:na:" ;
  gold_N = mkN "so:na:" ;
  good_A = mkA "AcX,c'a:" ;
  go_V = mkV "ja:na:" ;
  green_A = mkA "hara:" ;
  harbour_N = mkCmpdNoun "bam.dar" (mkN "ga:h") ;
  hate_N = mkN "nafrat" ;
  hate_V2 = mkV2 (compoundV "nafrat" do_V2) ;
  hat_N = mkN "To:pi:" ;
--  have_V2 = dirV2 (mk5V "have" "has" "had" "had" "having") ;
  hear_V2 = mkV2 (mkV "sunna:") ;
  hill_N = mkN "paha:R" ;
  hope_N = mkN "Ummi:d" ;
  hope_VS = (compoundV "Ummi:d" do_V2);
  horse_N = mkN "g'o:Ra:" ;
  hot_A = mkA "garm" ;
  house_N = mkN "g'ar" ;
  important_A = mkA "zaru:ri:" ;  -- check about z
  industry_N = mkN "sant" feminine ;
  iron_N = mkN "lo:ha:" ;
  king_N = mkN "ra:ja:" ;
  know_V2 = mkV2 (mkV "ja:nna:") ;
  know_VS = mkV "ja:nna:";
  know_VQ = (mkV "ja:nna:") ;
  lake_N = mkN "j'i:l" feminine ;
  lamp_N = mkN "cira:g" ;
  learn_V2 = mkV2 (mkV "si:k'na:") ;
  leather_N = mkN "camRa:" ;
  leave_V2 = mkV2 (mkV "calna:") ;
  like_V2 = mkV2 (compoundV "pasam.d" do_V2) "ko:";
  listen_V2 = mkV2 (mkV "sunna:") ;
  live_V = mkV "rahna:" ; ---- touch
  long_A = mkA "lam.ba:" ;
  lose_V2 = mkV2 (compoundV "k'o:" do_V2) ;
  love_N = mkN "pX,ya:r" ;
  love_V2 = mkV2 (compoundV "pX,ya:r" do_V2) "ko:";
  man_N = mkN "A:dmi:" masculine;
  married_A2 = mkA (mkIrregA "s*a:di: s*uda:") "se:" ;
  marriage = mkN "s*a:di: " ;
  meat_N = mkN "ma:m.s" ;
  milk_N = mkN "du:d'" ;
  moon_N = mkN "ca:m.d" ;
  mother_N = mkN "ma:n~" feminine;   -- not covered need to be discussed
  mountain_N = mkN "paha:R" ;
  music_N = mkN "sam.gi:t" ;
  narrow_A = mkA "tam.g" ;
  new_A = mkA "naya:" ;
  newspaper_N = mkN "Axba:r" ;
  oil_N = mkN "te:l" ;
  old_A = mkA "bu:R'a:" ;
  open_V2 = mkV2 (mkV "k'o:lna:") ;
  paint_V2A = mkV2 (compoundV "ram.g" do_V2) ;
  paper_N = mkN "ka:g.az" ;
  paris_PN = mkPN "pe+ris" ;
  peace_N = mkN "Aman" ;
  pen_N = mkN "qalam" ;
  planet_N = mkN "sita:ra:" ;
  plastic_N = mkN "pla:sTik" ;
  play_V2 = mkV2 (mkV "k'e:lna:") ;
  policeman_N = mkCmpdNoun "pulis" (mkN "wa:la:") ; 
  priest_N = mkN "puja:ri:" ;
--  probable_AS = mkAS (regA "probable") ;
  queen_N = mkN "ra:ni:" ;
  radio_N = mkN "re:Dio:" ;
  rain_N = mkN "ba:ris*" ;
  rain_V0 = compoundV "ba:ris*" (mkV "ho:na:" ) ;
  read_V2 = mkV2 (mkV "paR'na:");
  red_A = mkA "la:l" ;
  religion_N = mkN "mazhab" ;
  restaurant_N = mkN "re:sto:ra:m." ;
--  river_N = mkN "dariya:" masculine ;
  rock_N = mkN "caTTa:n" ;
  roof_N = mkN "c'at" masculine ;
  rubber_N = mkN "rabar" ;
  run_V = mkV "do+Rna:" ;
  say_VS = mkV "kahna:" ;
  school_N = mkN "sku:l" ;
  science_N = mkN "vijX,n*a:n" ; -- vgyan
  sea_N = mkN "samam.dar" ;
  seek_V2 = mkV2 (compoundV "tala:s*" do_V2) ;
  see_V2 = mkV2 (mkV "de:k'na:") ;
  sell_V3 = mkV3 (mkV "be:cna:") "ko:" "";
  send_V3 = mkV3 (mkV "b'e:jna:") "ko:" "";
  sheep_N = mkN "b'i:R" feminine ;
  ship_N = mkN "jaha:z" ;
  shirt_N = mkN "kurX,ta:" feminine;
  shoe_N = mkN "ju:ta:" ;
  shop_N = mkN "du:ka:n" feminine ;
  short_A = mkA "c'o:Ta:" ;
  silver_N = mkN "ca:m.di:" ;
  sister_N = mkN "bahan" feminine ;
  sleep_V = mkV "so:na:" ;
  small_A = mkA "c'o:Ta:" ;
  snake_N = mkN "sa:m.p" ;
  sock_N = mkN "jurra:b" feminine ;
  speak_V2 = mkV2 (mkV "bo:lna:") ;
  star_N = mkN "ta:ra:" ;
  steel_N = mkN "Ispa:t" ; -- something like ispat
  stone_N = mkN "patX,t'ar" ;
  stove_N = mkN "cu:lX,ha:" ;
--  student_N = mkCmpdNoun "t-alb" (mkN "elm") ; -- something vidrati
  stupid_A = mkA "be:vaqu:f" ;
  sun_N = mkN "su:raj" ; -- swrya
  switch8off_V2 =  mkV2 (compoundV "bam.d" do_V2) ;
  switch8on_V2 = mkV2 (mkV "cala:na:") ;
  table_N = mkN "me:z" feminine ;
  talk_V3 = mkV3 (mkV "bo:lna:") "se:" "ke: ba:re: me:";
  teacher_N = mkN "UsX,ta:d" ; -- adyapak
  teach_V2 = mkV2 (mkV "sik'a:na:") ;
  television_N = mkN "Ti:vi:" ;
  thick_A = mkA "mo:Ta:" ;
  thin_A = mkA "patla:" ;
  train_N = mkN "re:l ga:Ri:" ;
  travel_V = (compoundV "safar" do_V2) ;
--  tree_N = mkN "pe:R" masculine ;
  trousers_N = mkN "patlu:n" ;
  ugly_A = mkA "badsu:rat" ;
  understand_V2 = mkV2 (mkV "samaj'na:") ;
  university_N = mkN "vis*X,v vidX,ya:lay" ;
  village_N = mkN "ga:n~v" ; -- check for n or N
  wait_V2 = mkV2 (compoundV "Im.taza:r" do_V2) "ka:" ; -- something prtkXa
  walk_V = mkV "calna:" ;
  warm_A = mkA "garm" ; something gngna
  war_N = mkN "laRa:I:" ;
  watch_V2 = mkV2 (mkV "de:k'na:") ;
  water_N = mkN "pa:ni:" masculine ; -- not covered masculine ending with y
  white_A = mkA "safe:d" ;
  window_N = mkN "k'iRki:" ;
  wine_N = mkN "s*ara:b" feminine ;
  win_V2 = mkV2 (mkV "ji:tna:") ;
  woman_N = mkN "O+rat" feminine ;
  wonder_VQ = compoundV "he+ra:n" (mkV "ho:na:") ;
  wood_N = mkN "lakRi:" ;
  write_V2 = mkV2 (mkV "lik'na:") ;
  yellow_A = mkA "pi:la:" ;
  young_A = mkA "java:n" ;
  do_V2 = mkV2 (mkV "karna:")  ;
  now_Adv = mkAdv "Ab" ;
  already_Adv = mkAdv "pahle: hi:" ;
  song_N = mkN "gi:t" ;
  add_V3 = mkV3 (mkV "jo:Rna:") "ko:" "me:m."; -- confirm
  number_N = mkN "hndsh" ;
  put_V2 = mkV2 (mkV "Da:lna:") ;
  stop_V = mkV "rukna:"  ;
  jump_V = compoundV "c'ala:m.g" (mkV "laga:na:") ;

  left_Ord = {s = "ba:ya:n~" ; n = singular};
  right_Ord = {s= "da:ya:n~" ; n = singular};
  far_Adv = mkAdv "du:r" ;
  correct_A = mkA "sahi:h" ;
  dry_A = mkA "su:k'a:" ;
  dull_A = mkA "nalik" ;
  full_A = mkA "b'ara:" ;
  heavy_A = mkA "b'a:ri:" ;
  near_A = mkA "nazdi:k" ;
  rotten_A = mkA "saRa:" ;
  round_A = mkA "go:l" ;
  sharp_A = mkA "te:z" ;
  smooth_A = mkA "cikna:" ;
  straight_A = mkA "si:d'a:" ;
  wet_A = mkA "gi:la:" ; ----
  wide_A = mkA "co+Ra:" ;
  animal_N = mkN "ja:nvar" ;
  ashes_N = mkN "ra:k'" feminine; -- FIXME: plural only?
  back_N = mkN "pi:T'" feminine ;
--  bark_N = mkN "bark" ;
--  belly_N = mkN "dh-ny" ;
  blood_N = mkN "xu:n" ;
  bone_N = mkN "haDX,Di:" feminine ;
  breast_N = mkN "c'a:ti:" ; --stan
  cloud_N = mkN "ba:dal" ;
  day_N = mkN "din" ;
  dust_N = mkN "d'u:l" ;
  ear_N = mkN "ka:n" ;
  earth_N = mkN "zami:n" feminine ;
  egg_N = mkN "Am.Da:" ;
  eye_N = mkN "A:m.k'" feminine ;
  fat_N = mkN "mo:Ta:" ;
  feather_N = mkN "pam.k'" ;
  fingernail_N = mkN "na:k'u:n" ;
  fire_N = mkN "A:g" feminine ;
  flower_N = mkN "p'u:l" ;
  fog_N = mkN "d'um.d'" feminine ;
  foot_N = mkN "pa:m.v" ; -- not properly covered need to be discussed
  forest_N = mkN "jam.gal" ;
  grass_N = mkN "g'a:s" feminine ;
--  guts_N = mkN "gut" ; -- FIXME: no singular
  hair_N = mkN "ba:l" ;
  hand_N = mkN "ha:t'" ;
  head_N = mkN "sir" ;
  heart_N = mkN "dil" ;
  horn_N = mkN "si:m.g" ;
  husband_N = mkN "pati" ;
  ice_N = mkN "barX,f" feminine ;
  knee_N = mkN "g'uTna:" ;
  leaf_N = mkN "patta:" ;
  leg_N = mkN "Ta:m.g" feminine ;
  liver_N = mkN "kale:ja:" ;
  louse_N = mkN "ju:" ;
  mouth_N = mkN "muh" ; 
  name_N = mkN "na:m" ;
  neck_N = mkN "garX,dan" feminine ;
  night_N = mkN "ra:t" feminine ;
  nose_N = mkN "na:k" ;
--  person_N = mkN "vX,yakX,ti" ;
  road_N = mkN "saRak" ;
  root_N = mkN "jaR" feminine ;
  rope_N = mkN "rasX,si:" ;
  salt_N = mkN "namak" feminine ;
  sand_N = mkN "re:t" feminine ;
  seed_N = mkN "bi:j"  ;
  skin_N = mkN "jld" feminine ; -- crm
  sky_N = mkN "A:sma:n" ;
  smoke_N = mkN "d'ua:n~"; -- singular masc nouns ending with aN,wN yet to be implemented
  snow_N = mkN "barX,f" feminine ;
  stick_N = mkN "lakRi:" ;
  tail_N = mkN "dum" ;
  tongue_N = mkN "zaba:n" feminine ;
  tooth_N = mkN "da:m.t" masculine;
  wife_N = mkN "bi:vi:" ;
  wind_N = mkN "hava:" ;
--  wing_N = mkN "pr" ;
  worm_N = mkN "ki:Ra" ;
  year_N = mkN "sa:l" ;
--  blow_V = mkV "clna" ;
  breathe_V = compoundV "sa:n~s" (mkV "le:na:" ) ;
  burn_V = mkV "jala:na:" ;
  dig_V = mkV "k'o:dna:" ;
  fall_V = mkV "girna:" ;
  float_V = mkV "te+rna:" ;
  flow_V = mkV  "bahna:" ;
  fly_V = mkV "uRna:" ;
--  freeze_V = mkV "jmna";
  give_V3 = mkV3 (mkV "de:na:") "ko:" "";
  laugh_V = mkV "ham.sna:" ;
  lie_N = mkN "j'u:T" masculine ;
  lie_V = compoundV "j'u:T" (mkV "bo:lna:" );
  play_V = mkV "k'e:lna:" ;
  sew_V = mkV "si:na:" ;
  sing_V = mkV "ga:na:" ;
  sit_V = mkV "be+T'na:" ;
  smell_V = mkV "su:m.gna:" ;
  spit_V = mkV "t'u:kna:" ;
  stand_V = compoundV "k'aRa:" (mkV "ho:na:" ); -- a type of compound verb made of two verbs i.e 'kHRa' also inflects, rather than a string and verb should be fixed
  swell_V = mkV "su:jna:" ;
  swim_V = mkV "te+rna:" ;
  think_V = mkV "so:cna:" ;
  turn_V = mkV "muRna:";
--  vomit_V = compoundV "Aly" (mkV "krna") feminine ;
  bite_V2 = mkV2 (mkV "ka:Tana:") ;
  count_V2 = mkV2 (mkV "ginna:") ;
  cut_V2 = mkV2 (mkV "ka:Tna:") ;
  fear_V2 = mkV2 (mkV "Darna:") ;
  fight_V2 = mkV2 (mkV "laRna:") ;
--  hit_V2 = mkV2 (compoundV "th-wkr" (mkV "marna" ));
  hold_V2 = mkV2 (mkV "pakaRna:") ;
--  hunt_V2 = mkV2 (compoundV "Xkar" do_V2);
  kill_V2 =  mkV2 (compoundV "ma:r" (mkV "Da:lna:" )) ;
  pull_V2 = mkV2 (mkV "k'i:m.cna:");
  push_V2 = mkV2 (mkV "d'ake:lna:") "ko:" ;
  rub_V2 = mkV2 (mkV "ragaRna:") ;
  scratch_V2 = mkV2 (mkV "k'aro:m.cna:") "ko:" ;
--  split_V2 = mkV2 (mkV "banta") "ko::" ;
--  squeeze_V2 = dirV2 (regV "squeeze") ;
--  stab_V2 = dirV2 (regDuplV "stab") ;
  suck_V2 = mkV2 (mkV "cu:sna:") ;
  throw_V2 = mkV2 (mkV "p'e:m.kna:") ;
  tie_V2 = mkV2 (mkV "ba:m.d'na:") ;
  wash_V2 = mkV2 (mkV "d'o:na:") ;
--  wash_V2 = mkV2 (mkV "po:m.c'ana:") ;

----  other_A = regA "other" ;

--  grammar_N = mkN "grdan" ;
--  language_N = mkN "zban" feminine ;
--  rule_N = mkN "ASwl" ;

---- added 4/6/2007
    john_PN = mkPN "ja:n" ;
    question_N = mkN "sava:l" ;
    ready_A = mkA "te+ya:r" ;
    reason_N = mkN "vajah" feminine ;
    today_Adv = mkAdv "A:j" ;
    uncertain_A = mkA ["g.yr yqyny"] ;
    
  
}
