--# -path=.:../romance:../common:../abstract:../../prelude

-- Irregular verbs from Nancy, based on a list from Sylvain Pogodalla, 25/11/2004
-- Translated to GF by Aarne Ranta
-- added extracted subcat information 29/11

concrete VerbsFre of VerbsFreAbs = CatFre ** 
  open DiffFre, MorphoFre, BeschFre, Prelude in {

  flags optimize=values ;

-- all verbs in classes with "er" and "finir" are omitted

lin 
  abattre_V2 = v_besch55 "abattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  absoudre_V2 = v_besch72 "absoudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  abstenir_V = v_besch23 "abstenir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  abstraire_V2 = v_besch61 "abstraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  accourir_V = v_besch33 "accourir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  accroître_V2 = v_besch73 "accroître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  accueillir_V2 = v_besch28 "accueillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  acquérir_V2 = v_besch24 "acquérir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  adjoindre_V2 = v_besch58 "adjoindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  admettre_V2 = v_besch56 "admettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  advenir_V = v_besch23 "advenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  aller_V = v_besch22 "aller" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  apercevoir_V2 = v_besch38 "apercevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  apparaître_V = v_besch64 "apparaître" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  appartenir_V2 = v_besch23 "appartenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  appendre_V2 = v_besch53 "appendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  apprendre_V2 = v_besch54 "apprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  assaillir_V2 = v_besch29 "assaillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  asseoir_V2 = v_besch49 "asseoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  astreindre_V2 = v_besch57 "astreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  atteindre_V2 = v_besch57 "atteindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  attendre_V2 = v_besch53 "attendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  avoir_V2 = v_besch1 "avoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  battre_V2 = v_besch55 "battre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  boire_V2 = v_besch69 "boire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  bouillir_V2 = v_besch31 "bouillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  braire_V = v_besch61 "braire" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  ceindre_V2 = v_besch57 "ceindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  choir_V = v_besch52 "choir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  circonscrire_V2 = v_besch80 "circonscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  circonvenir_V2 = v_besch23 "circonvenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  clore_V2 = v_besch70 "clore" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  combattre_V2 = v_besch55 "combattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  commettre_V2 = v_besch56 "commettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  comparaître_V2 = v_besch64 "comparaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  complaire_V2 = v_besch63 "complaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  comprendre_V2 = v_besch54 "comprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  compromettre_V2 = v_besch56 "compromettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  concevoir_V2 = v_besch38 "concevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  conclure_V2 = v_besch71 "conclure" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  concourir_V2 = v_besch33 "concourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  condescendre_V2 = v_besch53 "condescendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  conduire_V2 = v_besch82 "conduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  confire_V2 = v_besch81 "confire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  confondre_V2 = v_besch53 "confondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  conjoindre_V2 = v_besch58 "conjoindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  connaître_V2 = v_besch64 "connaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  conquérir_V2 = v_besch24 "conquérir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  consentir_V2 = v_besch25 "consentir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  construire_V2 = v_besch82 "construire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contenir_V2 = v_besch23 "contenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contraindre_V2 = v_besch59 "contraindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contrebattre_V2 = v_besch55 "contrebattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contredire_V2 = v_besch78 "contredire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contrefaire_V2 = v_besch62 "contrefaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  contrevenir_V2 = v_besch23 "contrevenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  convaincre_V2 = v_besch60 "convaincre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  convenir_V2 = v_besch23 "convenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  correspondre_V2 = v_besch53 "correspondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  corrompre_V2 = v_besch53 "corrompre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  coudre_V2 = v_besch73 "coudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  courir_V2 = v_besch33 "courir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  couvrir_V2 = v_besch27 "couvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  craindre_V2 = v_besch59 "craindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  croire_V2 = v_besch68 "croire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  croître_V = v_besch67 "croître" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  cueillir_V2 = v_besch28 "cueillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  cuire_V2 = v_besch82 "cuire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  débattre_V2 = v_besch55 "débattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  débouillir_V2 = v_besch31 "débouillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  décevoir_V2 = v_besch38 "décevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déchoir_V2 = v_besch52 "déchoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déclore_V2 = v_besch70 "déclore" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  décommettre_V2 = v_besch56 "décommettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déconfire_V2 = v_besch81 "déconfire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  découdre_V2 = v_besch73 "découdre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  découvrir_V2 = v_besch27 "découvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  décrire_V2 = v_besch80 "décrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  décroître_V2 = v_besch67 "décroître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  décuire_V2 = v_besch82 "décuire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déduire_V2 = v_besch82 "déduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  défaillir_V = v_besch30 "défaillir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  défaire_V2 = v_besch62 "défaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  défendre_V2 = v_besch53 "défendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  démentir_V2 = v_besch25 "démentir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  démettre_V2 = v_besch56 "démettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  démordre_V = v_besch53 "démordre" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  départir_V2 = v_besch25 "départir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  dépeindre_V2 = v_besch57 "dépeindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  dépendre_V2 = v_besch53 "dépendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  déplaire_V = v_besch63 "déplaire" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  dépourvoir_V2 = v_besch40 "dépourvoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déprendre_V2 = v_besch54 "déprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  désapprendre_V2 = v_besch54 "désapprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  descendre_V2 = v_besch53 "descendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  desservir_V2 = v_besch35 "desservir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  déteindre_V2 = v_besch57 "déteindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  détendre_V2 = v_besch53 "détendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  détenir_V2 = v_besch23 "détenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  détordre_V2 = v_besch53 "détordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  détruire_V2 = v_besch82 "détruire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  devenir_V = v_besch23 "devenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  dévêtir_V2 = v_besch26 "dévêtir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  devoir_V2 = v_besch42 "devoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  dire_V2 = v_besch78 "dire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  disconvenir_V2 = v_besch23 "disconvenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  discourir_V2 = v_besch33 "discourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  disjoindre_V2 = v_besch58 "disjoindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  disparaître_V2 = v_besch64 "disparaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  dissoudre_V2 = v_besch72 "dissoudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  distendre_V2 = v_besch53 "distendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  distordre_V2 = v_besch53 "distordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  distraire_V2 = v_besch61 "distraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  dormir_V2 = v_besch32 "dormir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  ébattre_V = v_besch55 "ébattre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  échoir_V2 = v_besch52 "échoir" ** {isRefl = False ; aux = VEsse ; lock_V2 = <> ; c2 = complDat} ;
  éclore_V2 = v_besch70 "éclore" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  éconduire_V2 = v_besch82 "éconduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  écrire_V2 = v_besch80 "écrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  élire_V2 = v_besch77 "élire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  embatre_V2 = v_besch55 "embatre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  embattre_V2 = v_besch55 "embattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  emboire_V = v_besch69 "emboire" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  émettre_V2 = v_besch56 "émettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  émoudre_V2 = v_besch74 "émoudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  émouvoir_V2 = v_besch44 "émouvoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  empreindre_V2 = v_besch57 "empreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  enceindre_V2 = v_besch57 "enceindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  enclore_V2 = v_besch70 "enclore" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  encourir_V2 = v_besch33 "encourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  endormir_V2 = v_besch32 "endormir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  enduire_V2 = v_besch82 "enduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  enfreindre_V2 = v_besch57 "enfreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  enfuir_V = v_besch36 "enfuir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  enjoindre_V2 = v_besch58 "enjoindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  enquérir_V = v_besch24 "enquérir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entendre_V2 = v_besch53 "entendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  entr'apercevoir_V = v_besch38 "entr'apercevoir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entrebattre_V = v_besch55 "entrebattre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entre_détruire_V = v_besch82 "entre-détruire" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entre_haïr_V = v_besch20 "entre-haïr" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entremettre_V = v_besch56 "entremettre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  entre_nuire_V = v_besch82 "entre-nuire" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  entreprendre_V2 = v_besch54 "entreprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  entretenir_V2 = v_besch23 "entretenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  entrevoir_V2 = v_besch39 "entrevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  entrouvrir_V2 = v_besch27 "entrouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  envoyer_V2 = v_besch18 "envoyer" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  épandre_V2 = v_besch53 "épandre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  éperdre_V = v_besch53 "éperdre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  éprendre_V = v_besch54 "éprendre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  équivaloir_V2 = v_besch47 "équivaloir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  éteindre_V2 = v_besch57 "éteindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  étendre_V2 = v_besch53 "étendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  étreindre_V2 = v_besch57 "étreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  être_V = v_besch2 "être" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  exclure_V2 = v_besch71 "exclure" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  extraire_V2 = v_besch61 "extraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  faillir_V2 = v_besch30 "faillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  faire_V2 = v_besch62 "faire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  falloir_V = v_besch46 "falloir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  feindre_V2 = v_besch57 "feindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  fendre_V2 = v_besch53 "fendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  fondre_V2 = v_besch53 "fondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  forfaire_V2 = v_besch62 "forfaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  foutre_V2 = v_besch53 "foutre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  frire_V2 = v_besch81 "frire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  fuir_V2 = v_besch36 "fuir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  geindre_V2 = v_besch57 "geindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  gésir_V2 = mkNV (conj3gésir "gésir") ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  haïr_V2 = v_besch20 "haïr" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  inclure_V2 = v_besch71 "inclure" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  induire_V2 = v_besch82 "induire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  inscrire_V2 = v_besch80 "inscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  instruire_V2 = v_besch82 "instruire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  interdire_V2 = v_besch78 "interdire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  interrompre_V2 = v_besch53 "interrompre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  intervenir_V = v_besch23 "intervenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  introduire_V2 = v_besch82 "introduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  joindre_V2 = v_besch58 "joindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  lire_V2 = v_besch77 "lire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  luire_V = v_besch82 "luire" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  mainmettre_V2 = v_besch56 "mainmettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  maintenir_V2 = v_besch23 "maintenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  méconnaître_V2 = v_besch64 "méconnaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  mécroire_V2 = v_besch68 "mécroire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  médire_V2 = v_besch78 "médire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  mentir_V2 = v_besch25 "mentir" ** {isRefl = False ; aux = VEsse ; lock_V2 = <> ; c2 = complDat} ;
  méprendre_V2 = v_besch54 "méprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  messeoir_V2 = v_besch50 "messeoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  mettre_V2 = v_besch56 "mettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  mévendre_V2 = v_besch53 "mévendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  mordre_V2 = v_besch53 "mordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  morfondre_V = v_besch53 "morfondre" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  moudre_V2 = v_besch74 "moudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  mourir_V = v_besch34 "mourir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  mouvoir_V2 = v_besch44 "mouvoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  naître_V = v_besch65 "naître" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  nuire_V2 = v_besch82 "nuire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  obtenir_V2 = v_besch23 "obtenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  obvenir_V = v_besch23 "obvenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  occlure_V2 = v_besch71 "occlure" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  offrir_V2 = v_besch27 "offrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  oindre_V2 = v_besch58 "oindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  omettre_V2 = v_besch56 "omettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  ouïr_V2 = v_besch37 "ouïr" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  ouvrir_V2 = v_besch27 "ouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  paître_V2 = v_besch66 "paître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  paître_V = v_besch66 "paître" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  paraître_V = v_besch64 "paraître" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  parcourir_V2 = v_besch33 "parcourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  parfondre_V2 = v_besch53 "parfondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  partir_V = v_besch25 "partir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  parvenir_V = v_besch23 "parvenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  peindre_V2 = v_besch57 "peindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  pendre_V2 = v_besch53 "pendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  percevoir_V2 = v_besch38 "percevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  perdre_V2 = v_besch53 "perdre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  permettre_V2 = v_besch56 "permettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  plaindre_V2 = v_besch59 "plaindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  plaire_V2 = v_besch63 "plaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  pleuvoir_V = v_besch45 "pleuvoir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  poindre_V2 = v_besch58 "poindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  pondre_V2 = v_besch53 "pondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  pourfendre_V2 = v_besch53 "pourfendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  poursuivre_V2 = v_besch75 "poursuivre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  pourvoir_V2 = v_besch40 "pourvoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  pouvoir_V = v_besch43 "pouvoir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  prédire_V2 = v_besch78 "prédire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  prendre_V2 = v_besch54 "prendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  prescrire_V2 = v_besch80 "prescrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  pressentir_V2 = v_besch25 "pressentir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  prétendre_V2 = v_besch53 "prétendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  prévaloir_V2 = v_besch47 "prévaloir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  prévenir_V2 = v_besch23 "prévenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  prévoir_V2 = v_besch39 "prévoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  produire_V2 = v_besch82 "produire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  promettre_V2 = v_besch56 "promettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  promouvoir_V2 = v_besch44 "promouvoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  proscrire_V2 = v_besch80 "proscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  provenir_V = v_besch23 "provenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  rabattre_V2 = v_besch55 "rabattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  raire_V2 = v_besch61 "raire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rapprendre_V2 = v_besch54 "rapprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rasseoir_V2 = v_besch49 "rasseoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réadmettre_V2 = v_besch56 "réadmettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réapparaître_V = v_besch64 "réapparaître" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  réapprendre_V2 = v_besch54 "réapprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rebattre_V2 = v_besch55 "rebattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recevoir_V2 = v_besch38 "recevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recomparaître_V2 = v_besch64 "recomparaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reconduire_V2 = v_besch82 "reconduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reconnaître_V2 = v_besch64 "reconnaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reconquérir_V2 = v_besch24 "reconquérir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reconstruire_V2 = v_besch82 "reconstruire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recoudre_V2 = v_besch73 "recoudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recourir_V2 = v_besch33 "recourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  recouvrir_V2 = v_besch27 "recouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  récrire_V2 = v_besch80 "récrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recroître_V2 = v_besch67 "recroître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recueillir_V2 = v_besch28 "recueillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  recuire_V2 = v_besch82 "recuire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  redécouvrir_V2 = v_besch27 "redécouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  redéfaire_V2 = v_besch62 "redéfaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  redescendre_V2 = v_besch53 "redescendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  redevenir_V = v_besch23 "redevenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  redevoir_V2 = v_besch42 "redevoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  redire_V2 = v_besch78 "redire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réduire_V2 = v_besch82 "réduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  réécrire_V2 = v_besch80 "réécrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réélire_V2 = v_besch77 "réélire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réentendre_V2 = v_besch53 "réentendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  refaire_V2 = v_besch62 "refaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  refendre_V2 = v_besch53 "refendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  refondre_V2 = v_besch53 "refondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réinscrire_V2 = v_besch80 "réinscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  réintroduire_V2 = v_besch82 "réintroduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rejoindre_V2 = v_besch58 "rejoindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  relire_V2 = v_besch77 "relire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reluire_V2 = v_besch82 "reluire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  remettre_V2 = v_besch56 "remettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  remordre_V2 = v_besch53 "remordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  remoudre_V2 = v_besch74 "remoudre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  renaître_V2 = v_besch65 "renaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rendormir_V2 = v_besch32 "rendormir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rendre_V2 = v_besch53 "rendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rentraire_V2 = v_besch61 "rentraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rentrouvrir_V2 = v_besch27 "rentrouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  renvoyer_V2 = v_besch18 "renvoyer" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  repaître_V2 = v_besch66 "repaître" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  répandre_V2 = v_besch53 "répandre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reparaître_V = v_besch64 "reparaître" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  repartir_V = v_besch25 "repartir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  repeindre_V2 = v_besch57 "repeindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rependre_V2 = v_besch53 "rependre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  repentir_V = v_besch25 "repentir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  reperdre_V2 = v_besch53 "reperdre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  repleuvoir_V = v_besch45 "repleuvoir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  répondre_V2 = v_besch53 "répondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reprendre_V2 = v_besch54 "reprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reproduire_V2 = v_besch82 "reproduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  requérir_V2 = v_besch24 "requérir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  résoudre_V2 =  mkNV (conj3résoudre "résoudre") ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  ressentir_V2 = v_besch25 "ressentir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  resservir_V2 = v_besch35 "resservir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  ressortir_V = v_besch25 "ressortir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  ressouvenir_V = v_besch23 "ressouvenir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  restreindre_V2 = v_besch57 "restreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  reteindre_V2 = v_besch57 "reteindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retendre_V2 = v_besch53 "retendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retenir_V2 = v_besch23 "retenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retondre_V2 = v_besch53 "retondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retordre_V2 = v_besch53 "retordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retraduire_V2 = v_besch82 "retraduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retraire_V2 = v_besch61 "retraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retranscrire_V2 = v_besch80 "retranscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  retransmettre_V2 = v_besch56 "retransmettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rétreindre_V2 = v_besch57 "rétreindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revaloir_V2 = v_besch47 "revaloir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revendre_V2 = v_besch53 "revendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revenir_V = v_besch23 "revenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  revêtir_V2 = v_besch26 "revêtir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revivre_V2 = v_besch76 "revivre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revoir_V2 = v_besch39 "revoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  revouloir_V2 = v_besch48 "revouloir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rire_V2 = v_besch79 "rire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;
  rompre_V2 = v_besch53 "rompre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  rouvrir_V2 = v_besch27 "rouvrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  saillir_V2 = v_besch29 "saillir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  satisfaire_V2 = v_besch62 "satisfaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  savoir_V2 = v_besch41 "savoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  secourir_V2 = v_besch33 "secourir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  séduire_V2 = v_besch82 "séduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  sentir_V2 = v_besch25 "sentir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  seoir_V = v_besch50 "seoir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  servir_V2 = v_besch35 "servir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  sortir_V = v_besch25 "sortir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  soubattre_V2 = v_besch55 "soubattre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  souffrir_V2 = v_besch27 "souffrir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  soumettre_V2 = v_besch56 "soumettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  sourire_V2 = v_besch79 "sourire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  souscrire_V2 = v_besch80 "souscrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  sous_entendre_V2 = v_besch53 "sous-entendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  sous_tendre_V2 = v_besch53 "sous-tendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  soustraire_V2 = v_besch61 "soustraire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  soutenir_V2 = v_besch23 "soutenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  souvenir_V = v_besch23 "souvenir" ** {isRefl = False ; aux = VHabere ; lock_V = <> ; c2 = complAcc} ;
  subvenir_V2 = v_besch23 "subvenir" ** {isRefl = False ; aux = VEsse ; lock_V2 = <> ; c2 = complDat} ;
  suffire_V2 = v_besch81 "suffire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  suivre_V2 = v_besch75 "suivre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  surfaire_V2 = v_besch62 "surfaire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  surprendre_V2 = v_besch54 "surprendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  surproduire_V2 = v_besch82 "surproduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  surseoir_V2 = v_besch51 "surseoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  surtondre_V2 = v_besch53 "surtondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  survenir_V = v_besch23 "survenir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  survivre_V2 = v_besch76 "survivre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  suspendre_V2 = v_besch53 "suspendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  taire_V2 = v_besch63 "taire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  teindre_V2 = v_besch57 "teindre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  tendre_V2 = v_besch53 "tendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  tenir_V2 = v_besch23 "tenir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complDat} ;
  tondre_V2 = v_besch53 "tondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  tordre_V2 = v_besch53 "tordre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  traduire_V2 = v_besch82 "traduire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  traire_V2 = v_besch61 "traire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  transcrire_V2 = v_besch80 "transcrire" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  transmettre_V2 = v_besch56 "transmettre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  transparaître_V = v_besch64 "transparaître" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  tréfondre_V2 = v_besch53 "tréfondre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  tressaillir_V = v_besch29 "tressaillir" ** {isRefl = False ; aux = VHabere ; lock_V = <>} ;
  vaincre_V2 = v_besch60 "vaincre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  valoir_V2 = v_besch47 "valoir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  vendre_V2 = v_besch53 "vendre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  venir_V = v_besch23 "venir" ** {isRefl = False ; aux = VEsse ; lock_V = <>} ;
  vêtir_V2 = v_besch26 "vêtir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  vivre_V2 = v_besch76 "vivre" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  voir_V2 = v_besch39 "voir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complAcc} ;
  vouloir_V2 = v_besch48 "vouloir" ** {isRefl = False ; aux = VHabere ; lock_V2 = <> ; c2 = complGen} ;

}
