--# -path=.:../romance:../abstract:../../prelude

-- Irregular verbs from Nancy, based on a list from Sylvain Pogodalla, 25/11/2004
-- Translated to GF by Aarne Ranta
-- added extracted subcat information 29/11

concrete VerbsFre of VerbsFreAbs = --- CategoriesFre **
  open TypesFre, MorphoFre, ConjugNancy in {

lincat VN  = {s : VForm => Str ; aux : VAux} ;
lincat VN2 = {s : VForm => Str ; aux : VAux ; c : Case} ;

-- all verbs in classes with "er" and "finir" are omitted

lin 
  abattreVN2 = v_nancy55 "abattre" ** {aux = AHabere ; c = Acc} ;
  absoudreVN2 = v_nancy72 "absoudre" ** {aux = AHabere ; c = Acc} ;
  abstenirVN = v_nancy23 "abstenir" ** {aux = AHabere ; c = Acc} ;
  abstraireVN2 = v_nancy61 "abstraire" ** {aux = AHabere ; c = Acc} ;
  accourirVN = v_nancy33 "accourir" ** {aux = AHabere} ;
  accroîtreVN2 = v_nancy73 "accroître" ** {aux = AHabere ; c = Acc} ;
  accueillirVN2 = v_nancy28 "accueillir" ** {aux = AHabere ; c = Acc} ;
  acquérirVN2 = v_nancy24 "acquérir" ** {aux = AHabere ; c = Acc} ;
  adjoindreVN2 = v_nancy58 "adjoindre" ** {aux = AHabere ; c = Acc} ;
  admettreVN2 = v_nancy56 "admettre" ** {aux = AHabere ; c = Acc} ;
  advenirVN = v_nancy23 "advenir" ** {aux = AEsse} ;
  allerVN = v_nancy22 "aller" ** {aux = AEsse} ;
  apercevoirVN2 = v_nancy38 "apercevoir" ** {aux = AHabere ; c = Gen} ;
  apparaîtreVN = v_nancy64 "apparaître" ** {aux = AHabere} ;
  appartenirVN2 = v_nancy23 "appartenir" ** {aux = AHabere ; c = Dat} ;
  appendreVN2 = v_nancy53 "appendre" ** {aux = AHabere ; c = Acc} ;
  apprendreVN2 = v_nancy54 "apprendre" ** {aux = AHabere ; c = Acc} ;
  assaillirVN2 = v_nancy29 "assaillir" ** {aux = AHabere ; c = Acc} ;
  asseoirVN2 = v_nancy49 "asseoir" ** {aux = AHabere ; c = Acc} ;
  astreindreVN2 = v_nancy57 "astreindre" ** {aux = AHabere ; c = Acc} ;
  atteindreVN2 = v_nancy57 "atteindre" ** {aux = AHabere ; c = Acc} ;
  attendreVN2 = v_nancy53 "attendre" ** {aux = AHabere ; c = Dat} ;
  avoirVN2 = v_nancy1 "avoir" ** {aux = AHabere ; c = Acc} ;
  battreVN2 = v_nancy55 "battre" ** {aux = AHabere ; c = Acc} ;
  boireVN2 = v_nancy69 "boire" ** {aux = AHabere ; c = Acc} ;
  bouillirVN2 = v_nancy31 "bouillir" ** {aux = AHabere ; c = Acc} ;
  braireVN = v_nancy61 "braire" ** {aux = AHabere} ;
  ceindreVN2 = v_nancy57 "ceindre" ** {aux = AHabere ; c = Acc} ;
  choirVN = v_nancy52 "choir" ** {aux = AEsse} ;
  circonscrireVN2 = v_nancy80 "circonscrire" ** {aux = AHabere ; c = Acc} ;
  circonvenirVN2 = v_nancy23 "circonvenir" ** {aux = AHabere ; c = Acc} ;
  cloreVN2 = v_nancy70 "clore" ** {aux = AHabere ; c = Acc} ;
  combattreVN2 = v_nancy55 "combattre" ** {aux = AHabere ; c = Acc} ;
  commettreVN2 = v_nancy56 "commettre" ** {aux = AHabere ; c = Acc} ;
  comparaîtreVN2 = v_nancy64 "comparaître" ** {aux = AHabere ; c = Acc} ;
  complaireVN2 = v_nancy63 "complaire" ** {aux = AHabere ; c = Dat} ;
  comprendreVN2 = v_nancy54 "comprendre" ** {aux = AHabere ; c = Acc} ;
  compromettreVN2 = v_nancy56 "compromettre" ** {aux = AHabere ; c = Acc} ;
  concevoirVN2 = v_nancy38 "concevoir" ** {aux = AHabere ; c = Acc} ;
  conclureVN2 = v_nancy71 "conclure" ** {aux = AHabere ; c = Acc} ;
  concourirVN2 = v_nancy33 "concourir" ** {aux = AHabere ; c = Acc} ;
  condescendreVN2 = v_nancy53 "condescendre" ** {aux = AHabere ; c = Dat} ;
  conduireVN2 = v_nancy82 "conduire" ** {aux = AHabere ; c = Acc} ;
  confireVN2 = v_nancy81 "confire" ** {aux = AHabere ; c = Acc} ;
  confondreVN2 = v_nancy53 "confondre" ** {aux = AHabere ; c = Acc} ;
  conjoindreVN2 = v_nancy58 "conjoindre" ** {aux = AHabere ; c = Acc} ;
  connaîtreVN2 = v_nancy64 "connaître" ** {aux = AHabere ; c = Acc} ;
  conquérirVN2 = v_nancy24 "conquérir" ** {aux = AHabere ; c = Acc} ;
  consentirVN2 = v_nancy25 "consentir" ** {aux = AHabere ; c = Dat} ;
  construireVN2 = v_nancy82 "construire" ** {aux = AHabere ; c = Acc} ;
  contenirVN2 = v_nancy23 "contenir" ** {aux = AHabere ; c = Acc} ;
  contraindreVN2 = v_nancy59 "contraindre" ** {aux = AHabere ; c = Acc} ;
  contrebattreVN2 = v_nancy55 "contrebattre" ** {aux = AHabere ; c = Acc} ;
  contredireVN2 = v_nancy78 "contredire" ** {aux = AHabere ; c = Acc} ;
  contrefaireVN2 = v_nancy62 "contrefaire" ** {aux = AHabere ; c = Acc} ;
  contrevenirVN2 = v_nancy23 "contrevenir" ** {aux = AHabere ; c = Dat} ;
  convaincreVN2 = v_nancy60 "convaincre" ** {aux = AHabere ; c = Gen} ;
  convenirVN2 = v_nancy23 "convenir" ** {aux = AHabere ; c = Gen} ;
  correspondreVN2 = v_nancy53 "correspondre" ** {aux = AHabere ; c = Dat} ;
  corrompreVN2 = v_nancy53 "corrompre" ** {aux = AHabere ; c = Acc} ;
  coudreVN2 = v_nancy73 "coudre" ** {aux = AHabere ; c = Acc} ;
  courirVN2 = v_nancy33 "courir" ** {aux = AHabere ; c = Acc} ;
  couvrirVN2 = v_nancy27 "couvrir" ** {aux = AHabere ; c = Acc} ;
  craindreVN2 = v_nancy59 "craindre" ** {aux = AHabere ; c = Acc} ;
  croireVN2 = v_nancy68 "croire" ** {aux = AHabere ; c = Dat} ;
  croîtreVN = v_nancy67 "croître" ** {aux = AEsse} ;
  cueillirVN2 = v_nancy28 "cueillir" ** {aux = AHabere ; c = Acc} ;
  cuireVN2 = v_nancy82 "cuire" ** {aux = AHabere ; c = Acc} ;
  débattreVN2 = v_nancy55 "débattre" ** {aux = AHabere ; c = Acc} ;
  débouillirVN2 = v_nancy31 "débouillir" ** {aux = AHabere ; c = Acc} ;
  décevoirVN2 = v_nancy38 "décevoir" ** {aux = AHabere ; c = Acc} ;
  déchoirVN2 = v_nancy52 "déchoir" ** {aux = AHabere ; c = Acc} ;
  décloreVN2 = v_nancy70 "déclore" ** {aux = AHabere ; c = Acc} ;
  décommettreVN2 = v_nancy56 "décommettre" ** {aux = AHabere ; c = Acc} ;
  déconfireVN2 = v_nancy81 "déconfire" ** {aux = AHabere ; c = Acc} ;
  découdreVN2 = v_nancy73 "découdre" ** {aux = AHabere ; c = Acc} ;
  découvrirVN2 = v_nancy27 "découvrir" ** {aux = AHabere ; c = Acc} ;
  décrireVN2 = v_nancy80 "décrire" ** {aux = AHabere ; c = Acc} ;
  décroîtreVN2 = v_nancy67 "décroître" ** {aux = AHabere ; c = Acc} ;
  décuireVN2 = v_nancy82 "décuire" ** {aux = AHabere ; c = Acc} ;
  déduireVN2 = v_nancy82 "déduire" ** {aux = AHabere ; c = Acc} ;
  défaillirVN = v_nancy30 "défaillir" ** {aux = AHabere} ;
  défaireVN2 = v_nancy62 "défaire" ** {aux = AHabere ; c = Acc} ;
  défendreVN2 = v_nancy53 "défendre" ** {aux = AHabere ; c = Acc} ;
  démentirVN2 = v_nancy25 "démentir" ** {aux = AHabere ; c = Acc} ;
  démettreVN2 = v_nancy56 "démettre" ** {aux = AHabere ; c = Acc} ;
  démordreVN = v_nancy53 "démordre" ** {aux = AHabere} ;
  départirVN2 = v_nancy25 "départir" ** {aux = AHabere ; c = Gen} ;
  dépeindreVN2 = v_nancy57 "dépeindre" ** {aux = AHabere ; c = Acc} ;
  dépendreVN2 = v_nancy53 "dépendre" ** {aux = AHabere ; c = Gen} ;
  déplaireVN = v_nancy63 "déplaire" ** {aux = AHabere} ;
  dépourvoirVN2 = v_nancy40 "dépourvoir" ** {aux = AHabere ; c = Acc} ;
  déprendreVN2 = v_nancy54 "déprendre" ** {aux = AHabere ; c = Gen} ;
  désapprendreVN2 = v_nancy54 "désapprendre" ** {aux = AHabere ; c = Acc} ;
  descendreVN2 = v_nancy53 "descendre" ** {aux = AHabere ; c = Acc} ;
  desservirVN2 = v_nancy35 "desservir" ** {aux = AHabere ; c = Acc} ;
  déteindreVN2 = v_nancy57 "déteindre" ** {aux = AHabere ; c = Acc} ;
  détendreVN2 = v_nancy53 "détendre" ** {aux = AHabere ; c = Acc} ;
  détenirVN2 = v_nancy23 "détenir" ** {aux = AHabere ; c = Acc} ;
  détordreVN2 = v_nancy53 "détordre" ** {aux = AHabere ; c = Acc} ;
  détruireVN2 = v_nancy82 "détruire" ** {aux = AHabere ; c = Acc} ;
  devenirVN = v_nancy23 "devenir" ** {aux = AEsse} ;
  dévêtirVN2 = v_nancy26 "dévêtir" ** {aux = AHabere ; c = Acc} ;
  devoirVN2 = v_nancy42 "devoir" ** {aux = AHabere ; c = Acc} ;
  direVN2 = v_nancy78 "dire" ** {aux = AHabere ; c = Acc} ;
  disconvenirVN2 = v_nancy23 "disconvenir" ** {aux = AHabere ; c = Gen} ;
  discourirVN2 = v_nancy33 "discourir" ** {aux = AHabere ; c = Gen} ;
  disjoindreVN2 = v_nancy58 "disjoindre" ** {aux = AHabere ; c = Acc} ;
  disparaîtreVN2 = v_nancy64 "disparaître" ** {aux = AHabere ; c = Acc} ;
  dissoudreVN2 = v_nancy72 "dissoudre" ** {aux = AHabere ; c = Acc} ;
  distendreVN2 = v_nancy53 "distendre" ** {aux = AHabere ; c = Acc} ;
  distordreVN2 = v_nancy53 "distordre" ** {aux = AHabere ; c = Acc} ;
  distraireVN2 = v_nancy61 "distraire" ** {aux = AHabere ; c = Acc} ;
  dormirVN2 = v_nancy32 "dormir" ** {aux = AHabere ; c = Acc} ;
  ébattreVN = v_nancy55 "ébattre" ** {aux = AHabere ; c = Acc} ;
  échoirVN2 = v_nancy52 "échoir" ** {aux = AEsse ; c = Dat} ;
  écloreVN2 = v_nancy70 "éclore" ** {aux = AHabere ; c = Acc} ;
  éconduireVN2 = v_nancy82 "éconduire" ** {aux = AHabere ; c = Acc} ;
  écrireVN2 = v_nancy80 "écrire" ** {aux = AHabere ; c = Acc} ;
  élireVN2 = v_nancy77 "élire" ** {aux = AHabere ; c = Acc} ;
  embatreVN2 = v_nancy55 "embatre" ** {aux = AHabere ; c = Acc} ;
  embattreVN2 = v_nancy55 "embattre" ** {aux = AHabere ; c = Acc} ;
  emboireVN = v_nancy69 "emboire" ** {aux = AHabere ; c = Acc} ;
  émettreVN2 = v_nancy56 "émettre" ** {aux = AHabere ; c = Acc} ;
  émoudreVN2 = v_nancy74 "émoudre" ** {aux = AHabere ; c = Acc} ;
  émouvoirVN2 = v_nancy44 "émouvoir" ** {aux = AHabere ; c = Acc} ;
  empreindreVN2 = v_nancy57 "empreindre" ** {aux = AHabere ; c = Gen} ;
  enceindreVN2 = v_nancy57 "enceindre" ** {aux = AHabere ; c = Acc} ;
  encloreVN2 = v_nancy70 "enclore" ** {aux = AHabere ; c = Acc} ;
  encourirVN2 = v_nancy33 "encourir" ** {aux = AHabere ; c = Acc} ;
  endormirVN2 = v_nancy32 "endormir" ** {aux = AHabere ; c = Acc} ;
  enduireVN2 = v_nancy82 "enduire" ** {aux = AHabere ; c = Acc} ;
  enfreindreVN2 = v_nancy57 "enfreindre" ** {aux = AHabere ; c = Acc} ;
  enfuirVN = v_nancy36 "enfuir" ** {aux = AHabere ; c = Acc} ;
  enjoindreVN2 = v_nancy58 "enjoindre" ** {aux = AHabere ; c = Acc} ;
  enquérirVN = v_nancy24 "enquérir" ** {aux = AHabere ; c = Acc} ;
  entendreVN2 = v_nancy53 "entendre" ** {aux = AHabere ; c = Acc} ;
  entr'apercevoirVN = v_nancy38 "entr'apercevoir" ** {aux = AHabere ; c = Acc} ;
  entrebattreVN = v_nancy55 "entrebattre" ** {aux = AHabere ; c = Acc} ;
  entre_détruireVN = v_nancy82 "entre-détruire" ** {aux = AHabere ; c = Acc} ;
  entre_haïrVN = v_nancy20 "entre-haïr" ** {aux = AHabere ; c = Acc} ;
  entremettreVN = v_nancy56 "entremettre" ** {aux = AHabere ; c = Acc} ;
  entre_nuireVN = v_nancy82 "entre-nuire" ** {aux = AHabere} ;
  entreprendreVN2 = v_nancy54 "entreprendre" ** {aux = AHabere ; c = Acc} ;
  entretenirVN2 = v_nancy23 "entretenir" ** {aux = AHabere ; c = Acc} ;
  entrevoirVN2 = v_nancy39 "entrevoir" ** {aux = AHabere ; c = Acc} ;
  entrouvrirVN2 = v_nancy27 "entrouvrir" ** {aux = AHabere ; c = Acc} ;
  envoyerVN2 = v_nancy18 "envoyer" ** {aux = AHabere ; c = Acc} ;
  épandreVN2 = v_nancy53 "épandre" ** {aux = AHabere ; c = Acc} ;
  éperdreVN = v_nancy53 "éperdre" ** {aux = AHabere ; c = Acc} ;
  éprendreVN = v_nancy54 "éprendre" ** {aux = AHabere ; c = Acc} ;
  équivaloirVN2 = v_nancy47 "équivaloir" ** {aux = AHabere ; c = Dat} ;
  éteindreVN2 = v_nancy57 "éteindre" ** {aux = AHabere ; c = Acc} ;
  étendreVN2 = v_nancy53 "étendre" ** {aux = AHabere ; c = Acc} ;
  étreindreVN2 = v_nancy57 "étreindre" ** {aux = AHabere ; c = Acc} ;
  êtreVN = v_nancy2 "être" ** {aux = AHabere} ;
  exclureVN2 = v_nancy71 "exclure" ** {aux = AHabere ; c = Acc} ;
  extraireVN2 = v_nancy61 "extraire" ** {aux = AHabere ; c = Acc} ;
  faillirVN2 = v_nancy30 "faillir" ** {aux = AHabere ; c = Dat} ;
  faireVN2 = v_nancy62 "faire" ** {aux = AHabere ; c = Acc} ;
  falloirVN = v_nancy46 "falloir" ** {aux = AHabere} ;
  feindreVN2 = v_nancy57 "feindre" ** {aux = AHabere ; c = Acc} ;
  fendreVN2 = v_nancy53 "fendre" ** {aux = AHabere ; c = Acc} ;
  fondreVN2 = v_nancy53 "fondre" ** {aux = AHabere ; c = Acc} ;
  forfaireVN2 = v_nancy62 "forfaire" ** {aux = AHabere ; c = Dat} ;
  foutreVN2 = v_nancy53 "foutre" ** {aux = AHabere ; c = Gen} ;
  frireVN2 = v_nancy81 "frire" ** {aux = AHabere ; c = Acc} ;
  fuirVN2 = v_nancy36 "fuir" ** {aux = AHabere ; c = Acc} ;
  geindreVN2 = v_nancy57 "geindre" ** {aux = AHabere ; c = Acc} ;
  gésirVN2 = mkNV (conj3gésir "gésir") ** {aux = AHabere ; c = Acc} ;
  haïrVN2 = v_nancy20 "haïr" ** {aux = AHabere ; c = Acc} ;
  inclureVN2 = v_nancy71 "inclure" ** {aux = AHabere ; c = Acc} ;
  induireVN2 = v_nancy82 "induire" ** {aux = AHabere ; c = Acc} ;
  inscrireVN2 = v_nancy80 "inscrire" ** {aux = AHabere ; c = Acc} ;
  instruireVN2 = v_nancy82 "instruire" ** {aux = AHabere ; c = Acc} ;
  interdireVN2 = v_nancy78 "interdire" ** {aux = AHabere ; c = Acc} ;
  interrompreVN2 = v_nancy53 "interrompre" ** {aux = AHabere ; c = Acc} ;
  intervenirVN = v_nancy23 "intervenir" ** {aux = AEsse} ;
  introduireVN2 = v_nancy82 "introduire" ** {aux = AHabere ; c = Acc} ;
  joindreVN2 = v_nancy58 "joindre" ** {aux = AHabere ; c = Acc} ;
  lireVN2 = v_nancy77 "lire" ** {aux = AHabere ; c = Acc} ;
  luireVN = v_nancy82 "luire" ** {aux = AHabere} ;
  mainmettreVN2 = v_nancy56 "mainmettre" ** {aux = AHabere ; c = Acc} ;
  maintenirVN2 = v_nancy23 "maintenir" ** {aux = AHabere ; c = Acc} ;
  méconnaîtreVN2 = v_nancy64 "méconnaître" ** {aux = AHabere ; c = Acc} ;
  mécroireVN2 = v_nancy68 "mécroire" ** {aux = AHabere ; c = Acc} ;
  médireVN2 = v_nancy78 "médire" ** {aux = AHabere ; c = Gen} ;
  mentirVN2 = v_nancy25 "mentir" ** {aux = AEsse ; c = Dat} ;
  méprendreVN2 = v_nancy54 "méprendre" ** {aux = AHabere ; c = Dat} ;
  messeoirVN2 = v_nancy50 "messeoir" ** {aux = AHabere ; c = Acc} ;
  mettreVN2 = v_nancy56 "mettre" ** {aux = AHabere ; c = Acc} ;
  mévendreVN2 = v_nancy53 "mévendre" ** {aux = AHabere ; c = Acc} ;
  mordreVN2 = v_nancy53 "mordre" ** {aux = AHabere ; c = Acc} ;
  morfondreVN = v_nancy53 "morfondre" ** {aux = AHabere ; c = Acc} ;
  moudreVN2 = v_nancy74 "moudre" ** {aux = AHabere ; c = Acc} ;
  mourirVN = v_nancy34 "mourir" ** {aux = AEsse} ;
  mouvoirVN2 = v_nancy44 "mouvoir" ** {aux = AHabere ; c = Gen} ;
  naîtreVN = v_nancy65 "naître" ** {aux = AEsse} ;
  nuireVN2 = v_nancy82 "nuire" ** {aux = AHabere ; c = Dat} ;
  obtenirVN2 = v_nancy23 "obtenir" ** {aux = AHabere ; c = Acc} ;
  obvenirVN = v_nancy23 "obvenir" ** {aux = AEsse} ;
  occlureVN2 = v_nancy71 "occlure" ** {aux = AHabere ; c = Acc} ;
  offrirVN2 = v_nancy27 "offrir" ** {aux = AHabere ; c = Acc} ;
  oindreVN2 = v_nancy58 "oindre" ** {aux = AHabere ; c = Acc} ;
  omettreVN2 = v_nancy56 "omettre" ** {aux = AHabere ; c = Acc} ;
  ouïrVN2 = v_nancy37 "ouïr" ** {aux = AHabere ; c = Acc} ;
  ouvrirVN2 = v_nancy27 "ouvrir" ** {aux = AHabere ; c = Acc} ;
  paîtreVN2 = v_nancy66 "paître" ** {aux = AHabere ; c = Acc} ;
  paîtreVN = v_nancy66 "paître" ** {aux = AHabere ; c = Acc} ;
  paraîtreVN = v_nancy64 "paraître" ** {aux = AHabere} ;
  parcourirVN2 = v_nancy33 "parcourir" ** {aux = AHabere ; c = Acc} ;
  parfondreVN2 = v_nancy53 "parfondre" ** {aux = AHabere ; c = Acc} ;
  partirVN = v_nancy25 "partir" ** {aux = AEsse} ;
  parvenirVN = v_nancy23 "parvenir" ** {aux = AEsse} ;
  peindreVN2 = v_nancy57 "peindre" ** {aux = AHabere ; c = Acc} ;
  pendreVN2 = v_nancy53 "pendre" ** {aux = AHabere ; c = Acc} ;
  percevoirVN2 = v_nancy38 "percevoir" ** {aux = AHabere ; c = Acc} ;
  perdreVN2 = v_nancy53 "perdre" ** {aux = AHabere ; c = Acc} ;
  permettreVN2 = v_nancy56 "permettre" ** {aux = AHabere ; c = Acc} ;
  plaindreVN2 = v_nancy59 "plaindre" ** {aux = AHabere ; c = Acc} ;
  plaireVN2 = v_nancy63 "plaire" ** {aux = AHabere ; c = Dat} ;
  pleuvoirVN = v_nancy45 "pleuvoir" ** {aux = AHabere} ;
  poindreVN2 = v_nancy58 "poindre" ** {aux = AHabere ; c = Acc} ;
  pondreVN2 = v_nancy53 "pondre" ** {aux = AHabere ; c = Acc} ;
  pourfendreVN2 = v_nancy53 "pourfendre" ** {aux = AHabere ; c = Acc} ;
  poursuivreVN2 = v_nancy75 "poursuivre" ** {aux = AHabere ; c = Acc} ;
  pourvoirVN2 = v_nancy40 "pourvoir" ** {aux = AHabere ; c = Dat} ;
  pouvoirVN = v_nancy43 "pouvoir" ** {aux = AHabere} ;
  prédireVN2 = v_nancy78 "prédire" ** {aux = AHabere ; c = Acc} ;
  prendreVN2 = v_nancy54 "prendre" ** {aux = AHabere ; c = Acc} ;
  prescrireVN2 = v_nancy80 "prescrire" ** {aux = AHabere ; c = Acc} ;
  pressentirVN2 = v_nancy25 "pressentir" ** {aux = AHabere ; c = Acc} ;
  prétendreVN2 = v_nancy53 "prétendre" ** {aux = AHabere ; c = Dat} ;
  prévaloirVN2 = v_nancy47 "prévaloir" ** {aux = AHabere ; c = Gen} ;
  prévenirVN2 = v_nancy23 "prévenir" ** {aux = AHabere ; c = Acc} ;
  prévoirVN2 = v_nancy39 "prévoir" ** {aux = AHabere ; c = Acc} ;
  produireVN2 = v_nancy82 "produire" ** {aux = AHabere ; c = Acc} ;
  promettreVN2 = v_nancy56 "promettre" ** {aux = AHabere ; c = Acc} ;
  promouvoirVN2 = v_nancy44 "promouvoir" ** {aux = AHabere ; c = Acc} ;
  proscrireVN2 = v_nancy80 "proscrire" ** {aux = AHabere ; c = Acc} ;
  provenirVN = v_nancy23 "provenir" ** {aux = AEsse} ;
  rabattreVN2 = v_nancy55 "rabattre" ** {aux = AHabere ; c = Acc} ;
  raireVN2 = v_nancy61 "raire" ** {aux = AHabere ; c = Acc} ;
  rapprendreVN2 = v_nancy54 "rapprendre" ** {aux = AHabere ; c = Acc} ;
  rasseoirVN2 = v_nancy49 "rasseoir" ** {aux = AHabere ; c = Acc} ;
  réadmettreVN2 = v_nancy56 "réadmettre" ** {aux = AHabere ; c = Acc} ;
  réapparaîtreVN = v_nancy64 "réapparaître" ** {aux = AHabere} ;
  réapprendreVN2 = v_nancy54 "réapprendre" ** {aux = AHabere ; c = Acc} ;
  rebattreVN2 = v_nancy55 "rebattre" ** {aux = AHabere ; c = Acc} ;
  recevoirVN2 = v_nancy38 "recevoir" ** {aux = AHabere ; c = Acc} ;
  recomparaîtreVN2 = v_nancy64 "recomparaître" ** {aux = AHabere ; c = Acc} ;
  reconduireVN2 = v_nancy82 "reconduire" ** {aux = AHabere ; c = Acc} ;
  reconnaîtreVN2 = v_nancy64 "reconnaître" ** {aux = AHabere ; c = Acc} ;
  reconquérirVN2 = v_nancy24 "reconquérir" ** {aux = AHabere ; c = Acc} ;
  reconstruireVN2 = v_nancy82 "reconstruire" ** {aux = AHabere ; c = Acc} ;
  recoudreVN2 = v_nancy73 "recoudre" ** {aux = AHabere ; c = Acc} ;
  recourirVN2 = v_nancy33 "recourir" ** {aux = AHabere ; c = Dat} ;
  recouvrirVN2 = v_nancy27 "recouvrir" ** {aux = AHabere ; c = Acc} ;
  récrireVN2 = v_nancy80 "récrire" ** {aux = AHabere ; c = Acc} ;
  recroîtreVN2 = v_nancy67 "recroître" ** {aux = AHabere ; c = Acc} ;
  recueillirVN2 = v_nancy28 "recueillir" ** {aux = AHabere ; c = Acc} ;
  recuireVN2 = v_nancy82 "recuire" ** {aux = AHabere ; c = Acc} ;
  redécouvrirVN2 = v_nancy27 "redécouvrir" ** {aux = AHabere ; c = Acc} ;
  redéfaireVN2 = v_nancy62 "redéfaire" ** {aux = AHabere ; c = Acc} ;
  redescendreVN2 = v_nancy53 "redescendre" ** {aux = AHabere ; c = Acc} ;
  redevenirVN = v_nancy23 "redevenir" ** {aux = AEsse} ;
  redevoirVN2 = v_nancy42 "redevoir" ** {aux = AHabere ; c = Acc} ;
  redireVN2 = v_nancy78 "redire" ** {aux = AHabere ; c = Acc} ;
  réduireVN2 = v_nancy82 "réduire" ** {aux = AHabere ; c = Dat} ;
  réécrireVN2 = v_nancy80 "réécrire" ** {aux = AHabere ; c = Acc} ;
  réélireVN2 = v_nancy77 "réélire" ** {aux = AHabere ; c = Acc} ;
  réentendreVN2 = v_nancy53 "réentendre" ** {aux = AHabere ; c = Acc} ;
  refaireVN2 = v_nancy62 "refaire" ** {aux = AHabere ; c = Acc} ;
  refendreVN2 = v_nancy53 "refendre" ** {aux = AHabere ; c = Acc} ;
  refondreVN2 = v_nancy53 "refondre" ** {aux = AHabere ; c = Acc} ;
  réinscrireVN2 = v_nancy80 "réinscrire" ** {aux = AHabere ; c = Acc} ;
  réintroduireVN2 = v_nancy82 "réintroduire" ** {aux = AHabere ; c = Acc} ;
  rejoindreVN2 = v_nancy58 "rejoindre" ** {aux = AHabere ; c = Acc} ;
  relireVN2 = v_nancy77 "relire" ** {aux = AHabere ; c = Acc} ;
  reluireVN2 = v_nancy82 "reluire" ** {aux = AHabere ; c = Acc} ;
  remettreVN2 = v_nancy56 "remettre" ** {aux = AHabere ; c = Acc} ;
  remordreVN2 = v_nancy53 "remordre" ** {aux = AHabere ; c = Acc} ;
  remoudreVN2 = v_nancy74 "remoudre" ** {aux = AHabere ; c = Acc} ;
  renaîtreVN2 = v_nancy65 "renaître" ** {aux = AHabere ; c = Acc} ;
  rendormirVN2 = v_nancy32 "rendormir" ** {aux = AHabere ; c = Acc} ;
  rendreVN2 = v_nancy53 "rendre" ** {aux = AHabere ; c = Acc} ;
  rentraireVN2 = v_nancy61 "rentraire" ** {aux = AHabere ; c = Acc} ;
  rentrouvrirVN2 = v_nancy27 "rentrouvrir" ** {aux = AHabere ; c = Acc} ;
  renvoyerVN2 = v_nancy18 "renvoyer" ** {aux = AHabere ; c = Acc} ;
  repaîtreVN2 = v_nancy66 "repaître" ** {aux = AHabere ; c = Acc} ;
  répandreVN2 = v_nancy53 "répandre" ** {aux = AHabere ; c = Acc} ;
  reparaîtreVN = v_nancy64 "reparaître" ** {aux = AEsse} ;
  repartirVN = v_nancy25 "repartir" ** {aux = AEsse} ;
  repeindreVN2 = v_nancy57 "repeindre" ** {aux = AHabere ; c = Acc} ;
  rependreVN2 = v_nancy53 "rependre" ** {aux = AHabere ; c = Acc} ;
  repentirVN = v_nancy25 "repentir" ** {aux = AHabere ; c = Acc} ;
  reperdreVN2 = v_nancy53 "reperdre" ** {aux = AHabere ; c = Acc} ;
  repleuvoirVN = v_nancy45 "repleuvoir" ** {aux = AHabere} ;
  répondreVN2 = v_nancy53 "répondre" ** {aux = AHabere ; c = Acc} ;
  reprendreVN2 = v_nancy54 "reprendre" ** {aux = AHabere ; c = Acc} ;
  reproduireVN2 = v_nancy82 "reproduire" ** {aux = AHabere ; c = Acc} ;
  requérirVN2 = v_nancy24 "requérir" ** {aux = AHabere ; c = Acc} ;
  résoudreVN2 =  mkNV (conj3résoudre "résoudre") ** {aux = AHabere ; c = Acc} ;
  ressentirVN2 = v_nancy25 "ressentir" ** {aux = AHabere ; c = Gen} ;
  resservirVN2 = v_nancy35 "resservir" ** {aux = AHabere ; c = Acc} ;
  ressortirVN = v_nancy25 "ressortir" ** {aux = AEsse} ;
  ressouvenirVN = v_nancy23 "ressouvenir" ** {aux = AHabere ; c = Acc} ;
  restreindreVN2 = v_nancy57 "restreindre" ** {aux = AHabere ; c = Acc} ;
  reteindreVN2 = v_nancy57 "reteindre" ** {aux = AHabere ; c = Acc} ;
  retendreVN2 = v_nancy53 "retendre" ** {aux = AHabere ; c = Acc} ;
  retenirVN2 = v_nancy23 "retenir" ** {aux = AHabere ; c = Acc} ;
  retondreVN2 = v_nancy53 "retondre" ** {aux = AHabere ; c = Acc} ;
  retordreVN2 = v_nancy53 "retordre" ** {aux = AHabere ; c = Acc} ;
  retraduireVN2 = v_nancy82 "retraduire" ** {aux = AHabere ; c = Acc} ;
  retraireVN2 = v_nancy61 "retraire" ** {aux = AHabere ; c = Acc} ;
  retranscrireVN2 = v_nancy80 "retranscrire" ** {aux = AHabere ; c = Acc} ;
  retransmettreVN2 = v_nancy56 "retransmettre" ** {aux = AHabere ; c = Acc} ;
  rétreindreVN2 = v_nancy57 "rétreindre" ** {aux = AHabere ; c = Acc} ;
  revaloirVN2 = v_nancy47 "revaloir" ** {aux = AHabere ; c = Acc} ;
  revendreVN2 = v_nancy53 "revendre" ** {aux = AHabere ; c = Acc} ;
  revenirVN = v_nancy23 "revenir" ** {aux = AEsse} ;
  revêtirVN2 = v_nancy26 "revêtir" ** {aux = AHabere ; c = Acc} ;
  revivreVN2 = v_nancy76 "revivre" ** {aux = AHabere ; c = Acc} ;
  revoirVN2 = v_nancy39 "revoir" ** {aux = AHabere ; c = Acc} ;
  revouloirVN2 = v_nancy48 "revouloir" ** {aux = AHabere ; c = Acc} ;
  rireVN2 = v_nancy79 "rire" ** {aux = AHabere ; c = Gen} ;
  rompreVN2 = v_nancy53 "rompre" ** {aux = AHabere ; c = Acc} ;
  rouvrirVN2 = v_nancy27 "rouvrir" ** {aux = AHabere ; c = Acc} ;
  saillirVN2 = v_nancy29 "saillir" ** {aux = AHabere ; c = Acc} ;
  satisfaireVN2 = v_nancy62 "satisfaire" ** {aux = AHabere ; c = Dat} ;
  savoirVN2 = v_nancy41 "savoir" ** {aux = AHabere ; c = Acc} ;
  secourirVN2 = v_nancy33 "secourir" ** {aux = AHabere ; c = Acc} ;
  séduireVN2 = v_nancy82 "séduire" ** {aux = AHabere ; c = Acc} ;
  sentirVN2 = v_nancy25 "sentir" ** {aux = AHabere ; c = Acc} ;
  seoirVN = v_nancy50 "seoir" ** {aux = AHabere} ;
  servirVN2 = v_nancy35 "servir" ** {aux = AHabere ; c = Acc} ;
  sortirVN = v_nancy25 "sortir" ** {aux = AHabere} ;
  soubattreVN2 = v_nancy55 "soubattre" ** {aux = AHabere ; c = Acc} ;
  souffrirVN2 = v_nancy27 "souffrir" ** {aux = AHabere ; c = Acc} ;
  soumettreVN2 = v_nancy56 "soumettre" ** {aux = AHabere ; c = Dat} ;
  sourireVN2 = v_nancy79 "sourire" ** {aux = AHabere ; c = Dat} ;
  souscrireVN2 = v_nancy80 "souscrire" ** {aux = AHabere ; c = Dat} ;
  sous_entendreVN2 = v_nancy53 "sous-entendre" ** {aux = AHabere ; c = Acc} ;
  sous_tendreVN2 = v_nancy53 "sous-tendre" ** {aux = AHabere ; c = Acc} ;
  soustraireVN2 = v_nancy61 "soustraire" ** {aux = AHabere ; c = Acc} ;
  soutenirVN2 = v_nancy23 "soutenir" ** {aux = AHabere ; c = Acc} ;
  souvenirVN = v_nancy23 "souvenir" ** {aux = AHabere ; c = Acc} ;
  subvenirVN2 = v_nancy23 "subvenir" ** {aux = AEsse ; c = Dat} ;
  suffireVN2 = v_nancy81 "suffire" ** {aux = AHabere ; c = Dat} ;
  suivreVN2 = v_nancy75 "suivre" ** {aux = AHabere ; c = Acc} ;
  surfaireVN2 = v_nancy62 "surfaire" ** {aux = AHabere ; c = Acc} ;
  surprendreVN2 = v_nancy54 "surprendre" ** {aux = AHabere ; c = Acc} ;
  surproduireVN2 = v_nancy82 "surproduire" ** {aux = AHabere ; c = Acc} ;
  surseoirVN2 = v_nancy51 "surseoir" ** {aux = AHabere ; c = Dat} ;
  surtondreVN2 = v_nancy53 "surtondre" ** {aux = AHabere ; c = Acc} ;
  survenirVN = v_nancy23 "survenir" ** {aux = AEsse} ;
  survivreVN2 = v_nancy76 "survivre" ** {aux = AHabere ; c = Dat} ;
  suspendreVN2 = v_nancy53 "suspendre" ** {aux = AHabere ; c = Acc} ;
  taireVN2 = v_nancy63 "taire" ** {aux = AHabere ; c = Acc} ;
  teindreVN2 = v_nancy57 "teindre" ** {aux = AHabere ; c = Acc} ;
  tendreVN2 = v_nancy53 "tendre" ** {aux = AHabere ; c = Dat} ;
  tenirVN2 = v_nancy23 "tenir" ** {aux = AHabere ; c = Dat} ;
  tondreVN2 = v_nancy53 "tondre" ** {aux = AHabere ; c = Acc} ;
  tordreVN2 = v_nancy53 "tordre" ** {aux = AHabere ; c = Acc} ;
  traduireVN2 = v_nancy82 "traduire" ** {aux = AHabere ; c = Acc} ;
  traireVN2 = v_nancy61 "traire" ** {aux = AHabere ; c = Acc} ;
  transcrireVN2 = v_nancy80 "transcrire" ** {aux = AHabere ; c = Acc} ;
  transmettreVN2 = v_nancy56 "transmettre" ** {aux = AHabere ; c = Acc} ;
  transparaîtreVN = v_nancy64 "transparaître" ** {aux = AHabere} ;
  tréfondreVN2 = v_nancy53 "tréfondre" ** {aux = AHabere ; c = Acc} ;
  tressaillirVN = v_nancy29 "tressaillir" ** {aux = AHabere} ;
  vaincreVN2 = v_nancy60 "vaincre" ** {aux = AHabere ; c = Acc} ;
  valoirVN2 = v_nancy47 "valoir" ** {aux = AHabere ; c = Acc} ;
  vendreVN2 = v_nancy53 "vendre" ** {aux = AHabere ; c = Acc} ;
  venirVN = v_nancy23 "venir" ** {aux = AEsse} ;
  vêtirVN2 = v_nancy26 "vêtir" ** {aux = AHabere ; c = Acc} ;
  vivreVN2 = v_nancy76 "vivre" ** {aux = AHabere ; c = Acc} ;
  voirVN2 = v_nancy39 "voir" ** {aux = AHabere ; c = Acc} ;
  vouloirVN2 = v_nancy48 "vouloir" ** {aux = AHabere ; c = Gen} ;

}
