--# -path=.:../romance:../abstract:../../prelude

concrete BasicIta of Basic = CategoriesIta ** open ParadigmsIta, BeschIta in {

flags 
  startcat=Phr ; lexer=textlit ; unlexer=text ;
  optimize=values ;

lin
  airplane_N = regN "aereo" ;
--V  answer_V2S = mkV2S (v2V répondre_V2) dative ;
  apartment_N = regN "apartamento" ;
  apple_N = regN "mela" ;
  art_N = femN (regN "arte") ;
--V  ask_V2Q = mkV2Q (regV "demander") dative ;
  baby_N = regN "bambino" ;
  bad_ADeg = prefADeg (mkADeg (regA "cattivo") (regA "peggio")) ;
  bank_N = regN "banca" ;
  beautiful_ADeg = prefADeg (regADeg "bello") ;
  become_VA = essereV (regV "diventare") ;
  beer_N = regN "birra" ;
--V  beg_V2V = mkV2V (regV "demander") accusative dative ;
  big_ADeg = prefADeg (regADeg "grande") ;
  bike_N = regN "bicicletta" ;
  bird_N = regN "uccello" ;
  black_ADeg = regADeg "nero" ;
  blue_ADeg = regADeg "blù" ;
  boat_N = regN "batello" ;
  book_N = regN "libro" ;
  boot_N = regN "stivale" ;
  boss_N = regN "capo" ;
  boy_N = regN "ragazzo" ;
  bread_N = regN "pane" ;
--V  break_V2 = dirV2 (regV "casser") ;
  broad_ADeg = regADeg "largo" ;
  brother_N2 = deN2 (regN "fratello") ;
  brown_ADeg = regADeg "marrone" ;
  butter_N = regN "burro" ;
  buy_V2 = dirV2 (regV "comprare") ;
----  camera_N = compN (regN "appareil" masculine) ["de photo"] ;
----  cap_N = regN "casquette" ;
  car_N = regN "macchina" ;
----  carpet_N = regN "tapis" ;
  cat_N = regN "gatto" ;
----  ceiling_N = regN "plafond" ;
----  chair_N = regN "chaise" ;
  cheese_N = regN "formaggio" ;
  child_N = regN "bambino" ;
  church_N = regN "chiesa" ;
  city_N = regN "città" ;
  clean_ADeg = regADeg "proprio" ;
  clever_ADeg = regADeg "sapiente" ; ----
--V  close_V2 = dirV2 (regV "") ;
--V  coat_N = regN "manteau" ;
  cold_ADeg = regADeg "freddo" ;
--V  come_V = venir_V ;
  computer_N = regN "computer"  ;
  country_N = regN "paese" ;
  cousin_N = regN "cugino" ; ---- cousine
  cow_N = regN "vacca" ;
--V  die_V = mourir_V ;
  dirty_ADeg = regADeg "sporco" ;
  doctor_N = mkN "medico" "medici" masculine ;
  dog_N = regN "cane" ;
  door_N = regN "porta" ;
--V  drink_V2 = boire_V2 ;
  easy_A2V = mkA2V (regA "facile") dative genitive ;
  eat_V2 = dirV2 (regV "mangiare") ;
--V  enemy_N = regN "ennemi" ;
  factory_N = regN "stabilimento" ;
  father_N2 = deN2 (regN "padre" masculine) ;
--V  fear_VS = mkVS (v2V craindre_V2) ;
  find_V2 = dirV2 (regV "trovare") ;
  fish_N = regN "pesca" ;
----  floor_N = regN "plancher" ;
  forget_V2 = dirV2 (regV "dimenticare") ;
  fridge_N = regN "frigorifero" ;
  friend_N = regN "amico" ;
  fruit_N = regN "frutta" ;
  fun_AV = mkAV (regA "divertente") genitive ;
  garden_N = regN "giardino" ;
  girl_N = regN "ragazza" ;
----  glove_N = regN "gant" ;
  gold_N = regN "oro" ;
  good_ADeg = prefADeg (mkADeg (regA "buono") 
    (mkA "migliore" "migliore" "migliori" "migliori" "meglio")) ;
--V  go_V = aller_V ;
  green_ADeg = regADeg "verde" ;
  harbour_N = regN "porto" ;
--V  hate_V2 = haïr_V2 ;
  hat_N = regN "capello" ;
--V  have_V2 = avoir_V2 ;
--V  hear_V2 = entendre_V2 ;
  hill_N = regN "collina" ;
  hope_VS = mkVS (regV "sperare") ;
  horse_N = regN "cavallo" ;
  hot_ADeg = regADeg "caldo" ;
  house_N = regN "casa" ;
  important_ADeg = regADeg "importante" ;
  industry_N = regN "industria" ;
  iron_N = regN "ferro" ;
  king_N = regN "ré" ;
--V  know_V2 = connaître_V2 ; ---- savoir_V2 : VS
  lake_N = regN "lago" ;
  lamp_N = regN "lampa" ;
--V  learn_V2 = apprendre_V2 ;
  leather_N = regN "cuoio" ;
  leave_V2 = dirV2 (regV "lasciare") ;
  like_V2 = dirV2 (regV "amare") ;
  listen_V2 = dirV2 (regV "ascoltare") ;
--V  live_V = v2V vivre_V2 ;
  long_ADeg = regADeg "lungo" ;
--V  lose_V2 = perdre_V2 ;
  love_N = regN "amore" ;
  love_V2 = dirV2 (regV "amare") ;
  man_N = regN "uomo" ;
  married_A2 = mkA2 (regA "sposato") dative ;
  meat_N = femN (regN "carne") ;
  milk_N = regN "latte" ;
  moon_N = regN "luna" ;
  mother_N2 = deN2 (femN (regN "madre")) ;
  mountain_N = regN "montagna" ;
  music_N = regN "musica" ;
  narrow_ADeg = regADeg "stretto" ;
  new_ADeg = prefADeg (regADeg "nuovo") ;
  newspaper_N = regN "giornale" ;
  oil_N = regN "olio" ;
  old_ADeg = 
    prefADeg (regADeg "veccio") ; ---- vieil
--V  open_V2 = ouvrir_V2 ;
--V  paint_V2A = mkV2A (v2V peindre_V2) accusative ;
  paper_N = regN "carta" ;
  peace_N = femN (regN "pace") ;
  pen_N = regN "stylo" ;
  planet_N = regN "planète" ;
  plastic_N = regN "plastic" ;
  play_V2 = dirV2 (regV "jouer") ;
  policeman_N = regN "policier" ;
  priest_N = regN "prêtre" ;
  probable_AS = mkAS (regA "probable") ;
  queen_N = regN "reine" ;
  radio_N = regN "radio" ;
  rain_V0 = mkV0 (pleuvoir_V) ;
  read_V2 = lire_V2 ;
  red_ADeg = regADeg "rouge" ;
  religion_N = regN "religion" ;
  restaurant_N = regN "restaurant" ;
  river_N = regN "rivière" ;
  rock_N = regN "rocher" ;
  roof_N = regN "toit" ;
  rubber_N = regN "caoutchuc" ;
  run_V = v2V courir_V2 ;
  say_VS = mkVS (v2V dire_V2) ;
  school_N = regN "école" ;
  science_N = regN "science" ;
  sea_N = regN "mer" ;
  seek_V2 = dirV2 (regV "chercher") ;
  see_V2 = voir_V2 ;
  sell_V3 = dirV3 (v2V vendre_V2) dative ;
  send_V3 = dirV3 (v2V envoyer_V2) dative ;
  sheep_N = regN "mouton" ;
  ship_N = regN "bateau" ;
  shirt_N = regN "chemise" ;
  shoe_N = regN "chaussure" ;
  shop_N = regN "magasin" ;
  short_ADeg = regADeg "court" ; ---- bref
  silver_N = regN "argent" ;
  sister_N = regN "soeur" ;
  sleep_V = v2V dormir_V2 ;
  small_ADeg = prefADeg (regADeg "petit") ;
  snake_N = regN "serpent" ;
  sock_N = regN "chaussette" ;
  speak_V2 = dirV2 (regV "parler") ;
  star_N = regN "étoile" ;
  steel_N = regN "acier" ;
  stone_N = regN "pierre" ;
  stove_N = regN "four" ;
  student_N = regN "étudiant" ;
  stupid_ADeg = regADeg "stupide" ;
  sun_N = regN "soleil" ;
  switch8off_V2 = éteindre_V2 ;
  switch8on_V2 = dirV2 (regV "allumer") ; ----
  table_N = regN "table" ;
  talk_V3 = mkV3 (regV "parler") dative genitive ;
  teacher_N = regN "professeur" ;
  teach_V2 = dirV2 (regV "enseigner") ;
  television_N = regN "télévision" ;
  thick_ADeg = compADeg (mkA "épais" "épaisse" "épais" "épaissement") ;
  thin_ADeg = regADeg "fin" ;
  train_N = regN "train" ;
  travel_V = regV "voyager" ;
  tree_N = regN "arbre" ;
 ---- trousers_N = regN "pantalon" ;
  ugly_ADeg = regADeg "laide" ;
  understand_V2 = comprendre_V2 ;
  university_N = regN "université" ;
  village_N = regN "village" ;
  wait_V2 = attendre_V2 ; ---- dative?
  walk_V = regV "marcher" ;
  warm_ADeg = regADeg "chaud" ;
  war_N = regN "guerre" ;
  watch_V2 = dirV2 (regV "regarder") ;
  water_N = regN "eau" ;
  white_ADeg = compADeg (mkA "blanc" "blanche" "blancs" "blanchement") ;
  window_N = regN "fenêtre" ;
  wine_N = regN "vin" ;
  win_V2 = dirV2 (regV "gagner") ; ---- vaincre
  woman_N = regN "femme" ;
  wonder_VQ = mkVQ (regV "étonner") ; ----- s'étonner
  wood_N = regN "bois" ;
  write_V2 = écrire_V2 ;
  yellow_ADeg = regADeg "jaune" ;
  young_ADeg = prefADeg (regADeg "jeune") ;

  do_V2 = faire_V2 ;
  now_Adv = mkAdv "maintenant" ;
  already_Adv = mkAdv "déjà" ;
  song_N = regN "chanson" ;
  add_V3 = dirV3 (regV "ajouter") dative ;
  number_N = regN "nombre" ; ---- numéro
  put_V2 = mettre_V2 ;
  stop_V = regV "arrêter" ; ---- s'arrêter
  jump_V = regV "sauter" ;
  here_Adv = mkAdv "ici" ;
  here7to_Adv = mkAdv "ici" ;
  here7from_Adv = mkAdv ["d'ici"] ;
  there_Adv = mkAdv "là" ; ---- y, là-bas
  there7to_Adv = mkAdv "là" ; --- y
  there7from_Adv = mkAdv ["de là"] ; ---- en
} ;
