--# -path=.:../abstract:../../prelude
--# -val

concrete BasicFin of Basic = CategoriesFin ** open ParadigmsFin in {

flags 
  startcat=Phr ; lexer=textlit ; unlexer=text ;
  optimize=values ;

lin

  airplane_N = regN "lentokone" ;
----  answer_V2S = mkV2S (regV "answer") "to" ;
  apartment_N = regN "asunto" ;
  apple_N = regN "omena" ; --- omenia, not omenoita
  art_N = regN "taide" ;
----  ask_V2Q = mkV2Q (regV "ask") [] ;
  baby_N = regN "vauva" ;
  bad_ADeg = mkADeg (regN "paha") "pahempi" "pahin" ;
  bank_N = regN "pankki" ;
  beautiful_ADeg = mkADeg (regN "kaunis") "kauniimpi" "kaunein" ;
----  become_VA = mkVA (irregV "become" "became" "become") ;
  beer_N = regN "olut" ;
----  beg_V2V = mkV2V (regDuplV "beg") [] "to" ;
  big_ADeg = mkADeg (reg2N "suuri" "suuria") "suurempi" "suurin" ;
  bike_N = nLukko "polkupyörä" ; --- for correct vowel harmony
  bird_N = regN "lintu" ;
  black_ADeg = mkADeg (regN "musta") "mustempi" "mustin" ;
  blue_ADeg = mkADeg (regN "sininen") "sinisempi" "sinisin" ;
  boat_N = regN "vene" ;
  book_N = regN "kirja" ;
  boot_N = regN "saapas" ;
  boss_N = regN "pomo" ;
  boy_N = reg3N "poika" "pojan" "poikia" ;
  bread_N = regN "leipä" ;
  break_V2 = dirV2 (regV "rikkoa") ;
  broad_ADeg = mkADeg (regN "leveä") "leveämpi" "levein" ;
----  brother_N2 = regN2 "brother" ;
  brown_ADeg = mkADeg (regN "ruskea") "ruskeampi" "ruskein" ;
--3  butter_N = reg3N "voi" "voin" "voita" ;
  buy_V2 = dirV2 (regV "ostaa") ;
  camera_N = regN "kamera" ;
  cap_N = regN "lakki" ;
  car_N = reg3N "auto" "auton" "autoja" ; -- regN: audon
  carpet_N = regN "matto" ;
  cat_N = regN "kissa" ;
  ceiling_N = regN "katto" ;
  chair_N = regN "tuoli" ;
  cheese_N = regN "juusto" ;
  child_N = mkN "lapsi" "lapsen" "lapsena" "lasta" "lapseen" 
            "lapsina" "lapsissa" "lasten" "lapsia" "lapsiin" human ;
  church_N = regN "kirkko" ;
  city_N = regN "kaupunki" ;
  clean_ADeg = regADeg "puhdas" ;
  clever_ADeg = regADeg "viisas" ;
  close_V2 = dirV2 (regV "sulkea") ;
  coat_N = regN "takki" ;
  cold_ADeg = mkADeg (regN "kylmä") "kylmempi" "kylmin" ;
  come_V = regV "tulla" ;
  computer_N = regN "tietokone" ;
  country_N = regN "maa" ;
  cousin_N = regN "serkku" ;
  cow_N = regN "lehmä" ;
  die_V = regV "kuolla" ;
  dirty_ADeg = mkADeg (regN "likainen") "likaisempi" "likaisin" ;
----  distance_N3 = mkN3 (regN "distance") "from" "to" ;
--3  doctor_N = reg3N "tohtori" "tohtorin" "tohtoreita" ;
  dog_N = regN "koira" ;
  door_N = reg2N "ovi" "ovia" ;
  drink_V2 = dirV2 (regV "juoda") ;
----  easy_A2V = mkA2V (regA "easy") "for" ;
  eat_V2 = dirV2 (regV "syödä") ;
  empty_ADeg = mkADeg (regN "tyhjä") "tyhjempi" "tyhjin" ;
  enemy_N = regN "vihollinen" ;
  factory_N = regN "tehdas" ;
----  father_N2 = regN2 "father" ;
----  fear_VS = mkVS (reg2V "pelätä" "pelkäsi") ;
  find_V2 = dirV2 (reg2V "löytää" "löysi") ;
  fish_N = regN "kala" ;
  floor_N = reg2N "lattia" "lattioita" ;
  forget_V2 = dirV2 (regV "unohtaa") ;
  fridge_N = regN "jääkaappi" ;
  friend_N = regN "ystävä" ;
  fruit_N = regN "hedelmä" ;
----  fun_AV = mkAV (regA "fun") ;
  garden_N = regN "puutarha" ;
  girl_N = regN "tyttö" ;
  glove_N = regN "käsine" ;
  gold_N = regN "kulta" ;
  good_ADeg = mkADeg (regN "hyvä") "parempi" "parhain" ; --- paras
  go_V = regV "mennä" ;
  green_ADeg = mkADeg (regN "vihreä") "vihreämpi" "vihrein" ;
  harbour_N = reg3N "satama" "sataman" "satamia" ;
  hate_V2 = dirV2 (regV "vihata") ;
  hat_N = regN "hattu" ;
  have_V2 = dirV2 (regV "omistaa") ; ---- olla
  hear_V2 = dirV2 (regV "kuulla") ;
  hill_N = regN "kukkula" ;
----  hope_VS = mkVS (regV "toivoa") ;
  horse_N = regN "hevonen" ;
  hot_ADeg = mkADeg (regN "kuuma") "kuumempi" "kuumin" ;
  house_N = regN "talo" ;
  important_ADeg = mkADeg (regN "tärkeä") "tärkeämpi" "tärkein" ;
  industry_N = regN "teollisuus" ;
  iron_N = regN "rauta" ;
  king_N = regN "kuningas" ;
  know_V2 = dirV2 (reg2V "tietää" "tiesi") ; --- tuntea; gives tietänyt
  lake_N = reg2N "järvi" "järviä" ;
  lamp_N = regN "lamppu" ;
  learn_V2 = 
    dirV2 (mkV "oppia" "oppii" "opin" "oppivat" "oppikaa" "opitaan"
      "oppi" "opin" "oppisi" "oppinut" "opittu" "opitun") ;
  leather_N = regN "nahka" ; --- nahan
  leave_V2 = dirV2 (regV "jättää") ;
  like_V2 = caseV2 (regV "pitää") elative ;
--3  listen_V2 = caseV2 (reg3V "kuunnella" "kuuntelen" "kuuntelin") partitive ;
  live_V = regV "elää" ;
  long_ADeg = mkADeg (regN "pitkä") "pitempi" "pisin" ;
  lose_V2 = dirV2 (regV "hävitä") ; --- hukata
  love_N = reg3N "rakkaus" "rakkauden" "rakkauksia" ;
  love_V2 = caseV2 (regV "rakastaa") partitive ;
  man_N = mkN "mies" "miehen" "miehenä" "miestä" "mieheen" 
            "miehinä" "miehissä" "miesten" "miehiä" "miehiin" human ;
----  married_A2 = mkA2 (regA "married") "to" ;
  meat_N = regN "liha" ;
  milk_N = regN "maito" ;
  moon_N = regN "kuu" ;
----  mother_N2 = regN2 "äiti" ;
  mountain_N = reg2N "vuori" "vuoria" ;
  music_N = regN "musiikki" ;
  narrow_ADeg = mkADeg (regN "kapea") "kapeampi" "kapein" ;
  new_ADeg = mkADeg (reg3N "uusi" "uuden" "uusia") "uudempi" "uusin" ;
  newspaper_N = nSylki "sanomalehti" ; --- for correct vowel harmony
  oil_N = regN "öljy" ;
  old_ADeg = mkADeg (regN "vanha") "vanhempi" "vanhin" ;
  open_V2 = dirV2 (regV "avata") ;
----  paint_V2A = mkV2A (regV "maalata") [] ;
--3  paper_N = reg3N "paperi" "paperin" "papereita" ;
  peace_N = regN "rauha" ;
  pen_N = regN "kynä" ;
  planet_N = regN "planeetta" ;
  plastic_N = regN "muovi" ;
  play_V2 = dirV2 (regV "pelata") ; --- leikkiä, soittaa
  policeman_N = regN "poliisi" ;
  priest_N = regN "pappi" ;
----  probable_AS = mkAS (mkA (nNainen "todennäköistä")) ; --- for vowel harmony
----  queen_N = regN "kuningatar" ;
--3  radio_N = reg3N "radio" "radion" "radioita" ;
----  rain_V0 = mkV0 (vHuoltaa "sataa" "sadan" "satoi" "sadoin") ;
  read_V2 = dirV2 (regV "lukea") ;
  red_ADeg = regADeg "punainen" ;
  religion_N = regN "uskonto" ;
  restaurant_N = regN "ravintola" ;
----  river_N = reg3N "joki" "joen" "jokia" ;
----  rock_N = regN "kallio" ;
  roof_N = regN "katto" ;
  rubber_N = regN "kumi" ;
  run_V = reg2V "juosta" "juoksi" ;
----  say_VS = mkVS (regV "sanoa") ;
  school_N = regN "koulu" ;
  science_N = regN "tiede" ;
  sea_N = reg2N "meri" "meriä" ;
  seek_V2 = dirV2 (regV "etsiä") ;
----  see_V2 = dirV2 (irregV "see" "saw" "seen") ;
----  sell_V3 = dirV3 (regV "myydä") allative ;
----  send_V3 = dirV3 (regV "lähettää") allative ;
  sheep_N = regN "lammas" ;
  ship_N = regN "laiva" ;
  shirt_N = regN "paita" ;
  shoe_N = regN "kenkä" ;
  shop_N = regN "kauppa" ;
  short_ADeg = regADeg "lyhyt" ;
  silver_N = regN "hopea" ;
  sister_N = regN "sisko" ;
  sleep_V = regV "nukkua" ;
----  small_ADeg = regADeg "small" ;
  snake_N = regN "käärme" ;
  sock_N = regN "sukka" ;
  speak_V2 = dirV2 (regV "puhua") ;
  star_N = reg2N "tähti" "tähtiä" ;
----  steel_N = regN "teräs" ;
  stone_N = reg2N "kivi" "kiviä" ;
  stove_N = reg3N "liesi" "lieden" "liesiä" ;
  student_N = reg2N "opiskelija" "opiskelijoita" ;
  stupid_ADeg = regADeg "tyhmä" ;
  sun_N = regN "aurinko" ;
  switch8off_V2 = dirV2 (regV "sammuttaa") ; ---
  switch8on_V2 = dirV2 (regV "sytyttää") ; ---
  table_N = regN "pöytä" ;
----  talk_V3 = mkV3 (regV "puhua") allative elative ;
  teacher_N = regN "opettaja" ;
  teach_V2 = dirV2 (regV "opettaa") ;
--3  television_N = reg2N "televisio" "telievisioita" ;
  thick_ADeg = regADeg "paksu" ;
  thin_ADeg = regADeg "ohut" ;
  train_N = regN "juna" ;
  travel_V = regV "matkustaa" ;
  tree_N = regN "puu" ;
 ---- trousers_N = regN "trousers" ;
  ugly_ADeg = mkADeg (regN "ruma") "rumempi" "rumin" ;
  understand_V2 = dirV2 (reg3V "ymmärtää" "ymmärrän" "ymmärsin") ;
  university_N = regN "yliopisto" ;
  village_N = regN "kylä" ;
  wait_V2 = caseV2 (regV "odottaa") partitive ;
  walk_V = (regV "kävellä") ;
----  warm_ADeg = regADeg "warm" ;
  war_N = regN "sota" ;
  watch_V2 = dirV2 (regV "katsella") ;
  water_N = reg3N "vesi" "veden" "vesiä" ;
  white_ADeg = regADeg "valkoinen" ;
  window_N = reg2N "ikkuna" "ikkunoita" ;
  wine_N = regN "viini" ;
  win_V2 = dirV2 (regV "voittaa") ;
  woman_N = regN "nainen" ;
--3  wonder_VQ = mkVQ (regV "ihmetellä") ;
  wood_N = regN "puu" ;
  write_V2 = dirV2 (regV "kirjoittaa") ;
  yellow_ADeg = regADeg "keltainen" ;
  young_ADeg = mkADeg (reg2N "nuori" "nuoria") "nuorempi" "nuorin" ;

----  do_V2 = dirV2 (mkV "do" "does" "did" "done" "doing") ;
  now_Adv = mkAdv "nyt" ;
  already_Adv = mkAdv "jo" ;
  song_N = regN "laulu" ;
----  add_V3 = dirV3 (regV "lisätä") illative ;
  number_N = reg2N "numero" "numeroita" ;
  put_V2 = dirV2 (regV "panna") ;
  stop_V = regV "pysähtyä" ;
  jump_V = regV "hypätä" ;
  here_Adv = mkAdv "täällä" ;
  here7to_Adv = mkAdv "tänne" ;
  here7from_Adv = mkAdv "täältä" ;
  there_Adv = mkAdv "siellä" ; --- tuolla
  there7to_Adv = mkAdv "sinne" ;
  there7from_Adv = mkAdv "sieltä" ;

} ;
