--# -path=.:../abstract:../../prelude
--# -val

concrete BasicFin of Basic = CategoriesFin ** open ParadigmsFin in {

flags 
  startcat=Phr ; lexer=textlit ; unlexer=text ;
  optimize=values ;

lin

  airplane_N = regN "lentokone" ;
----  answer_V2S = mkV2S (regV "answer") "to" ;
  apartment_N = reg3N "asunto" "asunnon" "asuntoja" ;
  apple_N = reg3N "omena" "omenan" "omenoita" ;
  art_N = reg3N "taide" "taiteen" "taiteita" ;
----  ask_V2Q = mkV2Q (regV "ask") [] ;
  baby_N = regN "vauva" ;
  bad_ADeg = mkADeg (regN "paha") "pahempi" "pahin" ;
  bank_N = reg3N "pankki" "pankin" "pankkeja" ;
  beautiful_ADeg = mkADeg (regN "kaunis") "kauniimpi" "kaunein" ;
----  become_VA = mkVA (irregV "become" "became" "become") ;
  beer_N = reg3N "olut" "oluen" "oluita" ;
----  beg_V2V = mkV2V (regDuplV "beg") [] "to" ;
  big_ADeg = mkADeg (reg3N "suuri" "suuren" "suuria") "suurempi" "suurin" ;
  bike_N = nLukko "polkupyörä" ; --- for correct vowel harmony
  bird_N = reg3N "lintu" "linnun" "lintuja" ;
  black_ADeg = mkADeg (reg3N "musta" "mustan" "mustia") "mustempi" "mustin" ;
  blue_ADeg = mkADeg (regN "sininen") "sinisempi" "sinisin" ;
  boat_N = regN "vene" ;
  book_N = regN "kirja" ;
  boot_N = reg3N "saapas" "saappaan" "saappaita" ;
  boss_N = regN "pomo" ;
  boy_N = reg3N "poika" "pojan" "poikia" ;
  bread_N = reg3N "leipä" "leivän" "leipiä" ;
  break_V2 = dirV2 (reg3V "rikkoa" "rikon" "rikoin") ;
  broad_ADeg = mkADeg (regN "leveä") "leveämpi" "levein" ;
----  brother_N2 = regN2 "brother" ;
  brown_ADeg = mkADeg (regN "ruskea") "ruskeampi" "ruskein" ;
  butter_N = reg3N "voi" "voin" "voita" ;
  buy_V2 = dirV2 (regV "ostaa") ;
  camera_N = regN "kamera" ;
  cap_N = reg3N "lakki" "lakin" "lakkeja" ;
  car_N = regN "auto" ;
  carpet_N = reg3N "matto" "maton" "mattoja" ;
  cat_N = regN "kissa" ;
  ceiling_N = reg3N "katto" "katon" "kattoja" ;
  chair_N = regN "tuoli" ;
  cheese_N = regN "juusto" ;
  child_N = mkN "lapsi" "lapsen" "lapsena" "lasta" "lapseen" 
            "lapsina" "lapsissa" "lasten" "lapsia" "lapsiin" human ;
  church_N = reg3N "kirkko" "kirkon" "kirkkoja" ;
  city_N = reg3N "kaupunki" "kaupungin" "kaupunkeja" ;
  clean_ADeg = mkADeg (reg3N "puhdas" "puhtaan" "puhtaita") "puhtaampi" "puhtain" ;
  clever_ADeg = mkADeg (reg3N "viisas" "viisaan" "viisaita") "viisaampi" "viisain" ;
  close_V2 = dirV2 (reg3V "sulkea" "suljen" "sulki") ;
  coat_N = reg3N "takki" "takin" "takkeja" ;
  cold_ADeg = mkADeg (regN "kylmä") "kylmempi" "kylmin" ;
  come_V = regV "tulla" ;
  computer_N = regN "tietokone" ;
  country_N = regN "maa" ;
  cousin_N = reg3N "serkku" "serkun" "serkkuja" ;
  cow_N = regN "lehmä" ;
  die_V = regV "kuolla" ;
  dirty_ADeg = mkADeg (regN "likainen") "likaisempi" "likaisin" ;
----  distance_N3 = mkN3 (regN "distance") "from" "to" ;
  doctor_N = reg3N "tohtori" "tohtorin" "tohtoreita" ;
  dog_N = reg3N "koira" "koiran" "koiria" ;
  door_N = reg3N "ovi" "oven" "ovia" ;
  drink_V2 = dirV2 (regV "juoda") ;
----  easy_A2V = mkA2V (regA "easy") "for" ;
  eat_V2 = dirV2 (regV "syödä") ;
  empty_ADeg = mkADeg (regN "tyhjä") "tyhjempi" "tyhjin" ;
  enemy_N = regN "vihollinen" ;
  factory_N = reg3N "tehdas" "tehtaan" "tehtaiden" ;
----  father_N2 = regN2 "father" ;
----  fear_VS = mkVS (reg3V "pelätä" "pelkään" "pelkäsi") ;
  find_V2 = dirV2 (reg3V "löytää" "löydän" "löysin") ;
  fish_N = regN "kala" ;
  floor_N = reg3N "lattia" "lattian" "lattioita" ;
  forget_V2 = dirV2 (reg3V "unohtaa" "unohdan" "unohdin") ;
  fridge_N = reg3N "jääkaappi" "jääkaapin" "jääkaappeja" ;
  friend_N = regN "ystävä" ;
  fruit_N = regN "hedelmä" ;
----  fun_AV = mkAV (regA "fun") ;
  garden_N = regN "puutarha" ;
  girl_N = reg3N "tyttö" "tytön" "tyttöjä" ;
  glove_N = reg3N "käsine" "käsineen" "käsineitä" ;
  gold_N = reg3N "kulta" "kullan" "kultia" ;
  good_ADeg = mkADeg (regN "hyvä") "parempi" "parhain" ; --- paras
  go_V = regV "mennä" ;
  green_ADeg = mkADeg (regN "vihreä") "vihreämpi" "vihrein" ;
  harbour_N = reg3N "satama" "sataman" "satamia" ;
  hate_V2 = dirV2 (regV "vihata") ;
  hat_N = reg3N "hattu" "hatun" "hattuja" ;
  have_V2 = dirV2 (regV "omistaa") ; ---- olla
  hear_V2 = dirV2 (regV "kuulla") ;
  hill_N = regN "kukkula" ;
----  hope_VS = mkVS (regV "toivoa") ;
  horse_N = regN "hevonen" ;
  hot_ADeg = mkADeg (reg3N "kuuma" "kuuman" "kuumia") "kuumempi" "kuumin" ;
  house_N = regN "talo" ;
  important_ADeg = mkADeg (regN "tärkeä") "tärkeämpi" "tärkein" ;
  industry_N = regN "teollisuus" ;
  iron_N = reg3N "rauta" "raudan" "rautoja" ;
  king_N = reg3N "kuningas" "kuninkaan" "kuninkaita" ;
  know_V2 = dirV2 (reg3V "tietää" "tiedän" "tiesin") ; ---- tuntea
  lake_N = reg3N "järvi" "järven" "järviä" ;
  lamp_N = reg3N "lamppu" "lampun" "lamppuja" ;
  learn_V2 = 
    dirV2 (mkV "oppia" "oppii" "opin" "oppivat" "oppikaa" "opitaan"
      "oppi" "opin" "oppisi" "oppinut" "opittu" "opitun") ;
  leather_N = reg3N "nahka" "nahan" "nahkoja" ;
  leave_V2 = dirV2 (reg3V "jättää" "jätän" "jätin") ;
  like_V2 = caseV2 (reg3V "pitää" "pidän" "pidin") elative ;
  listen_V2 = caseV2 (reg3V "kuunnella" "kuuntelen" "kuuntelin") partitive ;
  live_V = regV "elää" ;
  long_ADeg = mkADeg (regN "pitkä") "pitempi" "pisin" ;
  lose_V2 = dirV2 (regV "hävitä") ; --- hukata
  love_N = reg3N "rakkaus" "rakkauden" "rakkauksia" ;
  love_V2 = caseV2 (regV "rakastaa") partitive ;
  man_N = mkN "mies" "miehen" "miehenä" "miestä" "mieheen" 
            "miehinä" "miehissä" "miesten" "miehiä" "miehiin" human ;
----  married_A2 = mkA2 (regA "married") "to" ;
  meat_N = regN "liha" ;
  milk_N = regN "maito" ;
  moon_N = regN "kuu" ;
----  mother_N2 = regN2 "äiti" ;
  mountain_N = reg3N "vuori" "vuoren" "vuoria" ;
  music_N = regN "musiikki" ;
  narrow_ADeg = mkADeg (regN "kapea") "kapeampi" "kapein" ;
  new_ADeg = mkADeg (reg3N "uusi" "uuden" "uusia") "uudempi" "uusin" ;
  newspaper_N = nSylki "sanomalehti" ; --- for correct vowel harmony
{-
  oil_N = regN "oil" ;
  old_ADeg = regADeg "old" ;
  open_V2 = dirV2 (regV "open") ;
  paint_V2A = mkV2A (regV "paint") [] ;
  paper_N = regN "paper" ;
  peace_N = regN "peace" ;
  pen_N = regN "pen" ;
  planet_N = regN "planet" ;
  plastic_N = regN "plastic" ;
  play_V2 = dirV2 (regV "play") ;
  policeman_N = regN "policeman" ;
  priest_N = regN "priest" ;
  probable_AS = mkAS (regA "probable") ;
  queen_N = regN "queen" ;
  radio_N = regN "radio" ;
  rain_V0 = mkV0 (regV "rain") ;
  read_V2 = dirV2 (irregV "read" "read" "read") ;
  red_ADeg = regADeg "red" ;
  religion_N = regN "religion" ;
  restaurant_N = regN "restaurant" ;
  river_N = regN "river" ;
  rock_N = regN "rock" ;
  roof_N = regN "roof" ;
  rubber_N = regN "rubber" ;
  run_V = (irregDuplV "run" "ran" "run") ;
  say_VS = mkVS (irregV "say" "said" "said") ;
  school_N = regN "school" ;
  science_N = regN "science" ;
  sea_N = regN "sea" ;
  seek_V2 = dirV2 (irregV "seek" "sought" "sought") ;
  see_V2 = dirV2 (irregV "see" "saw" "seen") ;
  sell_V3 = dirV3 (irregV "sell" "sold" "sold") "to" ;
  send_V3 = dirV3 (irregV "send" "sent" "sent") "to" ;
  sheep_N = mk2N "sheep" "sheep" ;
  ship_N = regN "ship" ;
  shirt_N = regN "shirt" ;
  shoe_N = regN "shoe" ;
  shop_N = regN "shop" ;
  short_ADeg = regADeg "short" ;
  silver_N = regN "silver" ;
-}
  sister_N = regN "sisko" ;
  sleep_V = regV "uinua" ;
{-
  small_ADeg = regADeg "small" ;
  snake_N = regN "snake" ;
  sock_N = regN "sock" ;
  speak_V2 = dirV2 (irregV "speak" "spoke" "spoken") ;
  star_N = regN "star" ;
  steel_N = regN "steel" ;
  stone_N = regN "stone" ;
  stove_N = regN "stove" ;
  student_N = regN "student" ;
  stupid_ADeg = regADeg "stupid" ;
  sun_N = regN "sun" ;
  switch8off_V2 = dirV2 (partV (regV "switch") "off") ;
  switch8on_V2 = dirV2 (partV (regV "switch") "on") ;
  table_N = regN "table" ;
  talk_V3 = mkV3 (regV "talk") "to" "about" ;
  teacher_N = regN "teacher" ;
  teach_V2 = dirV2 (irregV "teach" "taught" "taught") ;
  television_N = regN "television" ;
  thick_ADeg = regADeg "thick" ;
  thin_ADeg = regADeg "thin" ;
  train_N = regN "train" ;
  travel_V = (regDuplV "travel") ;
  tree_N = regN "tree" ;
 ---- trousers_N = regN "trousers" ;
  ugly_ADeg = regADeg "ugly" ;
  understand_V2 = dirV2 (irregV "understand" "understood" "understood") ;
  university_N = regN "university" ;
  village_N = regN "village" ;
  wait_V2 = mkV2 (regV "wait") "for" ;
  walk_V = (regV "walk") ;
  warm_ADeg = regADeg "warm" ;
  war_N = regN "war" ;
  watch_V2 = dirV2 (regV "watch") ;
  water_N = regN "water" ;
  white_ADeg = regADeg "white" ;
  window_N = regN "window" ;
  wine_N = regN "wine" ;
  win_V2 = dirV2 (irregV "win" "won" "won") ;
  woman_N = mk2N "woman" "women" ;
  wonder_VQ = mkVQ (regV "wonder") ;
  wood_N = regN "wood" ;
  write_V2 = dirV2 (irregV "write" "wrote" "written") ;
  yellow_ADeg = regADeg "yellow" ;
  young_ADeg = regADeg "young" ;

  do_V2 = dirV2 (mkV "do" "does" "did" "done" "doing") ;
  now_Adv = mkAdv "now" ;
  already_Adv = mkAdv "already" ;
  song_N = regN "song" ;
  add_V3 = dirV3 (regV "add") "to" ;
  number_N = regN "number" ;
  put_V2 = mkV2 (irregDuplV "put" "put" "put") [] ;
  stop_V = regDuplV "stop" ;
  jump_V = regV "jump" ;
  here_Adv = mkAdv "here" ;
  here7to_Adv = mkAdv "here" ;
  here7from_Adv = mkAdv ["from here"] ;
  there_Adv = mkAdv "there" ;
  there7to_Adv = mkAdv "there" ;
  there7from_Adv = mkAdv ["from there"] ;
-}

} ;
