--# -path=.:../romance:../common:../abstract:../../prelude

-- Irregular verbs from Nancy, based on a list from Sylvain Pogodalla, 25/11/2004
-- Translated to GF by Aarne Ranta
-- added extracted subcat information 29/11

concrete IrregFre of IrregFreAbs = CatFre ** 
  open DiffFre, MorphoFre, BeschFre, Prelude in {

  flags optimize=values ;
    coding=utf8 ;

-- all verbs in classes with "er" and "finir" are omitted

lin 
  abattre_V2 = v_besch55 "abattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  absoudre_V2 = v_besch72 "absoudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  abstenir_V = v_besch23 "abstenir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  abstraire_V2 = v_besch61 "abstraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  accourir_V = v_besch33 "accourir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  accroître_V2 = v_besch73 "accroître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  accueillir_V2 = v_besch28 "accueillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  acquérir_V2 = v_besch24 "acquérir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  adjoindre_V2 = v_besch58 "adjoindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  admettre_V2 = v_besch56 "admettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  advenir_V = v_besch23 "advenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  aller_V = v_besch22 "aller" ** {vtyp = VTyp VEsse VTrue ; p = [] ; lock_V = <>} ;
  apercevoir_V2 = v_besch38 "apercevoir" ** {vtyp = VTyp VRefl VFalse ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  apparaître_V = v_besch64 "apparaître" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  appartenir_V2 = v_besch23 "appartenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  appendre_V2 = v_besch53 "appendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  apprendre_V2 = v_besch54 "apprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  assaillir_V2 = v_besch29 "assaillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  asseoir_V2 = v_besch49 "asseoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  astreindre_V2 = v_besch57 "astreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  atteindre_V2 = v_besch57 "atteindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  attendre_V2 = v_besch53 "attendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ; --- Dat?
  avoir_V2 = v_besch1 "avoir" ** {vtyp = VTyp VHabere VTrue ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  battre_V2 = v_besch55 "battre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  boire_V2 = v_besch69 "boire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  bouillir_V2 = v_besch31 "bouillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  braire_V = v_besch61 "braire" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  ceindre_V2 = v_besch57 "ceindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  choir_V = v_besch52 "choir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  circonscrire_V2 = v_besch80 "circonscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  circonvenir_V2 = v_besch23 "circonvenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  clore_V2 = v_besch70 "clore" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  combattre_V2 = v_besch55 "combattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  commettre_V2 = v_besch56 "commettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  comparaître_V2 = v_besch64 "comparaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  complaire_V2 = v_besch63 "complaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  comprendre_V2 = v_besch54 "comprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  compromettre_V2 = v_besch56 "compromettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  concevoir_V2 = v_besch38 "concevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  conclure_V2 = v_besch71 "conclure" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  concourir_V2 = v_besch33 "concourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  condescendre_V2 = v_besch53 "condescendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  conduire_V2 = v_besch82 "conduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  confire_V2 = v_besch81 "confire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  confondre_V2 = v_besch53 "confondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  conjoindre_V2 = v_besch58 "conjoindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  connaître_V2 = v_besch64 "connaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  conquérir_V2 = v_besch24 "conquérir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  consentir_V2 = v_besch25 "consentir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  construire_V2 = v_besch82 "construire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contenir_V2 = v_besch23 "contenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contraindre_V2 = v_besch59 "contraindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contrebattre_V2 = v_besch55 "contrebattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contredire_V2 = v_besch78 "contredire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contrefaire_V2 = v_besch62 "contrefaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  contrevenir_V2 = v_besch23 "contrevenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  convaincre_V2 = v_besch60 "convaincre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  convenir_V2 = v_besch23 "convenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  correspondre_V2 = v_besch53 "correspondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  corrompre_V2 = v_besch53 "corrompre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  coudre_V2 = v_besch73 "coudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  courir_V2 = v_besch33 "courir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  couvrir_V2 = v_besch27 "couvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  craindre_V2 = v_besch59 "craindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  croire_V2 = v_besch68 "croire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  croître_V = v_besch67 "croître" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  cueillir_V2 = v_besch28 "cueillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  cuire_V2 = v_besch82 "cuire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  débattre_V2 = v_besch55 "débattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  débouillir_V2 = v_besch31 "débouillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  décevoir_V2 = v_besch38 "décevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déchoir_V2 = v_besch52 "déchoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déclore_V2 = v_besch70 "déclore" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  décommettre_V2 = v_besch56 "décommettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déconfire_V2 = v_besch81 "déconfire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  découdre_V2 = v_besch73 "découdre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  découvrir_V2 = v_besch27 "découvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  décrire_V2 = v_besch80 "décrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  décroître_V2 = v_besch67 "décroître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  décuire_V2 = v_besch82 "décuire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déduire_V2 = v_besch82 "déduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  défaillir_V = v_besch30 "défaillir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  défaire_V2 = v_besch62 "défaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  défendre_V2 = v_besch53 "défendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  démentir_V2 = v_besch25 "démentir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  démettre_V2 = v_besch56 "démettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  démordre_V = v_besch53 "démordre" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  départir_V2 = v_besch25 "départir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  dépeindre_V2 = v_besch57 "dépeindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  dépendre_V2 = v_besch53 "dépendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  déplaire_V = v_besch63 "déplaire" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  dépourvoir_V2 = v_besch40 "dépourvoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déprendre_V2 = v_besch54 "déprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  désapprendre_V2 = v_besch54 "désapprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  descendre_V2 = v_besch53 "descendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  desservir_V2 = v_besch35 "desservir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  déteindre_V2 = v_besch57 "déteindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  détendre_V2 = v_besch53 "détendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  détenir_V2 = v_besch23 "détenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  détordre_V2 = v_besch53 "détordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  détruire_V2 = v_besch82 "détruire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  devenir_V = v_besch23 "devenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  dévêtir_V2 = v_besch26 "dévêtir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  devoir_V2 = v_besch42 "devoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  dire_V2 = v_besch78 "dire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  disconvenir_V2 = v_besch23 "disconvenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  discourir_V2 = v_besch33 "discourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  disjoindre_V2 = v_besch58 "disjoindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  disparaître_V2 = v_besch64 "disparaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  dissoudre_V2 = v_besch72 "dissoudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  distendre_V2 = v_besch53 "distendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  distordre_V2 = v_besch53 "distordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  distraire_V2 = v_besch61 "distraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  dormir_V2 = v_besch32 "dormir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  ébattre_V = v_besch55 "ébattre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  échoir_V2 = v_besch52 "échoir" ** {vtyp = vEsse ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  éclore_V2 = v_besch70 "éclore" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  éconduire_V2 = v_besch82 "éconduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  écrire_V2 = v_besch80 "écrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  élire_V2 = v_besch77 "élire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  embatre_V2 = v_besch55 "embatre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  embattre_V2 = v_besch55 "embattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  emboire_V = v_besch69 "emboire" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  émettre_V2 = v_besch56 "émettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  émoudre_V2 = v_besch74 "émoudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  émouvoir_V2 = v_besch44 "émouvoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  empreindre_V2 = v_besch57 "empreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  enceindre_V2 = v_besch57 "enceindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  enclore_V2 = v_besch70 "enclore" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  encourir_V2 = v_besch33 "encourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  endormir_V2 = v_besch32 "endormir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  enduire_V2 = v_besch82 "enduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  enfreindre_V2 = v_besch57 "enfreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  enfuir_V = v_besch36 "enfuir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  enjoindre_V2 = v_besch58 "enjoindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  enquérir_V = v_besch24 "enquérir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entendre_V2 = v_besch53 "entendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  entr'apercevoir_V = v_besch38 "entr'apercevoir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entrebattre_V = v_besch55 "entrebattre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entre_détruire_V = v_besch82 "entre-détruire" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entre_haïr_V = v_besch20 "entre-haïr" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entremettre_V = v_besch56 "entremettre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  entre_nuire_V = v_besch82 "entre-nuire" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  entreprendre_V2 = v_besch54 "entreprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  entretenir_V2 = v_besch23 "entretenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  entrevoir_V2 = v_besch39 "entrevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  entrouvrir_V2 = v_besch27 "entrouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  envoyer_V2 = v_besch18 "envoyer" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  épandre_V2 = v_besch53 "épandre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  éperdre_V = v_besch53 "éperdre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  éprendre_V = v_besch54 "éprendre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  équivaloir_V2 = v_besch47 "équivaloir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  éteindre_V2 = v_besch57 "éteindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  étendre_V2 = v_besch53 "étendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  étreindre_V2 = v_besch57 "étreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  être_V = v_besch2 "être" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  exclure_V2 = v_besch71 "exclure" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  extraire_V2 = v_besch61 "extraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  faillir_V2 = v_besch30 "faillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  faire_V2 = v_besch62 "faire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  falloir_V = v_besch46 "falloir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  feindre_V2 = v_besch57 "feindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  fendre_V2 = v_besch53 "fendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  fondre_V2 = v_besch53 "fondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  forfaire_V2 = v_besch62 "forfaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  foutre_V2 = v_besch53 "foutre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  frire_V2 = v_besch81 "frire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  fuir_V2 = v_besch36 "fuir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  geindre_V2 = v_besch57 "geindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  gésir_V2 = mkNV (conj3gésir "gésir") ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  haïr_V2 = v_besch20 "haïr" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  inclure_V2 = v_besch71 "inclure" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  induire_V2 = v_besch82 "induire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  inscrire_V2 = v_besch80 "inscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  instruire_V2 = v_besch82 "instruire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  interdire_V2 = v_besch78 "interdire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  interrompre_V2 = v_besch53 "interrompre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  intervenir_V = v_besch23 "intervenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  introduire_V2 = v_besch82 "introduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  joindre_V2 = v_besch58 "joindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  lire_V2 = v_besch77 "lire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  luire_V = v_besch82 "luire" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  mainmettre_V2 = v_besch56 "mainmettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  maintenir_V2 = v_besch23 "maintenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  méconnaître_V2 = v_besch64 "méconnaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  mécroire_V2 = v_besch68 "mécroire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  médire_V2 = v_besch78 "médire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  mentir_V2 = v_besch25 "mentir" ** {vtyp = vEsse ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  méprendre_V2 = v_besch54 "méprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  messeoir_V2 = v_besch50 "messeoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  mettre_V2 = v_besch56 "mettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  mévendre_V2 = v_besch53 "mévendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  mordre_V2 = v_besch53 "mordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  morfondre_V = v_besch53 "morfondre" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  moudre_V2 = v_besch74 "moudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  mourir_V = v_besch34 "mourir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  mouvoir_V2 = v_besch44 "mouvoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  naître_V = v_besch65 "naître" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  nuire_V2 = v_besch82 "nuire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  obtenir_V2 = v_besch23 "obtenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  obvenir_V = v_besch23 "obvenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  occlure_V2 = v_besch71 "occlure" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  offrir_V2 = v_besch27 "offrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  oindre_V2 = v_besch58 "oindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  omettre_V2 = v_besch56 "omettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  ouïr_V2 = v_besch37 "ouïr" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  ouvrir_V2 = v_besch27 "ouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  paître_V2 = v_besch66 "paître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  paître_V = v_besch66 "paître" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  paraître_V = v_besch64 "paraître" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  parcourir_V2 = v_besch33 "parcourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  parfondre_V2 = v_besch53 "parfondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  partir_V = v_besch25 "partir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  parvenir_V = v_besch23 "parvenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  peindre_V2 = v_besch57 "peindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  pendre_V2 = v_besch53 "pendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  percevoir_V2 = v_besch38 "percevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  perdre_V2 = v_besch53 "perdre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  permettre_V2 = v_besch56 "permettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  plaindre_V2 = v_besch59 "plaindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  plaire_V2 = v_besch63 "plaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  pleuvoir_V = v_besch45 "pleuvoir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  poindre_V2 = v_besch58 "poindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  pondre_V2 = v_besch53 "pondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  pourfendre_V2 = v_besch53 "pourfendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  poursuivre_V2 = v_besch75 "poursuivre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  pourvoir_V2 = v_besch40 "pourvoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  pouvoir_V = v_besch43 "pouvoir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  prédire_V2 = v_besch78 "prédire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  prendre_V2 = v_besch54 "prendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  prescrire_V2 = v_besch80 "prescrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  pressentir_V2 = v_besch25 "pressentir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  prétendre_V2 = v_besch53 "prétendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  prévaloir_V2 = v_besch47 "prévaloir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  prévenir_V2 = v_besch23 "prévenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  prévoir_V2 = v_besch39 "prévoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  produire_V2 = v_besch82 "produire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  promettre_V2 = v_besch56 "promettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  promouvoir_V2 = v_besch44 "promouvoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  proscrire_V2 = v_besch80 "proscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  provenir_V = v_besch23 "provenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  rabattre_V2 = v_besch55 "rabattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  raire_V2 = v_besch61 "raire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rapprendre_V2 = v_besch54 "rapprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rasseoir_V2 = v_besch49 "rasseoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réadmettre_V2 = v_besch56 "réadmettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réapparaître_V = v_besch64 "réapparaître" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  réapprendre_V2 = v_besch54 "réapprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rebattre_V2 = v_besch55 "rebattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recevoir_V2 = v_besch38 "recevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recomparaître_V2 = v_besch64 "recomparaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reconduire_V2 = v_besch82 "reconduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reconnaître_V2 = v_besch64 "reconnaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reconquérir_V2 = v_besch24 "reconquérir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reconstruire_V2 = v_besch82 "reconstruire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recoudre_V2 = v_besch73 "recoudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recourir_V2 = v_besch33 "recourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  recouvrir_V2 = v_besch27 "recouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  récrire_V2 = v_besch80 "récrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recroître_V2 = v_besch67 "recroître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recueillir_V2 = v_besch28 "recueillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  recuire_V2 = v_besch82 "recuire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  redécouvrir_V2 = v_besch27 "redécouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  redéfaire_V2 = v_besch62 "redéfaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  redescendre_V2 = v_besch53 "redescendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  redevenir_V = v_besch23 "redevenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  redevoir_V2 = v_besch42 "redevoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  redire_V2 = v_besch78 "redire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réduire_V2 = v_besch82 "réduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  réécrire_V2 = v_besch80 "réécrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réélire_V2 = v_besch77 "réélire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réentendre_V2 = v_besch53 "réentendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  refaire_V2 = v_besch62 "refaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  refendre_V2 = v_besch53 "refendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  refondre_V2 = v_besch53 "refondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réinscrire_V2 = v_besch80 "réinscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  réintroduire_V2 = v_besch82 "réintroduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rejoindre_V2 = v_besch58 "rejoindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  relire_V2 = v_besch77 "relire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reluire_V2 = v_besch82 "reluire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  remettre_V2 = v_besch56 "remettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  remordre_V2 = v_besch53 "remordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  remoudre_V2 = v_besch74 "remoudre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  renaître_V2 = v_besch65 "renaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rendormir_V2 = v_besch32 "rendormir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rendre_V2 = v_besch53 "rendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rentraire_V2 = v_besch61 "rentraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rentrouvrir_V2 = v_besch27 "rentrouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  renvoyer_V2 = v_besch18 "renvoyer" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  repaître_V2 = v_besch66 "repaître" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  répandre_V2 = v_besch53 "répandre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reparaître_V = v_besch64 "reparaître" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  repartir_V = v_besch25 "repartir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  repeindre_V2 = v_besch57 "repeindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rependre_V2 = v_besch53 "rependre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  repentir_V = v_besch25 "repentir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  reperdre_V2 = v_besch53 "reperdre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  repleuvoir_V = v_besch45 "repleuvoir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  répondre_V2 = v_besch53 "répondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reprendre_V2 = v_besch54 "reprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reproduire_V2 = v_besch82 "reproduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  requérir_V2 = v_besch24 "requérir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  résoudre_V2 =  mkNV (conj3résoudre "résoudre") ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  ressentir_V2 = v_besch25 "ressentir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  resservir_V2 = v_besch35 "resservir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  ressortir_V = v_besch25 "ressortir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  ressouvenir_V = v_besch23 "ressouvenir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  restreindre_V2 = v_besch57 "restreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  reteindre_V2 = v_besch57 "reteindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retendre_V2 = v_besch53 "retendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retenir_V2 = v_besch23 "retenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retondre_V2 = v_besch53 "retondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retordre_V2 = v_besch53 "retordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retraduire_V2 = v_besch82 "retraduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retraire_V2 = v_besch61 "retraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retranscrire_V2 = v_besch80 "retranscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  retransmettre_V2 = v_besch56 "retransmettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rétreindre_V2 = v_besch57 "rétreindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revaloir_V2 = v_besch47 "revaloir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revendre_V2 = v_besch53 "revendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revenir_V = v_besch23 "revenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  revêtir_V2 = v_besch26 "revêtir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revivre_V2 = v_besch76 "revivre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revoir_V2 = v_besch39 "revoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  revouloir_V2 = v_besch48 "revouloir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rire_V2 = v_besch79 "rire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complGen} ;
  rompre_V2 = v_besch53 "rompre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  rouvrir_V2 = v_besch27 "rouvrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  saillir_V2 = v_besch29 "saillir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  satisfaire_V2 = v_besch62 "satisfaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  savoir_V2 = v_besch41 "savoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  secourir_V2 = v_besch33 "secourir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  séduire_V2 = v_besch82 "séduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  sentir_V2 = v_besch25 "sentir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  seoir_V = v_besch50 "seoir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  servir_V2 = v_besch35 "servir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  sortir_V = v_besch25 "sortir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  soubattre_V2 = v_besch55 "soubattre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  souffrir_V2 = v_besch27 "souffrir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  soumettre_V2 = v_besch56 "soumettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  sourire_V2 = v_besch79 "sourire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  souscrire_V2 = v_besch80 "souscrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  sous_entendre_V2 = v_besch53 "sous-entendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  sous_tendre_V2 = v_besch53 "sous-tendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  soustraire_V2 = v_besch61 "soustraire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  soutenir_V2 = v_besch23 "soutenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  souvenir_V = v_besch23 "souvenir" ** {vtyp = vHabere ; p = [] ; lock_V = <> ; c2 = complAcc} ;
  subvenir_V2 = v_besch23 "subvenir" ** {vtyp = vEsse ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  suffire_V2 = v_besch81 "suffire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  suivre_V2 = v_besch75 "suivre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  surfaire_V2 = v_besch62 "surfaire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  surprendre_V2 = v_besch54 "surprendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  surproduire_V2 = v_besch82 "surproduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  surseoir_V2 = v_besch51 "surseoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  surtondre_V2 = v_besch53 "surtondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  survenir_V = v_besch23 "survenir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  survivre_V2 = v_besch76 "survivre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  suspendre_V2 = v_besch53 "suspendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  taire_V2 = v_besch63 "taire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  teindre_V2 = v_besch57 "teindre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  tendre_V2 = v_besch53 "tendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  tenir_V2 = v_besch23 "tenir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complDat} ;
  tondre_V2 = v_besch53 "tondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  tordre_V2 = v_besch53 "tordre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  traduire_V2 = v_besch82 "traduire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  traire_V2 = v_besch61 "traire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  transcrire_V2 = v_besch80 "transcrire" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  transmettre_V2 = v_besch56 "transmettre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  transparaître_V = v_besch64 "transparaître" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  tréfondre_V2 = v_besch53 "tréfondre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  tressaillir_V = v_besch29 "tressaillir" ** {vtyp = vHabere ; p = [] ; lock_V = <>} ;
  vaincre_V2 = v_besch60 "vaincre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  valoir_V2 = v_besch47 "valoir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  vendre_V2 = v_besch53 "vendre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  venir_V = v_besch23 "venir" ** {vtyp = vEsse ; p = [] ; lock_V = <>} ;
  vêtir_V2 = v_besch26 "vêtir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  vivre_V2 = v_besch76 "vivre" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  voir_V2 = v_besch39 "voir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;
  vouloir_V2 = v_besch48 "vouloir" ** {vtyp = vHabere ; p = [] ; lock_V2 = <> ; c2 = complAcc} ;

oper
  vHabere = VTyp VHabere VFalse ;
  vEsse = VTyp VEsse VFalse ;

lin
  abattre_V = lin V abattre_V2 ;
  absoudre_V = lin V absoudre_V2 ;
  abstraire_V = lin V abstraire_V2 ;
  accroître_V = lin V accroître_V2 ;
  accueillir_V = lin V accueillir_V2 ;
  acquérir_V = lin V acquérir_V2 ;
  adjoindre_V = lin V adjoindre_V2 ;
  admettre_V = lin V admettre_V2 ;
  apercevoir_V = lin V apercevoir_V2 ;
  appartenir_V = lin V appartenir_V2 ;
  appendre_V = lin V appendre_V2 ;
  apprendre_V = lin V apprendre_V2 ;
  assaillir_V = lin V assaillir_V2 ;
  asseoir_V = lin V asseoir_V2 ;
  astreindre_V = lin V astreindre_V2 ;
  atteindre_V = lin V atteindre_V2 ;
  attendre_V = lin V attendre_V2 ;
  avoir_V = lin V avoir_V2 ;
  battre_V = lin V battre_V2 ;
  boire_V = lin V boire_V2 ;
  bouillir_V = lin V bouillir_V2 ;
  ceindre_V = lin V ceindre_V2 ;
  circonscrire_V = lin V circonscrire_V2 ;
  circonvenir_V = lin V circonvenir_V2 ;
  clore_V = lin V clore_V2 ;
  combattre_V = lin V combattre_V2 ;
  commettre_V = lin V commettre_V2 ;
  comparaître_V = lin V comparaître_V2 ;
  complaire_V = lin V complaire_V2 ;
  comprendre_V = lin V comprendre_V2 ;
  compromettre_V = lin V compromettre_V2 ;
  concevoir_V = lin V concevoir_V2 ;
  conclure_V = lin V conclure_V2 ;
  concourir_V = lin V concourir_V2 ;
  condescendre_V = lin V condescendre_V2 ;
  conduire_V = lin V conduire_V2 ;
  confire_V = lin V confire_V2 ;
  confondre_V = lin V confondre_V2 ;
  conjoindre_V = lin V conjoindre_V2 ;
  connaître_V = lin V connaître_V2 ;
  conquérir_V = lin V conquérir_V2 ;
  consentir_V = lin V consentir_V2 ;
  construire_V = lin V construire_V2 ;
  contenir_V = lin V contenir_V2 ;
  contraindre_V = lin V contraindre_V2 ;
  contrebattre_V = lin V contrebattre_V2 ;
  contredire_V = lin V contredire_V2 ;
  contrefaire_V = lin V contrefaire_V2 ;
  contrevenir_V = lin V contrevenir_V2 ;
  convaincre_V = lin V convaincre_V2 ;
  convenir_V = lin V convenir_V2 ;
  correspondre_V = lin V correspondre_V2 ;
  corrompre_V = lin V corrompre_V2 ;
  coudre_V = lin V coudre_V2 ;
  courir_V = lin V courir_V2 ;
  couvrir_V = lin V couvrir_V2 ;
  craindre_V = lin V craindre_V2 ;
  croire_V = lin V croire_V2 ;
  cueillir_V = lin V cueillir_V2 ;
  cuire_V = lin V cuire_V2 ;
  débattre_V = lin V débattre_V2 ;
  débouillir_V = lin V débouillir_V2 ;
  décevoir_V = lin V décevoir_V2 ;
  déchoir_V = lin V déchoir_V2 ;
  déclore_V = lin V déclore_V2 ;
  décommettre_V = lin V décommettre_V2 ;
  déconfire_V = lin V déconfire_V2 ;
  découdre_V = lin V découdre_V2 ;
  découvrir_V = lin V découvrir_V2 ;
  décrire_V = lin V décrire_V2 ;
  décroître_V = lin V décroître_V2 ;
  décuire_V = lin V décuire_V2 ;
  déduire_V = lin V déduire_V2 ;
  défaire_V = lin V défaire_V2 ;
  défendre_V = lin V défendre_V2 ;
  démentir_V = lin V démentir_V2 ;
  démettre_V = lin V démettre_V2 ;
  départir_V = lin V départir_V2 ;
  dépeindre_V = lin V dépeindre_V2 ;
  dépendre_V = lin V dépendre_V2 ;
  dépourvoir_V = lin V dépourvoir_V2 ;
  déprendre_V = lin V déprendre_V2 ;
  désapprendre_V = lin V désapprendre_V2 ;
  descendre_V = lin V descendre_V2 ;
  desservir_V = lin V desservir_V2 ;
  déteindre_V = lin V déteindre_V2 ;
  détendre_V = lin V détendre_V2 ;
  détenir_V = lin V détenir_V2 ;
  détordre_V = lin V détordre_V2 ;
  détruire_V = lin V détruire_V2 ;
  dévêtir_V = lin V dévêtir_V2 ;
  devoir_V = lin V devoir_V2 ;
  dire_V = lin V dire_V2 ;
  disconvenir_V = lin V disconvenir_V2 ;
  discourir_V = lin V discourir_V2 ;
  disjoindre_V = lin V disjoindre_V2 ;
  disparaître_V = lin V disparaître_V2 ;
  dissoudre_V = lin V dissoudre_V2 ;
  distendre_V = lin V distendre_V2 ;
  distordre_V = lin V distordre_V2 ;
  distraire_V = lin V distraire_V2 ;
  dormir_V = lin V dormir_V2 ;
  échoir_V = lin V échoir_V2 ;
  éclore_V = lin V éclore_V2 ;
  éconduire_V = lin V éconduire_V2 ;
  écrire_V = lin V écrire_V2 ;
  élire_V = lin V élire_V2 ;
  embatre_V = lin V embatre_V2 ;
  embattre_V = lin V embattre_V2 ;
  émettre_V = lin V émettre_V2 ;
  émoudre_V = lin V émoudre_V2 ;
  émouvoir_V = lin V émouvoir_V2 ;
  empreindre_V = lin V empreindre_V2 ;
  enceindre_V = lin V enceindre_V2 ;
  enclore_V = lin V enclore_V2 ;
  encourir_V = lin V encourir_V2 ;
  endormir_V = lin V endormir_V2 ;
  enduire_V = lin V enduire_V2 ;
  enfreindre_V = lin V enfreindre_V2 ;
  enjoindre_V = lin V enjoindre_V2 ;
  entendre_V = lin V entendre_V2 ;
  entreprendre_V = lin V entreprendre_V2 ;
  entretenir_V = lin V entretenir_V2 ;
  entrevoir_V = lin V entrevoir_V2 ;
  entrouvrir_V = lin V entrouvrir_V2 ;
  envoyer_V = lin V envoyer_V2 ;
  épandre_V = lin V épandre_V2 ;
  équivaloir_V = lin V équivaloir_V2 ;
  éteindre_V = lin V éteindre_V2 ;
  étendre_V = lin V étendre_V2 ;
  étreindre_V = lin V étreindre_V2 ;
  exclure_V = lin V exclure_V2 ;
  extraire_V = lin V extraire_V2 ;
  faillir_V = lin V faillir_V2 ;
  faire_V = lin V faire_V2 ;
  feindre_V = lin V feindre_V2 ;
  fendre_V = lin V fendre_V2 ;
  fondre_V = lin V fondre_V2 ;
  forfaire_V = lin V forfaire_V2 ;
  foutre_V = lin V foutre_V2 ;
  frire_V = lin V frire_V2 ;
  fuir_V = lin V fuir_V2 ;
  geindre_V = lin V geindre_V2 ;
  gésir_V = lin V gésir_V2 ;
  haïr_V = lin V haïr_V2 ;
  inclure_V = lin V inclure_V2 ;
  induire_V = lin V induire_V2 ;
  inscrire_V = lin V inscrire_V2 ;
  instruire_V = lin V instruire_V2 ;
  interdire_V = lin V interdire_V2 ;
  interrompre_V = lin V interrompre_V2 ;
  introduire_V = lin V introduire_V2 ;
  joindre_V = lin V joindre_V2 ;
  lire_V = lin V lire_V2 ;
  mainmettre_V = lin V mainmettre_V2 ;
  maintenir_V = lin V maintenir_V2 ;
  méconnaître_V = lin V méconnaître_V2 ;
  mécroire_V = lin V mécroire_V2 ;
  médire_V = lin V médire_V2 ;
  mentir_V = lin V mentir_V2 ;
  méprendre_V = lin V méprendre_V2 ;
  messeoir_V = lin V messeoir_V2 ;
  mettre_V = lin V mettre_V2 ;
  mévendre_V = lin V mévendre_V2 ;
  mordre_V = lin V mordre_V2 ;
  moudre_V = lin V moudre_V2 ;
  mouvoir_V = lin V mouvoir_V2 ;
  nuire_V = lin V nuire_V2 ;
  obtenir_V = lin V obtenir_V2 ;
  occlure_V = lin V occlure_V2 ;
  offrir_V = lin V offrir_V2 ;
  oindre_V = lin V oindre_V2 ;
  omettre_V = lin V omettre_V2 ;
  ouïr_V = lin V ouïr_V2 ;
  ouvrir_V = lin V ouvrir_V2 ;
  parcourir_V = lin V parcourir_V2 ;
  parfondre_V = lin V parfondre_V2 ;
  peindre_V = lin V peindre_V2 ;
  pendre_V = lin V pendre_V2 ;
  percevoir_V = lin V percevoir_V2 ;
  perdre_V = lin V perdre_V2 ;
  permettre_V = lin V permettre_V2 ;
  plaindre_V = lin V plaindre_V2 ;
  plaire_V = lin V plaire_V2 ;
  poindre_V = lin V poindre_V2 ;
  pondre_V = lin V pondre_V2 ;
  pourfendre_V = lin V pourfendre_V2 ;
  poursuivre_V = lin V poursuivre_V2 ;
  pourvoir_V = lin V pourvoir_V2 ;
  prédire_V = lin V prédire_V2 ;
  prendre_V = lin V prendre_V2 ;
  prescrire_V = lin V prescrire_V2 ;
  pressentir_V = lin V pressentir_V2 ;
  prétendre_V = lin V prétendre_V2 ;
  prévaloir_V = lin V prévaloir_V2 ;
  prévenir_V = lin V prévenir_V2 ;
  prévoir_V = lin V prévoir_V2 ;
  produire_V = lin V produire_V2 ;
  promettre_V = lin V promettre_V2 ;
  promouvoir_V = lin V promouvoir_V2 ;
  proscrire_V = lin V proscrire_V2 ;
  rabattre_V = lin V rabattre_V2 ;
  raire_V = lin V raire_V2 ;
  rapprendre_V = lin V rapprendre_V2 ;
  rasseoir_V = lin V rasseoir_V2 ;
  réadmettre_V = lin V réadmettre_V2 ;
  réapprendre_V = lin V réapprendre_V2 ;
  rebattre_V = lin V rebattre_V2 ;
  recevoir_V = lin V recevoir_V2 ;
  recomparaître_V = lin V recomparaître_V2 ;
  reconduire_V = lin V reconduire_V2 ;
  reconnaître_V = lin V reconnaître_V2 ;
  reconquérir_V = lin V reconquérir_V2 ;
  reconstruire_V = lin V reconstruire_V2 ;
  recoudre_V = lin V recoudre_V2 ;
  recourir_V = lin V recourir_V2 ;
  recouvrir_V = lin V recouvrir_V2 ;
  récrire_V = lin V récrire_V2 ;
  recroître_V = lin V recroître_V2 ;
  recueillir_V = lin V recueillir_V2 ;
  recuire_V = lin V recuire_V2 ;
  redécouvrir_V = lin V redécouvrir_V2 ;
  redéfaire_V = lin V redéfaire_V2 ;
  redescendre_V = lin V redescendre_V2 ;
  redevoir_V = lin V redevoir_V2 ;
  redire_V = lin V redire_V2 ;
  réduire_V = lin V réduire_V2 ;
  réécrire_V = lin V réécrire_V2 ;
  réélire_V = lin V réélire_V2 ;
  réentendre_V = lin V réentendre_V2 ;
  refaire_V = lin V refaire_V2 ;
  refendre_V = lin V refendre_V2 ;
  refondre_V = lin V refondre_V2 ;
  réinscrire_V = lin V réinscrire_V2 ;
  réintroduire_V = lin V réintroduire_V2 ;
  rejoindre_V = lin V rejoindre_V2 ;
  relire_V = lin V relire_V2 ;
  reluire_V = lin V reluire_V2 ;
  remettre_V = lin V remettre_V2 ;
  remordre_V = lin V remordre_V2 ;
  remoudre_V = lin V remoudre_V2 ;
  renaître_V = lin V renaître_V2 ;
  rendormir_V = lin V rendormir_V2 ;
  rendre_V = lin V rendre_V2 ;
  rentraire_V = lin V rentraire_V2 ;
  rentrouvrir_V = lin V rentrouvrir_V2 ;
  renvoyer_V = lin V renvoyer_V2 ;
  repaître_V = lin V repaître_V2 ;
  répandre_V = lin V répandre_V2 ;
  repeindre_V = lin V repeindre_V2 ;
  rependre_V = lin V rependre_V2 ;
  reperdre_V = lin V reperdre_V2 ;
  répondre_V = lin V répondre_V2 ;
  reprendre_V = lin V reprendre_V2 ;
  reproduire_V = lin V reproduire_V2 ;
  requérir_V = lin V requérir_V2 ;
  résoudre_V = lin V résoudre_V2 ;
  ressentir_V = lin V ressentir_V2 ;
  resservir_V = lin V resservir_V2 ;
  restreindre_V = lin V restreindre_V2 ;
  reteindre_V = lin V reteindre_V2 ;
  retendre_V = lin V retendre_V2 ;
  retenir_V = lin V retenir_V2 ;
  retondre_V = lin V retondre_V2 ;
  retordre_V = lin V retordre_V2 ;
  retraduire_V = lin V retraduire_V2 ;
  retraire_V = lin V retraire_V2 ;
  retranscrire_V = lin V retranscrire_V2 ;
  retransmettre_V = lin V retransmettre_V2 ;
  rétreindre_V = lin V rétreindre_V2 ;
  revaloir_V = lin V revaloir_V2 ;
  revendre_V = lin V revendre_V2 ;
  revêtir_V = lin V revêtir_V2 ;
  revivre_V = lin V revivre_V2 ;
  revoir_V = lin V revoir_V2 ;
  revouloir_V = lin V revouloir_V2 ;
  rire_V = lin V rire_V2 ;
  rompre_V = lin V rompre_V2 ;
  rouvrir_V = lin V rouvrir_V2 ;
  saillir_V = lin V saillir_V2 ;
  satisfaire_V = lin V satisfaire_V2 ;
  savoir_V = lin V savoir_V2 ;
  secourir_V = lin V secourir_V2 ;
  séduire_V = lin V séduire_V2 ;
  sentir_V = lin V sentir_V2 ;
  servir_V = lin V servir_V2 ;
  soubattre_V = lin V soubattre_V2 ;
  souffrir_V = lin V souffrir_V2 ;
  soumettre_V = lin V soumettre_V2 ;
  sourire_V = lin V sourire_V2 ;
  souscrire_V = lin V souscrire_V2 ;
  sous_entendre_V = lin V sous_entendre_V2 ;
  sous_tendre_V = lin V sous_tendre_V2 ;
  soustraire_V = lin V soustraire_V2 ;
  soutenir_V = lin V soutenir_V2 ;
  subvenir_V = lin V subvenir_V2 ;
  suffire_V = lin V suffire_V2 ;
  suivre_V = lin V suivre_V2 ;
  surfaire_V = lin V surfaire_V2 ;
  surprendre_V = lin V surprendre_V2 ;
  surproduire_V = lin V surproduire_V2 ;
  surseoir_V = lin V surseoir_V2 ;
  surtondre_V = lin V surtondre_V2 ;
  survivre_V = lin V survivre_V2 ;
  suspendre_V = lin V suspendre_V2 ;
  taire_V = lin V taire_V2 ;
  teindre_V = lin V teindre_V2 ;
  tendre_V = lin V tendre_V2 ;
  tenir_V = lin V tenir_V2 ;
  tondre_V = lin V tondre_V2 ;
  tordre_V = lin V tordre_V2 ;
  traduire_V = lin V traduire_V2 ;
  traire_V = lin V traire_V2 ;
  transcrire_V = lin V transcrire_V2 ;
  transmettre_V = lin V transmettre_V2 ;
  tréfondre_V = lin V tréfondre_V2 ;
  vaincre_V = lin V vaincre_V2 ;
  valoir_V = lin V valoir_V2 ;
  vendre_V = lin V vendre_V2 ;
  vêtir_V = lin V vêtir_V2 ;
  vivre_V = lin V vivre_V2 ;
  voir_V = lin V voir_V2 ;
  vouloir_V = lin V vouloir_V2 ;

}
