--# -path=.:../scandinavian:../abstract:../../prelude

concrete BasicNor of Basic = CategoriesNor ** open ParadigmsNor in {

flags startcat=Phr ; lexer=textlit ; parser=chart ; unlexer=text ;
  optimize=values ;

--- rough-translated from Swedish by AR 11/3/2005. To be fixed soon.

lin
  airplane_N = regN "flygplan" neutrum ;
  answer_V2S = mkV2S (regV "svare") "til" ;
  apartment_N = mk2N "legenhet" "legenheten" ;
  apple_N = regN "epple" neutrum ;
  art_N = mk2N "konst" "konsten" ;
  ask_V2Q = mkV2Q (regV "fråge") [] ;
  baby_N = regN "bebis" masculine ;
  bad_ADeg = irregADeg "dålig" "semre" "semst";
  bank_N = mk2N "bank" "banken" ;
  beautiful_ADeg = mk3ADeg "vakker" "vakkert" "vakkrast" ;
  become_VA = mkVA (mkV "bli" "blir""bli" "blev" "blivit" "bliven") ;
  beer_N = regN "øl" neutrum ;
  beg_V2V = mkV2V (mkV "be" "ber""be" "blad" "bett" "bedd") [] "att" ;
  big_ADeg = irregADeg "stor" "større" "størst";
  bike_N = mk2N "cykel" "cyklar" ;
  bird_N = mk2N "fågel" "fåglar" ;
  black_ADeg = mk2ADeg "svart" "svart" ;
  blue_ADeg = mk2ADeg "blå" "blått";
  boat_N = regN "båt" masculine ;
  book_N = mkN "bok" "boken" "bøkker" "bøkkerne" ;
  boot_N = mk2N "støvel" "støvlar" ;
  boss_N = mk2N "chef" "chefen" ;
  boy_N = regN "pojke" feminine ;
  bread_N = regN "brød" neutrum ;
  break_V2 = dirV2 (partV (mkV "slå" "slår" "slå" "slog" "slagit" "slagen") "sønder") ;
  broad_ADeg = mk2ADeg "bred" "brett" ;
  brother_N2 = mkN2 ( (mkN "bror" "brodern" "brøder" "brøderne")) "til" ;
  brown_ADeg = regADeg "brun" ;
  butter_N = regN "smør" neutrum ;
  buy_V2 = dirV2 (mk2V "køpe" "køpte") ;
  camera_N = regN "kamere" feminine ;
  cap_N = regN "møsse" feminine ;
  car_N = regN "bil" masculine ;
  carpet_N = regN "matte" feminine ;
  cat_N = mk2N "katt" "katten" ;
  ceiling_N = regN "tak" neutrum ;
  chair_N = regN "stol" masculine ;
  cheese_N = regN "ost" masculine ;
  child_N = regN "barn" neutrum ;
  church_N = regN "kyrke" feminine ;
  city_N = mk2N "stad" "steden" ;
  clean_ADeg = regADeg "ren" ;
  clever_ADeg = regADeg "klok" ;
  close_V2 = dirV2 (mk2V "stenge" "stengde") ;
  coat_N = regN "rokk" masculine ;
  cold_ADeg = regADeg "kall" ;
  come_V = (mkV "komme" "kommer" "kom" "kom" "kommit" "kommen") ;
  computer_N = mk2N "dator" "datoren" ;
  country_N = mkN "land" "landet" "lender" "lenderne" ;
  cousin_N = mk2N "kusin" "kusinerne" ;
  cow_N = mk2N "ko" "kor" ;
  die_V = (mkV "dø" "dør" "dø" "dog" "døtt" "dødd") ; ----
  dirty_ADeg = regADeg "smutsig" ;
  doctor_N = mk2N "lekare" "lekare" ;
  dog_N = regN "hund" masculine ;
  door_N = regN "dørr" masculine ;
  drink_V2 = dirV2 (irregV "drikke" "drakk" "drukket") ;
  easy_A2V = mkA2V (mk2A "lett" "lett") "før" ;
  eat_V2 = dirV2 (mk2V "spise" "spste") ;
  enemy_N = regN "fiende" neutrum ;
  factory_N = mk2N "fabrik" "fabriken" ;
  father_N2 = mkN2 ( (mkN "far" "fadern" "feder" "federne")) "til" ;
  fear_VS = mkVS (regV "frukte") ;
  find_V2 = dirV2 (irregV "finne" "fann" "funnet") ;
  fish_N = mk2N "fisk" "fiskar" ;
  floor_N = regN "golv" neutrum ;
  forget_V2 = dirV2 (mkV "glømme" "glømmer" "gløm" "glømde" "glømt" "glømd") ;
  fridge_N = regN "kylskåp" neutrum ;
  friend_N = mkN "ven" "vennen" "venner" "vennerne" ;
  fruit_N = mk2N "frukt" "frukten" ;
  fun_AV = mkAV (regA "rolig") ;
  garden_N = regN "tredgård" masculine ;
  girl_N = regN "flikke" feminine ;
  glove_N = regN "handske" feminine ;
  gold_N = regN "guld" neutrum ;
  good_ADeg = mkADeg "god" "gott" "gode" "bettre" "best" ;
  go_V = (mkV "gå" "går" "gå" "gikk" "gått" "gången") ;
  green_ADeg = regADeg "grøn" ;
  harbour_N = regN "hamn" masculine;
  hate_V2 = dirV2 (regV "hate") ;
  hat_N = regN "hatt" masculine ;
  have_V2 = dirV2 (mkV "he" "har" "he" "hade" "haft" "haft") ; ---- pp
  hear_V2 = dirV2 (mkV "høre" "hør" "hør" "hørde" "hørt" "hørd") ;
  hill_N = regN "kulle" feminine ;
  hope_VS = mkVS (depV (regV "hoppas")) ;
  horse_N = regN "hest" masculine ;
  hot_ADeg = regADeg "het" ;
  house_N = regN "hus" neutrum ;
  important_ADeg = regADeg "viktig" ;
  industry_N = mk2N "industri" "industrien" ; ---- "ien" ??
  iron_N = regN "jern" neutrum ;
  king_N =  (regN "kung" masculine) ;
  know_V2 = dirV2 (mkV "vete" "vet" "vet" "visste" "vetat" "visst") ;
  lake_N = mkN "sjø" "sjøn" "sjøar" "sjøarne" ;
  lamp_N = regN "lampe" feminine;
  learn_V2 = dirV2 (mkV "lere" "ler" "ler" "lerde" "lert" "lerd") ; ---- refl!
  leather_N = mkN "leder" "ledret" "leder" "ledren" ;
  leave_V2 = dirV2 (regV "lemne") ;
  like_V2 = mkV2 (mk2V "tykke" "tykkte") "om" ;
  listen_V2 = mkV2 (regV "lyssne") "på" ;
  live_V = (irregV "leve" "levde" "levt") ; ---- ?
  long_ADeg = irregADeg "lång" "lengre" "lengst" ;
  lose_V2 = dirV2 (regV "førlore") ;
  love_N = regN "kerlek" masculine ;
  love_V2 = dirV2 (regV "elske") ;
  man_N =  (mkN "man" "mannen" "men" "mennen") ;
  married_A2 = mkA2 (mk2A "gift" "gift") "med" ;
  meat_N = regN "køtt" neutrum ;
  milk_N = regN "mjølk" masculine ; ---- -ar?
  moon_N = regN "måne" masculine ;
  mother_N2 = mkN2 (mkN "mor" "modern" "mødrar" "mødrarne") "til" ;
  mountain_N = regN "berg" neutrum ;
  music_N = mk2N "musik" "musiken" ; ---- er ?
  narrow_ADeg = regADeg "smal" ;
  new_ADeg = mkADeg "ny" "nytt" "nye" "nyere" "nyest" ;
  newspaper_N = regN "tidning" masculine ;

  oil_N = regN "olje" feminine ;
  old_ADeg = mkADeg "gammel" "gammelt" "gamle" "eldre" "eldst" ;
  open_V2 = dirV2 (regV "øppne") ;
  paint_V2A = mkV2A (regV "måle") [] ;
  paper_N = mkN "papper" "pappret" "papper" "pappren" ;
  peace_N = regN "fred" masculine ; ---- ar?
  pen_N = regN "penne" feminine ;
  planet_N = mk2N "planet" "planeten" ;
  plastic_N = mk2N "plastic" "plastiken" ;
  play_V2 = dirV2 (regV "spele") ;
  policeman_N = mk2N "polis" "polisen" ;
  priest_N = mk2N "prest" "presten" ;
  probable_AS = mkAS (regA "sannolik") ;
  queen_N = regN "drottning" masculine ;
  radio_N = regN "radio" masculine ; ----
  rain_V0 = mkV0 (regV "regne") ;
  read_V2 = dirV2 (mk2V "lese" "leste") ;
  red_ADeg = mk2ADeg "rød" "røtt" ;
  religion_N = mk2N "religion" "religionen" ;
  restaurant_N = mk2N "restaurang" "restaurangen" ;
  river_N = mkN "å" "ån" "åar" "åarne" ;
  rock_N = regN "sten" masculine ;
  roof_N = regN "tak" neutrum ;
  rubber_N = mkN "gummi" "gummit" "gummin" "gummine" ;
  run_V = (irregV "springe" "sprang" "sprunget") ;
  say_VS = mkVS (mkV "sie" "sier" "sies" "sa" "sagd" "si") ;
  school_N = regN "skole" feminine;
  science_N = mk2N "vetenskap" "vetenskapen" ;
  sea_N = mkN "sjø" "sjøn" "sjøar" "sjøarne" ;
  seek_V2 = dirV2 (mk2V "søke" "søkte") ;
  see_V2 = dirV2 (mkV "se" "ser" "se" "såg" "sett" "sedd") ;
  sell_V3 = dirV3 (irregV "selje" "sålde" "sålt") "til" ;
  send_V3 = dirV3 (regV "skikke") "til" ;
  sheep_N = mk2N "får" "får" ;
  ship_N = regN "skepp" neutrum ;
  shirt_N = regN "skjorte" feminine ;
  shoe_N = regN "sko" masculine ;
  shop_N = mk2N "affer" "afferen" ;
  short_ADeg = regADeg "kort" ;
  silver_N = mkN "silver" "silvret" "silver" "silvren" ;
  sister_N = mk2N "syster" "systrar" ;
  sleep_V = (irregV "sove" "sov" "sovet") ;
  small_ADeg = mkADeg "lite" "lite" "lille" "mindre" "minst" ;
  snake_N = regN "orm" masculine ;
  sock_N = regN "strumpe" feminine ;
  speak_V2 = dirV2 (regV "tale") ;
  star_N = regN "stjerne" feminine ;
  steel_N = regN "stål" masculine ;
  stone_N = regN "sten" masculine ;
  stove_N = regN "spis" masculine ;
  student_N = mk2N "student" "studenten" ;
  stupid_ADeg = mk3ADeg "dum" "dumt" "dumme" ;
  sun_N = regN "sol" masculine ;
  switch8off_V2 = dirV2 (partV (irregV "stenge" "stengde" "stengt") "av") ;
  switch8on_V2 = dirV2 (partV (irregV "slå" "slog" "slaget") "på") ;
  table_N = regN "bord" neutrum ;
  talk_V3 = mkV3 (regV "prate") "til" "om" ;
  teacher_N = mk2N "lerare" "lerare" ;
  teach_V2 = dirV2 (regV "undervise") ;
  television_N = mk2N "television" "televisionen" ;
  thick_ADeg = regADeg "tjokk" ;
  thin_ADeg = mk2ADeg "tunn" "tunt" ;
  train_N = regN "tåg" neutrum ;
  travel_V = mk2V "rese" "reste" ;
  tree_N = regN "tred" neutrum ;
  ----  trousers_N = regN "trousers" ; ---- pl t !
  ugly_ADeg = regADeg "ful" ;
  understand_V2 = dirV2 (mkV "førstå" "førstår" "førstå" "førstod" "førstått" "førstådd") ;
  university_N = regN "universitet" neutrum ;
  village_N = mkN "by" "byn" "byar" "byarne" ;
  wait_V2 = mkV2 (regV "vente") "på" ;
  walk_V = (mkV "gå" "går" "gå" "gikk" "gått" "gången") ;
  warm_ADeg = regADeg "varm" ;
  war_N = regN "krig" neutrum ;
  watch_V2 = mkV2 (regV "titte") "på" ;
  water_N = mkN "vatten" "vattnet" "vatten" "vattnen" ;
  white_ADeg = regADeg "vet" ;
  window_N = mkN "fønster" "fønstret" "fønster" "fønstren" ;
  wine_N = mkN "vin" "vinet" "viner" "vinerne" ; ----
  win_V2 = dirV2 (irregV "vinne" "vann" "vunnet") ;
  woman_N = regN "kvinne" feminine ;
  wonder_VQ = mkVQ (regV "undre") ;
  wood_N = mkN "tre" "treet" "treen" "treene" ; ---- ?
  write_V2 = dirV2 (irregV "skrive" "skrev" "skrivet") ;
  yellow_ADeg = regADeg "gul" ;
  young_ADeg = irregADeg "ung" "yngre" "yngst" ;

  do_V2 = dirV2 (mkV "gøre" "gør" "gør" "gjorde" "gjort" "gjord") ;
  now_Adv = mkAdv "nå" ;
  already_Adv = mkAdv "allerede" ;
  song_N = mk2N "sång" "sången" ;
  add_V3 = mkV3 (partV (irregV "legge" "lade" "lagt") "til") [] "til" ;
  number_N = mkN "nummer" "numret" "numren" "numren" ;
  put_V2 = mkV2 (irregV "sette" "satte" "satt") [] ;
  stop_V = regV "stanne" ;
  jump_V = regV "hoppe" ;
  here_Adv = mkAdv "her" ;
  here7to_Adv = mkAdv "hit" ;
  here7from_Adv = mkAdv ["herfra"] ;
  there_Adv = mkAdv "der" ;
  there7to_Adv = mkAdv "dit" ;
  there7from_Adv = mkAdv ["derfra"] ;

} ;

-- a" -> e"   86
-- ö  -> ø    66
-- ck -> kk   20
-- ä  -> e    44
