Ara:
	runghc MkTour Ara Arabic

Cat:
	runghc MkTour Cat Catalan

Fin:
	runghc MkTour Fin Finnish

Fre:
	runghc MkTour Fre French

Ger:
	runghc MkTour Ger German

Nor:
	runghc MkTour Nor Norwegian

Rus:
	runghc MkTour Rus Russian

Swe:
	txt2tags -thtml -o tourSwe.html tour.txt 

