--# -path=.:../common:../abstract:../../prelude

concrete BasicGer of Basic = CatGer ** open ParadigmsGer in {

flags 
  optimize=values ;

lin
  airplane_N = regN "Flugzeug"  ;
  answer_V2S = mkV2S (regV "antworten") datPrep ;
  apartment_N = regN "Wohnung" ;
  apple_N = reg2N "Apfel" "Äpfel" masculine  ;
  art_N = reg2N "Kunst" "Künste" feminine ;
  ask_V2Q = mkV2Q (regV "fragen") accPrep ;
  baby_N = reg2N "Baby" "babies" neuter ; ----
  bad_A = regA "schlecht" ;
  bank_N = reg2N "Bank" "Banken" feminine ; ----
  beautiful_A = regA "schön" ;
  become_VA = mkVA (mkV "werden" "wird" "werd" "wurde" "würde" "geworden") ;
  beer_N = reg2N "Bier" "Biere" neuter ;
----  beg_V2V = mkV2V (mkV "be" "ber""be" "blad" "bett" "bedd") [] "att" ;
  big_A = mkA "groß" "groß" "größer""größt" ;
  bike_N = reg2N "Fahrrad" "Fahrräder" neuter ;
----  bird_N = reg2N "fågel" "fåglar" ;
  black_A = regA "schwarz" ;
  blue_A = regA "blau";
  boat_N = reg2N "Boot" "Boote" neuter ;
  book_N = reg2N "Buch" "Bücher" neuter ;
--  boot_N = reg2N "stövel" "stövlar" ;
  boss_N = reg2N "Chef" "Chefe" masculine ; ----
  boy_N = reg2N "Junge" "Jungen" masculine ;
  bread_N = reg2N "Brot" "Brote" neuter ; ----
  break_V2 = dirV2 (prefixV "zer" 
    (irregV "schlagen" "schlägt" "schlug" "schlüge" "geschlagen")) ;
  broad_A = regA "breit" ;
  brother_N2 = mkN2 (reg2N "Bruder" "Brüder" masculine)  zu_Prep ; ----
  brown_A = regA "braun" ;
----  butter_N = regN "smör"  ;
  buy_V2 = dirV2 (regV "kaufen") ;
----  camera_N = regN "kamera" ;
  cap_N = regN "Mütze" ;
  car_N = reg2N "Wagen" "Wagen" masculine ;
  carpet_N = reg2N "Teppich" "Teppiche" masculine ;
  cat_N = regN "Katze" ;
----  ceiling_N = regN "tak"  ;
  chair_N = reg2N "Stuhl" "Stühle" masculine ;
  cheese_N = regN "Käse" ;
  child_N = reg2N "Kind" "Kinder" neuter ;
  church_N = regN "Kirche" ;
  city_N = reg2N "Stadt" "Städte" feminine ;
  clean_A = regA "rein" ;
  clever_A = regA "klug" ; ----
  close_V2 = dirV2 (irregV "schliessen" "schließt" "schloß" "schlöße" "geschlossen") ;
  coat_N = regN "Jacke" ;
  cold_A = regA "Kalt" ;
{-
  come_V = (mkV "komma" "kommer" "kom" "kom" "kommit" "kommen") ;
  computer_N = reg2N "dator" "datorer" ;
  country_N = mkN "land" "landet" "länder" "länderna" ;
  cousin_N = reg2N "kusin" "kusinerna" ;
  cow_N = reg2N "ko" "kor" ;
  die_V = (mkV "dö" "dör" "dö" "dog" "dött" "dödd") ; ----
  distance_N3 = mkN3 (reg2N "avstånd" "avstånd") "från" "till" ;
  dirty_A = regADeg "smutsig" ;
  doctor_N = reg2N "läkare" "läkare" ;
  dog_N = regN "hund" ;
  door_N = regN "dörr" ;
  drink_V2 = dirV2 (irregV "dricka" "drack" "druckit") ;
  easy_A2V = mkA2V (mk2A "lätt" "lätt") "för" ;
  eat_V2 = dirV2 (irregV "äta" "åt" "ätit") ;
  empty_A = mkADeg "tom" "tomt" "tomma" "tomma" "tommare" "tommast" "tommaste" ;
  enemy_N = regN "fiende"  ;
  factory_N = reg2N "fabrik" "fabriker" ;
  father_N2 = mkN2 ((mkN "far" "fadern" "fäder" "fäderna")) "till" ;
  fear_VS = mkVS (regV "frukta") ;
  find_V2 = dirV2 (irregV "finna" "fann" "funnit") ;
  fish_N = reg2N "fisk" "fiskar" ;
  floor_N = regN "golv"  ;
  forget_V2 = dirV2 (mkV "glömma" "glömmer" "glöm" "glömde" "glömt" "glömd") ;
  fridge_N = regN "kylskåp"  ;
  friend_N = mkN "vän" "vännen" "vänner" "vännerna" ;
  fruit_N = reg2N "frukt" "frukter" ;
  fun_AV = mkAV (regA "rolig") ;
  garden_N = regN "trädgård" ;
  girl_N = regN "flicka" ;
  glove_N = regN "handske" ;
  gold_N = regN "guld"  ;
  good_A = mkADeg "god" "gott" "goda" "goda" "bättre" "bäst" "bästa" ;
  go_V = (mkV "gå" "går" "gå" "gick" "gått" "gången") ;
  green_A = regADeg "grön" ;
  harbour_N = regN "hamn";
  hate_V2 = dirV2 (regV "hata") ;
  hat_N = regN "hatt" ;
  have_V2 = dirV2 (mkV "ha" "har" "ha" "hade" "haft" "haft") ; ---- pp
  hear_V2 = dirV2 (mkV "höra" "hör" "hör" "hörde" "hört" "hörd") ;
  hill_N = regN "kulle" ;
  hope_VS = mkVS ((regV "önska")) ;
----  hope_VS = mkVS (depV (regV "hoppas")) ;
  horse_N = regN "häst" ;
  hot_A = regADeg "het" ;
  house_N = regN "hus"  ;
  important_A = regADeg "viktig" ;
  industry_N = reg2N "industri" "industrier" ; ---- "ien" ??
  iron_N = regN "järn"  ;
  king_N = (regN "kung") ;
  know_V2 = dirV2 (mkV "veta" "vet" "vet" "visste" "vetat" "visst") ;
  lake_N = mkN "sjö" "sjön" "sjöar" "sjöarna" ;
  lamp_N = regN "lampa";
  learn_V2 = dirV2 (mkV "lära" "lär" "lär" "lärde" "lärt" "lärd") ; ---- refl!
  leather_N = mkN "läder" "lädret" "läder" "lädren" ;
  leave_V2 = dirV2 (regV "lämna") ;
  like_V2 = mkV2 (mk2V "tycka" "tyckte") "om" ;
  listen_V2 = mkV2 (regV "lyssna") "på" ;
  live_V = (irregV "leva" "levde" "levt") ; ---- ?
  long_A = irregADeg "lång" "längre" "längst" ;
  lose_V2 = dirV2 (regV "förlora") ;
  love_N = regN "kärlek" ;
  love_V2 = dirV2 (regV "älska") ;
  man_N = (mkN "man" "mannen" "män" "männen") ;
  married_A2 = mkA2 (mk2A "gift" "gift") "med" ;
  meat_N = regN "kött"  ;
  milk_N = regN "mjölk" ; ---- -ar?
  moon_N = regN "måne" ;
  mother_N2 = mkN2 (mkN "mor" "modern" "mödrar" "mödrarna") "till" ;
  mountain_N = regN "berg"  ;
  music_N = reg2N "musik" "musiker" ; ---- er ?
  narrow_A = regADeg "smal" ;
  new_A = mkADeg "ny" "nytt" "nya" "nya" "nyare" "nyast" "nyaste" ;
  newspaper_N = regN "tidning" ;

  oil_N = regN "olja" ;
  old_A = mkADeg "gammal" "gammalt" "gamla" "gamla" "äldre" "äldst" "äldsta" ;
  open_V2 = dirV2 (regV "öppna") ;
  paint_V2A = mkV2A (regV "måla") [] ;
  paper_N = mkN "papper" "pappret" "papper" "pappren" ;
  peace_N = regN "fred" ; ---- ar?
  pen_N = regN "penna" ;
  planet_N = reg2N "planet" "planeter" ;
  plastic_N = reg2N "plast" "plaster" ;
  play_V2 = dirV2 (regV "spela") ;
  policeman_N = reg2N "polis" "poliser" ;
  priest_N = reg2N "präst" "präster" ;
  probable_AS = mkAS (regA "sannolik") ;
  queen_N = regN "drottning" ;
  radio_N = regN "radio" ; ----
  rain_V0 = mkV0 (regV "regna") ;
  read_V2 = dirV2 (mk2V "läsa" "läste") ;
  red_A = mk2ADeg "röd" "rött" ;
  religion_N = reg2N "religion" "religioner" ;
  restaurant_N = reg2N "restaurang" "restauranger" ;
  river_N = mkN "å" "ån" "åar" "åarna" ;
  rock_N = regN "sten" ;
  roof_N = regN "tak"  ;
  rubber_N = mkN "gummi" "gummit" "gummin" "gummina" ;
  run_V = (irregV "springa" "sprang" "sprungit") ;
  say_VS = mkVS (mkV "säga" "säger" "säg" "sade" "sagt" "sagd") ;
  school_N = regN "skola";
  science_N = reg2N "vetenskap" "vetenskaper" ;
  sea_N = mkN "sjö" "sjön" "sjöar" "sjöarna" ;
  seek_V2 = dirV2 (mk2V "söka" "sökte") ;
  see_V2 = dirV2 (mkV "se" "ser" "se" "såg" "sett" "sedd") ;
  sell_V3 = dirV3 (irregV "sälja" "sålde" "sålt") "till" ;
  send_V3 = dirV3 (regV "skicka") "till" ;
  sheep_N = reg2N "får" "får" ;
  ship_N = regN "skepp"  ;
  shirt_N = regN "skjorta" ;
  shoe_N = regN "sko" ;
  shop_N = reg2N "affär" "affären" ;
  short_A = regADeg "kort" ;
  silver_N = mkN "silver" "silvret" "silver" "silvren" ;
  sister_N = reg2N "syster" "systrar" ;
  sleep_V = (irregV "sova" "sov" "sovit") ;
  small_A = mkADeg "liten" "litet" "lilla" "små" "mindre" "minst" "minsta" ;
  snake_N = regN "orm" ;
  sock_N = regN "strumpa" ;
  speak_V2 = dirV2 (regV "tala") ;
  star_N = regN "stjärna" ;
  steel_N = regN "stål" ;
  stone_N = regN "sten" ;
  stove_N = regN "spis" ;
  student_N = reg2N "student" "studenter" ;
  stupid_A = mk3ADeg "dum" "dumt" "dumma" ;
  sun_N = regN "sol" ;
  switch8off_V2 = dirV2 (partV (irregV "stänga" "stängde" "stängt") "av") ;
  switch8on_V2 = dirV2 (partV (irregV "slå" "slog" "slagit") "på") ;
  table_N = regN "bord"  ;
  talk_V3 = mkV3 (regV "prata") "till" "om" ;
  teacher_N = reg2N "lärare" "lärare" ;
  teach_V2 = dirV2 (regV "undervisa") ;
  television_N = reg2N "television" "televisioner" ;
  thick_A = regADeg "tjock" ;
  thin_A = mk2ADeg "tunn" "tunt" ;
  train_N = regN "tåg"  ;
  travel_V = mk2V "resa" "reste" ;
  tree_N = regN "träd"  ;
  ----  trousers_N = regN "trousers" ; ---- pl t !
  ugly_A = regADeg "ful" ;
  understand_V2 = dirV2 (mkV "förstå" "förstår" "förstå" "förstod" "förstått" "förstådd") ;
  university_N = regN "universitet"  ;
  village_N = mkN "by" "byn" "byar" "byarna" ;
  wait_V2 = mkV2 (regV "vänta") "på" ;
  walk_V = (mkV "gå" "går" "gå" "gick" "gått" "gången") ;
  warm_A = regADeg "varm" ;
  war_N = regN "krig" ;
  watch_V2 = mkV2 (regV "titta") "på" ;
  water_N = mkN "vatten" "vattnet" "vatten" "vattnen" ;
  white_A = regADeg "vit" ;
  window_N = mkN "fönster" "fönstret" "fönster" "fönstren" ;
  wine_N = mkN "vin" "vinet" "viner" "vinerna" ; ----
  win_V2 = dirV2 (irregV "vinna" "vann" "vunnit") ;
  woman_N = regN "kvinna" ;
  wonder_VQ = mkVQ (regV "undra") ;
  wood_N = mkN "trä" "träet" "träen" "träena" ; ---- ?
  write_V2 = dirV2 (irregV "skriva" "skrev" "skrivit") ;
  yellow_A = regADeg "gul" ;
  young_A = irregADeg "ung" "yngre" "yngst" ;

  do_V2 = dirV2 (mkV "göra" "gör" "gör" "gjorde" "gjort" "gjord") ;
  now_Adv = mkAdv "nu" ;
  already_Adv = mkAdv "redan" ;
  song_N = reg2N "sång" "sånger" ;
  add_V3 = mkV3 (partV (irregV "lägga" "lade" "lagt") "till") [] "till" ;
  number_N = mkN "nummer" "numret" "numren" "numren" ;
  put_V2 = mkV2 (mkV "sätta" "sätter" "sätt" "satte" "satt" "satt") [] ;
  stop_V = regV "stanna" ;
  jump_V = regV "hoppa" ;
-}
} ;
