--# -path=.:../common:../abstract:../../prelude

concrete BasicGer of Basic = CatGer ** open Prelude, ParadigmsGer in {

flags 
  optimize=values ;

lin
  airplane_N = regN "Flugzeug"  ;
  already_Adv = ss "schon" ;
  answer_V2S = mkV2S (regV "antworten") datPrep ;
  apartment_N = regN "Wohnung" ;
  apple_N = reg2N "Apfel" "Äpfel" masculine  ;
  art_N = reg2N "Kunst" "Künste" feminine ;
  ask_V2Q = mkV2Q (regV "fragen") accPrep ;
  baby_N = reg2N "Baby" "babies" neuter ; ----
  bad_A = regA "schlecht" ;
  bank_N = reg2N "Bank" "Banken" feminine ; ----
  beautiful_A = regA "schön" ;
  become_VA = mkVA (mkV "werden" "wird" "werd" "wurde" "würde" "geworden") ;
  beer_N = reg2N "Bier" "Biere" neuter ;
----  beg_V2V = mkV2V (mkV "be" "ber""be" "blad" "bett" "bedd") [] "att" ;
  big_A = mkA "groß" "groß" "größer""größt" ;
  bike_N = reg2N "Fahrrad" "Fahrräder" neuter ;
----  bird_N = reg2N "fågel" "fåglar" ;
  black_A = regA "schwarz" ;
  blue_A = regA "blau";
  boat_N = reg2N "Boot" "Boote" neuter ;
  book_N = reg2N "Buch" "Bücher" neuter ;
--  boot_N = reg2N "stövel" "stövlar" ;
  boss_N = reg2N "Chef" "Chefe" masculine ; ----
  boy_N = reg2N "Junge" "Jungen" masculine ;
  bread_N = reg2N "Brot" "Brote" neuter ; ----
  break_V2 = dirV2 
    (irregV "zerschlagen" "zerschlägt" "zerschlug" "zerschlüge" "zerschlagen") ;
  broad_A = regA "breit" ;
  brother_N2 = mkN2 (reg2N "Bruder" "Brüder" masculine)  zu_Prep ; ----
  brown_A = regA "braun" ;
----  butter_N = regN "smör"  ;
  buy_V2 = dirV2 (regV "kaufen") ;
----  camera_N = regN "kamera" ;
  cap_N = regN "Mütze" ;
  car_N = reg2N "Wagen" "Wagen" masculine ;
  carpet_N = regN "Teppich" ;
  cat_N = regN "Katze" ;
----  ceiling_N = regN "tak"  ;
  chair_N = reg2N "Stuhl" "Stühle" masculine ;
  cheese_N = regN "Käse" ;
  child_N = reg2N "Kind" "Kinder" neuter ;
  church_N = regN "Kirche" ;
  city_N = reg2N "Stadt" "Städte" feminine ;
  clean_A = regA "rein" ;
  clever_A = regA "klug" ; ----
  close_V2 = dirV2 (irregV "schliessen" "schließt" "schloß" "schlöße" "geschlossen") ;
  coat_N = regN "Jacke" ;
  cold_A = regA "Kalt" ;
  come_V = seinV (mkV "kommen" "kommt" "komm" "kam" "käme" "gekommen") ;
  computer_N = reg2N "Rechner" "Rechner" masculine ;
  country_N = reg2N "Land" "Länder" neuter ;
  cousin_N = reg2N "Vetter" "Vetter" masculine ; --- Kusine
  cow_N = reg2N "Kuh" "Kühe" feminine ;
  die_V = seinV (irregV "sterben" "stirbt" "starb" "stärbe" "gestorben") ;
  distance_N3 = mkN3 (regN "Entfernung") von_Prep zu_Prep ;
  dirty_A = regA "schmutzig" ;
  doctor_N = reg2N "Arzt" "Ärzte" masculine ;
  dog_N = regN "Hund" ;
  door_N = reg2N "Tür" "Türe" feminine ;
  drink_V2 = dirV2 (irregV "trinken" "trinkt" "trank" "tränke" "getrunken") ;
  easy_A2V = mkA2V (regA "leicht") (mkPrep "für" accusative) ;
  eat_V2 = dirV2 (irregV "essen" "ißt" "aß" "äße" "gegessen") ;
  empty_A = regA "leer" ; ---- check infl
  enemy_N = regN "Feind" ; ----
  factory_N = regN "Fabrike" ;
  father_N2 = mkN2 (reg2N "Vater" "Väter" masculine) von_Prep ;
  fear_VS = mkVS (regV "fürchten") ;
  find_V2 = dirV2 (irregV "finden" "findet" "fand" "fände" "gefunden") ;
  fish_N = regN "Fisch" ;
  floor_N = reg2N "Fußboden" "Fußböden" masculine ;
  forget_V2 = dirV2 (irregV "vergessen" "vergißt" "vergaß" "vergässe" "vergessen") ;
  fridge_N = reg2N "Kühlschrank" "Kühlschränke" masculine ;
  friend_N = regN "Freund" ;
  fruit_N = reg2N "Frucht" "Früchte" feminine ;
  fun_AV = mkAV (regA "toll") ;
  garden_N = reg2N "Garten" "Gärten" masculine ;
  girl_N = reg2N "Mädchen" "Mädchen" neuter ;
  glove_N = regN "Handschuh" ;
  gold_N = regN "Gold" ; ----
  good_A = mkA "gut" "gut" "besser" "best" ;
  go_V = seinV (irregV "gehen" "geht" "ging" "ginge" "gegangen") ;
  green_A = regA "grün" ;
  harbour_N = reg2N "Hafen" "Häfen" masculine ;
  hate_V2 = dirV2 (regV "Hassen") ;
  hat_N = reg2N "Hut" "Hüte" masculine ;
----  have_V2 = dirV2 (mkV "ha" "har" "ha" "hade" "haft" "haft") ; ---- pp
  hear_V2 = dirV2 (regV "hören") ;
----  hill_N = regN "kulle" ;
  hope_VS = mkVS (regV "hoffen") ;
  horse_N = reg2N "Pferd" "Pferde" neuter ;
  hot_A = regA "heiß" ;
  house_N = reg2N "Haus" "Häuser" neuter ;
  important_A = regA "wichtig" ;
  industry_N = regN "Industrie" ;
  iron_N = reg2N "Eisen" "Eisen" neuter ;
  king_N = regN "König" ;
  know_V2 = dirV2 (irregV "wissen" "weiß" "wußte" "wüßte" "gewußt") ; ---- infl
----  lake_N = mkN "sjö" "sjön" "sjöar" "sjöarna" ;
  lamp_N = regN "Lampe";
  learn_V2 = dirV2 (regV "lernen") ;
----  leather_N = regN "Leder" ;
  leave_V2 = 
    dirV2 (irregV "verlassen" "verläßt" "verließ" "verliesse" "verlassen") ;
  like_V2 = dirV2 (irregV "magen" "mag" "mochte" "möchte" "gemocht") ;
  listen_V2 = mkV2 (prefixV "zu" (regV "hören")) datPrep ; ---- dat
  live_V = regV "leben" ;
  long_A = mkA "lang" "lang" "länger" "längst" ;
  lose_V2 = dirV2 (irregV "verlieren" "verliert" "verlor" "verlöre" "verloren") ;
  love_N = regN "Liebe" ;
  love_V2 = dirV2 (regV "lieben") ;
  man_N = reg2N "Mann" "Männer" masculine ;
  married_A2 = mkA2 (regA "verheiratet") (mkPrep "mit" dative) ;
  meat_N = reg2N "Fleisch" "Fleische" neuter ; ---- Pl
  milk_N = reg2N "Milch" "Milchen" feminine ; ---- Pl
  moon_N = regN "Mond" ; ---- Pl
  mother_N2 = mkN2 (reg2N "Mutter" "Mütter" feminine) von_Prep ;
  mountain_N = regN "Berg" ;
  music_N = reg2N "Musik" "Musiken" feminine ;
  narrow_A = regA "schmal" ;
  new_A = regA "neu" ;
  newspaper_N = regN "Zeitung" ;
{-
  oil_N = regN "Öl" ; ----
  old_A = mkA "alt" "gammalt" "gamla" "gamla" "äldre" "äldst" "äldsta" ;
  open_V2 = dirV2 (regV "öppna") ;
  paint_V2A = mkV2A (regV "måla") [] ;
  paper_N = mkN "papper" "pappret" "papper" "pappren" ;
  peace_N = regN "fred" ; ---- ar?
  pen_N = regN "penna" ;
  planet_N = reg2N "planet" "planeter" ;
  plastic_N = reg2N "plast" "plaster" ;
  play_V2 = dirV2 (regV "spela") ;
  policeman_N = reg2N "polis" "poliser" ;
  priest_N = reg2N "präst" "präster" ;
  probable_AS = mkAS (regA "sannolik") ;
  queen_N = regN "drottning" ;
  radio_N = regN "radio" ; ----
  rain_V0 = mkV0 (regV "regna") ;
  read_V2 = dirV2 (mk2V "läsa" "läste") ;
  red_A = mk2A "röd" "rött" ;
  religion_N = reg2N "religion" "religioner" ;
  restaurant_N = reg2N "restaurang" "restauranger" ;
  river_N = mkN "å" "ån" "åar" "åarna" ;
  rock_N = regN "sten" ;
  roof_N = regN "tak"  ;
  rubber_N = mkN "gummi" "gummit" "gummin" "gummina" ;
  run_V = (irregV "springa" "sprang" "sprungit") ;
  say_VS = mkVS (mkV "säga" "säger" "säg" "sade" "sagt" "sagd") ;
  school_N = regN "skola";
  science_N = reg2N "vetenskap" "vetenskaper" ;
  sea_N = mkN "sjö" "sjön" "sjöar" "sjöarna" ;
  seek_V2 = dirV2 (mk2V "söka" "sökte") ;
  see_V2 = dirV2 (mkV "se" "ser" "se" "såg" "sett" "sedd") ;
  sell_V3 = dirV3 (irregV "sälja" "sålde" "sålt") "till" ;
  send_V3 = dirV3 (regV "skicka") "till" ;
  sheep_N = reg2N "får" "får" ;
  ship_N = regN "skepp"  ;
  shirt_N = regN "skjorta" ;
  shoe_N = regN "sko" ;
  shop_N = reg2N "affär" "affären" ;
  short_A = regA "kort" ;
  silver_N = mkN "silver" "silvret" "silver" "silvren" ;
  sister_N = reg2N "syster" "systrar" ;
  sleep_V = (irregV "sova" "sov" "sovit") ;
  small_A = mkA "liten" "litet" "lilla" "små" "mindre" "minst" "minsta" ;
  snake_N = regN "orm" ;
  sock_N = regN "strumpa" ;
  speak_V2 = dirV2 (regV "tala") ;
  star_N = regN "stjärna" ;
  steel_N = regN "stål" ;
  stone_N = regN "sten" ;
  stove_N = regN "spis" ;
  student_N = reg2N "student" "studenter" ;
  stupid_A = mk3A "dum" "dumt" "dumma" ;
  sun_N = regN "sol" ;
  switch8off_V2 = dirV2 (partV (irregV "stänga" "stängde" "stängt") "av") ;
  switch8on_V2 = dirV2 (partV (irregV "slå" "slog" "slagit") "på") ;
  table_N = regN "bord"  ;
  talk_V3 = mkV3 (regV "prata") "till" "om" ;
  teacher_N = reg2N "lärare" "lärare" ;
  teach_V2 = dirV2 (regV "undervisa") ;
  television_N = reg2N "television" "televisioner" ;
  thick_A = regA "tjock" ;
  thin_A = mk2A "tunn" "tunt" ;
  train_N = regN "tåg"  ;
  travel_V = mk2V "resa" "reste" ;
  tree_N = regN "träd"  ;
  ----  trousers_N = regN "trousers" ; ---- pl t !
  ugly_A = regA "ful" ;
  understand_V2 = dirV2 (mkV "förstå" "förstår" "förstå" "förstod" "förstått" "förstådd") ;
  university_N = regN "universitet"  ;
  village_N = mkN "by" "byn" "byar" "byarna" ;
  wait_V2 = mkV2 (regV "vänta") "på" ;
  walk_V = (mkV "gå" "går" "gå" "gick" "gått" "gången") ;
  warm_A = regA "varm" ;
  war_N = regN "krig" ;
  watch_V2 = mkV2 (regV "titta") "på" ;
  water_N = mkN "vatten" "vattnet" "vatten" "vattnen" ;
  white_A = regA "vit" ;
  window_N = mkN "fönster" "fönstret" "fönster" "fönstren" ;
  wine_N = mkN "vin" "vinet" "viner" "vinerna" ; ----
  win_V2 = dirV2 (irregV "vinna" "vann" "vunnit") ;
  woman_N = regN "kvinna" ;
  wonder_VQ = mkVQ (regV "undra") ;
  wood_N = mkN "trä" "träet" "träen" "träena" ; ---- ?
  write_V2 = dirV2 (irregV "skriva" "skrev" "skrivit") ;
  yellow_A = regA "gul" ;
  young_A = irregA "ung" "yngre" "yngst" ;

  do_V2 = dirV2 (mkV "göra" "gör" "gör" "gjorde" "gjort" "gjord") ;
  now_Adv = mkAdv "nu" ;
  already_Adv = mkAdv "redan" ;
  song_N = reg2N "sång" "sånger" ;
  add_V3 = mkV3 (partV (irregV "lägga" "lade" "lagt") "till") [] "till" ;
  number_N = mkN "nummer" "numret" "numren" "numren" ;
  put_V2 = mkV2 (mkV "sätta" "sätter" "sätt" "satte" "satt" "satt") [] ;
  stop_V = regV "stanna" ;
  jump_V = regV "hoppa" ;
-}
} ;
