all: gfdoc htmls

htmls:
	htmls gf-resource.html

gfdoc:
	gfdoc ../abstract/Categories.gf ; mv ../abstract/Categories.html .
	gfdoc ../abstract/Rules.gf ; mv ../abstract/Rules.html .
	gfdoc ../abstract/Clause.gf ; mv ../abstract/Clause.html .
	gfdoc ../abstract/Structural.gf ; mv ../abstract/Structural.html .
	gfdoc ../abstract/Basic.gf ; mv ../abstract/Basic.html .
	gfdoc ../abstract/Time.gf ; mv ../abstract/Time.html .
	gfdoc ../abstract/Lang.gf ; mv ../abstract/Lang.html .
	gfdoc ../swedish/ParadigmsSwe.gf ; mv ../swedish/ParadigmsSwe.html .
	gfdoc ../swedish/BasicSwe.gf ; mv ../swedish/BasicSwe.html .
	gfdoc ../english/ParadigmsEng.gf ; mv ../english/ParadigmsEng.html .
