--# -path=.:../scandinavian:../common:../abstract:../../prelude

concrete LexiconDan of Lexicon = CatDan ** 
  open Prelude, ParadigmsDan, IrregDan in {

flags startcat=Phr ; lexer=textlit ; unlexer=text ;
  optimize=values ;

lin
  airplane_N = mk2N "fly" "flyet" ;
  answer_V2S = mkV2S (regV "svare") "til" ;
  apartment_N = mk2N "værelse" "værelsen" ;
  apple_N = mk2N "æble" "æblet" ;
  art_N = mk2N "kunst" "kunsten" ;
  ask_V2Q = mkV2Q spørge_V [] ;
  baby_N = mk2N "baby" "babyen" ; ---- babyen
  bad_A = regADeg "dårlig" ; ----
  bank_N = mk2N "bank" "banken" ;
  beautiful_A = mk3ADeg "smuk" "smukt" "smukke" ; ----
  become_VA = mkVA blive_V ;
  beer_N = regGenN "øl" neutrum ;
  beg_V2V = mkV2V bede_V [] "att" ;
  big_A = irregADeg "stor" "større" "størst";
  bike_N = mkN "cykel" "cykeln" "cykler" "cyklene" ; ----
  bird_N = mk2N "fugl" "fuglen" ;
  black_A = mk2ADeg "sort" "sort" ;
  blue_A = mk2ADeg "blå" "blått";
  boat_N = regGenN "båd" utrum ;
  book_N = mkN "bog" "bogen" "bøger" "bøgene" ;
  boot_N = mkN "støvle" "støvlen" "støvler" "støvlene" ;
  boss_N = mk2N "chef" "chefen" ;
  boy_N = regGenN "dreng" utrum ;
  bread_N = regGenN "brød" neutrum ;
  break_V2 = dirV2 (mk2V "knuse" "knuste") ;
  broad_A = regADeg "bred" ;
  brother_N2 = mkN2 ( (mkN "broder" "broderen" "brødre" "brødrene")) "til" ; ----
  brown_A = regADeg "brun" ;
  butter_N = regGenN "smør" neutrum ;
  buy_V2 = dirV2 (mk2V "købe" "købte") ; ----
  camera_N = mk2N "kamera" "kameraen" ; ----
  cap_N = mk2N "hue" "huen" ;
  car_N = regGenN "bil" utrum ;
  carpet_N = regGenN "tæppe" utrum ;
  cat_N = mk2N "kat" "katen" ;
  ceiling_N = regGenN "loft" neutrum ; ----
  chair_N = regGenN "stol" utrum ;
  cheese_N = regGenN "ost" utrum ;
  child_N = mkN "barn" "barnet" "børn" "børnen" ; ----
  church_N = regGenN "kirke" utrum ;
  city_N = mk2N "by" "byen" ;
  clean_A = regADeg "ren" ;
  clever_A = regADeg "flink" ;
  close_V2 = dirV2 (mk2V "lukke" "lukket") ;
  coat_N = regGenN "frakke" utrum ;
  cold_A = regADeg "kold" ;
  come_V = komme_V ;
  computer_N = mk2N "datamaskine" "datamaskinen" ;
  country_N = mk2N "land" "landet" ;
  cousin_N = mk2N "fætter" "fætteren" ; ----
  cow_N = mkN "ku" "kua" "kyr" "kyrne" ; ----
  die_V = dø_V ;
  dirty_A = regADeg "smudsig" ; ----
  distance_N3 = mkN3 (regGenN "afstand" utrum) "fra" "til" ;
  doctor_N = mk2N "læge" "lægen" ;
  dog_N = regGenN "hund" utrum ;
  door_N = regGenN "dør" utrum ;
  drink_V2 = dirV2 drikke_V ;
  easy_A2V = mkA2V (regA "nem") "for" ; ----
  eat_V2 = dirV2 (mk2V "spise" "spiste") ;
  empty_A = mkADeg "tøm" "tømt" "tømme" "tømmere" "tømmest" ; ----
  enemy_N = regGenN "fjende" utrum ;
  factory_N = mk2N "fabrik" "fabriken" ;
  father_N2 = mkN2 ( (mkN "far" "faderen" "fædre" "fædrene")) "til" ; ----
  fear_VS = mkVS (regV "frygte") ;
  find_V2 = dirV2 (irregV "finde" "fand" "fundet") ; ----
  fish_N = mk2N "fisk" "fisken" ;
  floor_N = regGenN "gulv" neutrum ;
  forget_V2 = dirV2 (mkV "glemme" "glemmer" "glemmes" "glemte" "glemt" "glem") ; ----
  fridge_N = regGenN "køleskab" neutrum ;
  friend_N = mkN "ven" "vennen" "venner" "vennene" ; ----
  fruit_N = mk2N "frugt" "frugten" ;
  fun_AV = mkAV (mkA "morsom" "morsomt" "morsomme") ; ----
  garden_N = regGenN "have" utrum ;
  girl_N = regGenN "pige" utrum ;
  glove_N = regGenN "handske" utrum ;
  gold_N = regGenN "guld" neutrum ;
  good_A = mkADeg "god" "godt" "gode" "bedre" "bedst" ; ----
  go_V = gå_V ;
  green_A = mk2ADeg "grøn" "grønt" ;
  harbour_N = regGenN "havn" utrum;
  hate_V2 = dirV2 (regV "hade") ;
  hat_N = regGenN "hat" utrum ;
  have_V2 = dirV2 have_V ;
  hear_V2 = dirV2 (mk2V "høre" "hørte") ;
  hill_N = regGenN "høj" utrum ;
  hope_VS = mkVS (regV "håbe") ;
  horse_N = regGenN "hest" utrum ;
  hot_A = regADeg "hed" ;
  house_N = regGenN "hus" neutrum ;
  important_A = regADeg "vigtig" ;
  industry_N = mk2N "industri" "industrien" ;
  iron_N = regGenN "jern" neutrum ;
  king_N = regGenN "konge" utrum ;
  know_V2 = dirV2 vide_V ;
  lake_N = regGenN "sø" utrum ;
  lamp_N = regGenN "lampe" utrum ;
  learn_V2 = dirV2 (mk2V "lære" "lærte") ; 
  leather_N = regGenN "læder" neutrum ;
  leave_V2 = dirV2 forlade_V ;
  like_V2 = mkV2 holde_V "af" ;
  listen_V2 = dirV2 (regV "lytte") ;
  live_V = mk2V "leve" "levde" ;
  long_A = irregADeg "lang" "længer" "længst" ; ----
  lose_V2 = dirV2 (regV "tabe") ;
  love_N = regGenN "kærlighed" utrum ;
  love_V2 = dirV2 (regV "elske") ;
  man_N =  (mkN "mand" "manden" "mænd" "mænden") ; ----
  married_A2 = mkA2 (mk2A "gift" "gift") "med" ;
  meat_N = regGenN "kød" neutrum ;
  milk_N = regGenN "mælk" utrum ;
  moon_N = regGenN "måne" utrum ;
  mother_N2 = mkN2 (mkN "moder" "moderen" "mødre" "mødrene") "til" ; ----
  mountain_N = regGenN "bjerg" neutrum ;
  music_N = mk2N "musik" "musiken" ;
  narrow_A = regADeg "smal" ;
  new_A = mkADeg "ny" "nytt" "nye" "nyere" "nyest" ;
  newspaper_N = regGenN "avis" utrum ;
  oil_N = regGenN "olie" utrum ;
  old_A = mkADeg "gammel" "gammelt" "gamle" "ældre" "ældst" ; ----
  open_V2 = dirV2 (regV "åbne") ;
  paint_V2A = mkV2A (regV "male") [] ;
  paper_N = regGenN "papir" neutrum ; ----
  paris_PN = regPN "Paris" neutrum ;
  peace_N = regGenN "fred" utrum ;
  pen_N = regGenN "pen" utrum ;
  planet_N = mk2N "planet" "planeten" ;
  plastic_N = mk2N "plast" "plasten" ;
  play_V2 = dirV2 (mk2V "spille" "spilte") ;
  policeman_N = mk2N "politibetjent" "politibetjenten" ; ----
  priest_N = mk2N "præst" "præsten" ;
  probable_AS = mkAS (regA "sandsynlig") ;
  queen_N = regGenN "dronning" utrum ;
  radio_N = regGenN "radio" utrum ;
  rain_V0 = mkV0 (regV "regne") ;
  read_V2 = dirV2 (mk2V "læse" "læste") ;
  red_A = regADeg "rød" ;
  religion_N = mk2N "religion" "religionen" ;
  restaurant_N = mk2N "restaurant" "restauranten" ;
  river_N = mk2N "flod" "floden" ;
  rock_N = regGenN "sten" utrum ;
  roof_N = regGenN "tag" neutrum ;
  rubber_N = mk2N "gummi" "gummien" ;
  run_V = regV "løbe" ;
  say_VS = mkVS sige_V ;
  school_N = regGenN "skole" utrum;
  science_N = mk2N "videnskab" "videnskaben" ;
  sea_N = mk2N "hav" "havet" ;
  see_V2 = dirV2 se_V ;
  seek_V2 = mkV2 (mk2V "søge" "søgte") "efter" ;
  sell_V3 = dirV3 sælge_V "til" ;
  send_V3 = dirV3 (mk2V "sende" "sendte") "til" ;
  sheep_N = mk2N "får" "fåret" ;
  ship_N = regGenN "skib" neutrum ;
  shirt_N = regGenN "skjorte" utrum ;
  shoe_N = regGenN "sko" utrum ;
  shop_N = mk2N "butik" "butiken" ;
  short_A = regADeg "kort" ;
  silver_N = mk2N "sølv" "sølvet";
  sister_N = mkN "søster" "søsteren" "søstrer" "søstrene" ; ----
  sleep_V = irregV "sove" "sov" "sovet" ;
  small_A = mkADeg "lille" "lille" "små" "mindre" "mindst" ; ----
  snake_N = regGenN "slange" utrum ;
  sock_N = regGenN "sok" utrum ;
  speak_V2 = dirV2 (regV "tale") ; ----
  star_N = regGenN "stjerne" utrum ;
  steel_N = regGenN "stål" neutrum ;
  stone_N = regGenN "sten" utrum ;
  stove_N = regGenN "komfur" utrum ;
  student_N = mk2N "student" "studenten" ;
  stupid_A = mk3ADeg "dum" "dumt" "dumme" ;
  sun_N = regGenN "sol" utrum ;
  switch8off_V2 = dirV2 (partV (regV "lukke") "for") ;
  switch8on_V2 = dirV2 (partV (regV "lukke") "op") ;
  table_N = regGenN "bord" neutrum ;
  talk_V3 = mkV3 (regV "tale") "til" "om" ;
  teacher_N = mkN "lærer" "læreren" "lærere" "lærerne" ;
  teach_V2 = dirV2 (mk2V "undervise" "underviste") ;
  television_N = mk2N "fjernsyn" "fjernsynet" ;
  thick_A = mk2ADeg "tyk" "tykt" ;
  thin_A = mk2ADeg "tynd" "tyndt" ; ----
  train_N = regGenN "tog" neutrum ;
  travel_V = mk2V "rejse" "rejste" ;
  tree_N = mkN "træ" "træet" "trær" "træne" ; ----
  ----  trousers_N = regGenN "trousers" ; ---- pl t !
  ugly_A = regADeg "grim" ;
  understand_V2 = dirV2 (irregV "forstå" "forstod" "forstått") ;
  university_N = regGenN "universitet" neutrum ;
  village_N = mk2N "landsby" "landsbyen" ;
  wait_V2 = mkV2 (regV "vente") "på" ;
  walk_V = (irregV "gå" "gikk" "gått") ;
  warm_A = regADeg "varm" ;
  war_N = regGenN "krig" utrum ;
  watch_V2 = mkV2 se_V "på" ;
  water_N = mk2N "vand" "vandet" ;
  white_A = regADeg "hvid" ;
  window_N = mkN "vindue" "vinduet" "vinduer" "vinduene" ; ---- er?
  wine_N = mk2N "vin" "vinen" ;
  win_V2 = dirV2 (irregV "vinde" "vand" "vundet") ;
  woman_N = regGenN "kvinde" utrum ;
  wonder_VQ = mkVQ (depV (regV "undre")) ;
  wood_N = mkN "træ" "træet" "trær" "træne" ; ----
  write_V2 = dirV2 (irregV "skrive" "skrev" "skrevet") ;
  yellow_A = regADeg "gul" ;
  young_A = irregADeg "ung" "yngre" "yngst" ; ----

  do_V2 = dirV2 (irregV "gøre" "gjorde" "gjort") ; ----
  now_Adv = mkAdv "nu" ;
  already_Adv = mkAdv "allerede" ;
  song_N = mk2N "sang" "sangen" ;
  add_V3 = mkV3 (regV "tilføje") [] "til" ; ----
  number_N = mk2N "nummer" "nummeret" ; ----
  put_V2 = mkV2 (irregV "sætte" "satte" "satt") [] ; ----
  stop_V = regV "standse" ;
  jump_V = regV "hoppe" ;

  left_Ord = {s = "venstre" ; isDet = True} ;
  right_Ord = {s = "højre" ; isDet = True} ;
  far_Adv = mkAdv "fjern" ;
  correct_A = regA "rigtig" ;
  dry_A = mk2A "tør" "tørt" ;
  dull_A = regA "sløv" ;
  full_A = regA "fuld" ;
  heavy_A = irregADeg "tung" "tyngre" "tyngst" ;
  near_A = mkADeg "nære" "nære" "nære" "nærmere" "nærmest" ;
  rotten_A = mk3ADeg "rådden" "råddent" "rådne" ; ----
  round_A = regA "rund" ;
  sharp_A = regA "skarp" ;
  smooth_A = regA "jævn" ;
  straight_A = regA "ret" ;
  wet_A = regA "våd" ;
  wide_A = regA "bred" ;
  animal_N = mk2N "dyr" "dyret" ;
  ashes_N = mk2N "aske" "asken" ;
  back_N = mk2N "ryg" "ryggen" ; ----
  bark_N = mk2N "bark" "barken" ;
  belly_N = mk2N "mave" "maven" ;
  blood_N = mk2N "blod" "blodet" ;
  bone_N = mk2N "ben" "benet" ;
  breast_N = mk2N "bryst" "brystet" ;
  cloud_N = mk2N "sky" "skyen" ;
  day_N = mk2N "dag" "dagen" ;
  dust_N = mk2N "støv" "støvet" ;
  ear_N = mk2N "øre" "øret" ;
  earth_N = mk2N "jord" "jorden" ;
  egg_N = mk2N "æg" "æget" ;
  eye_N = mkN "øje" "øjet" "øjne" "øjnene" ;
  fat_N = mk2N "fedt" "fedtet" ;
  feather_N = mk2N "fjer" "fjeren" ;
  fingernail_N = mk2N "negl" "neglen" ;
  fire_N = mk2N "ild" "ilden" ;
  flower_N = mk2N "blomst" "blomsten" ;
  fog_N = mk2N "tåge" "tågen" ;
  foot_N = mk2N "fod" "føder" ; ----
  forest_N = mk2N "skov" "skoven" ;
  grass_N = mk2N "græs" "græset" ;
  guts_N = mk2N "tarm" "tarmen" ; ---- indvolde
  hair_N = mk2N "hår" "håret" ;
  hand_N = mk2N "hånd" "hånden" ;
  head_N = mk2N "hoved" "hovedet" ;
  heart_N = mk2N "hjerte" "hjertet" ;
  horn_N = mk2N "horn" "hornet" ;
  husband_N = mk2N "ægtefælle" "ægtefællen" ; ----
  ice_N = mk2N "is" "isen" ;
  knee_N = mkN "knæ" "knæt" "knær" "knæne" ; ----
  leaf_N = mk2N "løv" "løvet" ;
  leg_N = mk2N "ben" "benet" ;
  liver_N = mkN "lever" "leveren" "levrer" "levrene" ; ----
  louse_N = mk2N "lus" "lusen" ;
  mouth_N = mk2N "mund" "munden" ;
  name_N = mk2N "navn" "navnet" ;
  neck_N = mk2N "hals" "halsen" ;
  night_N = mkN "nat" "natten" "nætter" "nættene" ; ----
  nose_N = mk2N "næse" "næsen" ;
  person_N = mk2N "person" "personen" ;
  rain_N = mk2N "regn" "regnet" ;
  road_N = mk2N "vej" "vejen" ;
  root_N = mkN "rod" "roden" "røder" "rødene" ; ----
  rope_N = mk2N "reb" "rebet" ;
  salt_N = mk2N "salt" "saltet" ;
  sand_N = mk2N "sand" "sanden" ;
  seed_N = mk2N "frø" "frøet" ;
  skin_N = mk2N "skind" "skindet" ;
  sky_N = mkN "himmel" "himmelen" "himler" "himlene" ; ----
  smoke_N = mk2N "røg" "røgen" ;
  snow_N = mk2N "snø" "snøen" ;
  stick_N = mk2N "pind" "pinden" ;
  tail_N = mk2N "hale" "halen" ;
  tongue_N = mk2N "tunge" "tungen" ;
  tooth_N = mkN "tand" "tanden" "tænder" "tændene" ; ----
  wife_N = mk2N "kone" "konen" ;
  wind_N = mk2N "vind" "vinden" ;
  wing_N = mk2N "vinge" "vingen" ;
  worm_N = mk2N "orm" "ormen" ;
  year_N = mk2N "år" "året" ;
  bite_V2 = dirV2 bide_V ;
  blow_V = mk2V "blæse" "blæste" ;
  burn_V = brænde_V ;
--  count_V2 = dirV2 tælle_V ;
  cut_V2 = dirV2 (skære_V) ;
  dig_V = mk2V "grave" "gravde" ;
  fall_V = falle_V ;
  fear_V2 = dirV2 (regV "frygte") ;
  fight_V2 = dirV2 (regV "kæmpe") ;
  float_V = flyde_V ;
  flow_V = regV "strømme" ;
  fly_V = flyve_V ;
  freeze_V = fryse_V ;
  give_V3 = dirdirV3 give_V ;
  hit_V2 = dirV2 (slå_V) ;
  hold_V2 = dirV2 (holde_V) ;
  hunt_V2 = dirV2 (regV "jage") ;
  kill_V2 = dirV2 (regV "dræbe") ;
  laugh_V = le_V ;
  lie_V = ligge_V ;
  play_V = regV "spille" ;
  pull_V2 = dirV2 (regV "trække") ;
  push_V2 = dirV2 (regV "skubbe") ;
  rub_V2 = dirV2 (gnide_V) ;
  scratch_V2 = dirV2 (regV "kradse") ;
  sew_V = mk2V "sy" "sydde" ;
  sing_V = synge_V ;
  sit_V = sidde_V ;
  smell_V = regV "lugte" ;
  spit_V = regV "spytte" ;
  split_V2 = dirV2 (regV "splitte") ; ----
  squeeze_V2 = dirV2 (regV "presse") ;
  stab_V2 = dirV2 (stikke_V) ;
  stand_V = stå_V ;
  suck_V2 = dirV2 (regV "sutte") ; ----
  swell_V = regV "svulme" ;
  swim_V = regV "svømme" ;
  think_V = mk2V "tænke" "tænkte" ; ----
  throw_V2 = dirV2 (regV "kaste") ;
--  tie_V2 = dirV2 binde_V ;
  turn_V = regV "dreje" ;
  vomit_V = partV (regV "kaste") "op" ;
  wash_V2 = dirV2 (regV "vaske") ;
  wipe_V2 = dirV2 (regV "viske") ;
  breathe_V = regV "ånde" ;


} ;

