strings:
	runghc -i../../../src FileThai.hs StringsThai.gf >StringsTha.gf
pronstrings:
	runghc -i../../../src FileThai.hs -p StringsThai.gf >pronunciation/StringsTha.gf
wordlist:
	runghc -i../../../src FileThai.hs -w StringsThai.gf

