//
//  StyleKitGF.m
//  GF Offline Translator
//
//  Created by Cenny Davidsson on 2015-05-04.
//  Copyright (c) 2015 Grammatical Framework. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitGF.h"


@implementation StyleKitGF

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawArrowsWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.376 green: 0.569 blue: 0.957 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69762 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23671 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69762 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23671 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52286 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52286 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69762 * CGRectGetHeight(frame))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.26072 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94521 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63937 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.26072 * CGRectGetHeight(frame))];
    [bezierPath closePath];
    [color setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46475 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76744 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46475 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76744 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28998 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28998 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46475 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02784 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71233 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40649 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02784 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [color setFill];
    [bezier2Path fill];
}

+ (void)drawMenyItemWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.376 green: 0.569 blue: 0.957 alpha: 1];

    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 3, floor((CGRectGetWidth(frame) - 1) * 0.28037 + 0.5), CGRectGetHeight(frame) - 6)];
    [color setFill];
    [ovalPath fill];


    //// Oval 2 Drawing
    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.36111 + 0.5), CGRectGetMinY(frame) + 3, floor(CGRectGetWidth(frame) * 0.63889 + 0.5) - floor(CGRectGetWidth(frame) * 0.36111 + 0.5), CGRectGetHeight(frame) - 6)];
    [color setFill];
    [oval2Path fill];


    //// Oval 3 Drawing
    UIBezierPath* oval3Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frame) + floor((CGRectGetWidth(frame) - 2) * 0.71698 + 0.5), CGRectGetMinY(frame) + 3, CGRectGetWidth(frame) - 2 - floor((CGRectGetWidth(frame) - 2) * 0.71698 + 0.5), CGRectGetHeight(frame) - 6)];
    [color setFill];
    [oval3Path fill];
}

@end
