include config.mk

GF_DATA_DIR=$(datadir)/GF-$(PACKAGE_VERSION)

.PHONY: install
install: 
	$(INSTALL) -d $(bindir)
	$(INSTALL) gf gfdoc jgf $(bindir)
	$(INSTALL) -d $(GF_DATA_DIR)
	$(INSTALL) -m 0644 gf-java.jar $(GF_DATA_DIR)
