include config.mk

GF_LIB_DIR=$(libdir)/GF-$(PACKAGE_VERSION)

install: 
	$(INSTALL) -d $(bindir)
	$(INSTALL) gf gfdoc jgf $(bindir)
	$(INSTALL) -d $(GF_LIB_DIR)
	$(INSTALL) -m 0644 gf-java.jar $(GF_LIB_DIR)
