#!/bin/sh

prefix="/usr/local"

case "i386-apple-darwin9.3.0" in
      *-cygwin)
          prefix=`cygpath -w "$prefix"`;;
esac

exec_prefix="${prefix}"
GF_BIN_DIR="${exec_prefix}/bin"
GF_DATA_DIR="${prefix}/share/GF-3.0-beta"

GFBIN="$GF_BIN_DIR/gf"

if [ ! -x "${GFBIN}" ]; then
   GFBIN=`which gf`
fi

if [ ! -x "${GFBIN}" ]; then
    echo "gf not found."
    exit 1
fi

exec $GFBIN --batch "$@"
